src/objects/ACCL__Product_Assortment__c.object
<CustomObject>
    <description>Holds the details of a set of products which are often used together.</description>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds the description of language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Obligatory__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Denotes whether this is a closed listing. Used by the system.</description>
        <inlineHelpText>Relevant only for Assortment List, to define closed listing.</inlineHelpText>
        <label>Obligatory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Product_Assortment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to product assortment template.</description>
        <label>Product Assortment Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Product_Assortment_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Product_Assortment_Template__c</referenceTo>
        <relationshipLabel>Product Assortments</relationshipLabel>
        <relationshipName>Product_Assortments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the product assortment belongs to.</description>
        <formula>TEXT(ACCL__Product_Assortment_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Version_Off_Platform_APL__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Stores off platform version number of Account product list.</description>
        <label>Version Off Platform APL</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACCL__Version__c</fullName>
        <description>Stores version number of Authorization list.</description>
        <label>Version</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Assortment</label>
    <nameField>
        <label>Product Assortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Assortments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Product_Assortment_Template__c.object
<CustomObject>
    <description>Template for product assortments. Controls the behaviour of the instances of this template, for example if a business partner must be specified (AccountMultiplicity). This table is sales organization dependent.</description>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds the description of language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the product assortment template belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Product Assortment Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Assortment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddOnProductAssortmentTestFactory.cls
@isTest
public class AddOnProductAssortmentTestFactory{
    public static ACCL__Product_Assortment__c defaultProductAssortment;
    public static ACCL__Product_Assortment__c defaultProductAssortmentQueried;
    public static ACCL__Product_Assortment__c buildProductAssortment(Integer nameSuffix,ACCL__Product_Assortment_Template__c productAssortmentTemplate) {
        ACCL__Product_Assortment__c productAssortment = new ACCL__Product_Assortment__c();
        productAssortment.Name= AddOnConstants.Name+nameSuffix;
        productAssortment.ACCL__Product_Assortment_Template__c = productAssortmentTemplate.id; 
        productAssortment.ACCL__Valid_From__c = System.today();
        productAssortment.ACCL__Valid_Thru__c = System.today().addYears(1);
        productAssortment.ACCL__Description_Language_1__c='English';
        productAssortment.ACCL__Version__c = 0;
        productAssortment.ACCL__Version_Off_Platform_APL__c = 0;
        return productAssortment;
    }
    public static ACCL__Product_Assortment__c buildDefaultProductAssortment() {
        return buildProductAssortment(-1,AddOnPrdAssortmentTemplateTestFactory.getDefaultproductAssortmentTemplate());
    }
    public static ACCL__Product_Assortment__c insertProductAssortment(integer i,ACCL__Product_Assortment_Template__c productAssortmentTemplate) {
        ACCL__Product_Assortment__c productAssortment = buildProductAssortment(i,productAssortmentTemplate);
        insert productAssortment;       
        return productAssortment;
    }
    public static ACCL__Product_Assortment__c getDefaultProductAssortment() {
        if( defaultProductAssortment == null ){
            defaultProductAssortment = insertProductAssortment(-1,AddOnPrdAssortmentTemplateTestFactory.getDefaultproductAssortmentTemplate());            
            defaultProductAssortmentQueried = [select id, ACCL__sales_org__c,Name,ACCL__Product_Assortment_Template__c,
                                               ACCL__Valid_From__c,ACCL__Valid_Thru__c,ACCL__Description_Language_1__c
                                               from ACCL__Product_Assortment__c where id =:defaultProductAssortment.id];
        }
        return defaultProductAssortmentQueried;
    }
    public static List<ACCL__Product_Assortment__c> buildProductAssortments( List<ACCL__Product_Assortment_Template__c> lstproductAssortmentTemplates) {
        List<ACCL__Product_Assortment__c> productAssortments = new List<ACCL__Product_Assortment__c>();
        for(integer i=0; i < lstproductAssortmentTemplates.size(); i++){
            productAssortments.add(buildProductAssortment(i,lstproductAssortmentTemplates[i]));
        }
        return productAssortments;
    }
    public static List<ACCL__Product_Assortment__c> insertProductAssortments(List<ACCL__Product_Assortment_Template__c> lstproductAssortmentTemplates) {
        List<ACCL__Product_Assortment__c> productAssortments=buildProductAssortments(lstproductAssortmentTemplates); 
        insert productAssortments;
        return productAssortments;
    }
    public static ACCL__Product_Assortment__c getProductAssortmentWithValidRange(Date validFrom,Date validThru,ACCL__Product_Assortment_Template__c productAssortmentTemplate){
        ACCL__Product_Assortment__c productAssortment = new ACCL__Product_Assortment__c();
        productAssortment.Name= AddOnConstants.Name;
        productAssortment.ACCL__Product_Assortment_Template__c = productAssortmentTemplate.id; 
        productAssortment.ACCL__Valid_From__c = validFrom;
        productAssortment.ACCL__Valid_Thru__c = validThru;
        productAssortment.ACCL__Description_Language_1__c='English';
        insert productAssortment;
        return productAssortment;
    }
    public static ACCL__Product_Assortment__c getProductAssortmentDuplicate(String productAssortmentName,Date validFrom,Date validThru,ACCL__Product_Assortment_Template__c productAssortmentTemplate) {
        ACCL__Product_Assortment__c productAssortment = new ACCL__Product_Assortment__c();
        productAssortment.Name=productAssortmentName;
        productAssortment.ACCL__Product_Assortment_Template__c = productAssortmentTemplate.id; 
        productAssortment.ACCL__Valid_From__c = validFrom;
        productAssortment.ACCL__Valid_Thru__c = validThru;
        productAssortment.ACCL__Description_Language_1__c='English';
        return productAssortment;    
    }
    //Listing Finding
    public static ACCL__Product_Assortment__c getProductAssortmentWithValidRangeForListing(Date validFrom,Date validThru,ACCL__Product_Assortment_Template__c productAssortmentTemplate,Boolean Obligatory){
        ACCL__Product_Assortment__c productAssortment = new ACCL__Product_Assortment__c();
        productAssortment.Name = AddOnConstants.Name;
        productAssortment.ACCL__Product_Assortment_Template__c = productAssortmentTemplate.id; 
        productAssortment.ACCL__Valid_From__c = validFrom;
        productAssortment.ACCL__Valid_Thru__c = validThru;
        productAssortment.ACCL__Obligatory__c = Obligatory;
        productAssortment.ACCL__Description_Language_1__c='English';
        insert productAssortment;
        return productAssortment;
    }
}