src/objects/ACCL__Sales_Organization__c.object
<CustomObject>
    <description>This Object holds the details of the Sales Organization.</description>
    <fields>
        <fullName>ACCL__Currency__c</fullName>
        <description>Currency of the sales organization</description>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>NOK</fullName>
                </value>
                <value>
                    <fullName>CHF</fullName>
                </value>
                <value>
                    <fullName>RUB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Default_Price_List_Type__c</fullName>
        <description>Default price list type of the sales organization</description>
        <label>Default Price List Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WS1999</fullName>
                </value>
                <value>
                    <fullName>WS2000</fullName>
                </value>
                <value>
                    <fullName>NotRelevant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Default_Price_Type__c</fullName>
        <description>Default price type of the sales organization.</description>
        <label>Default Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>factory</fullName>
                </value>
                <value>
                    <fullName>consumer</fullName>
                </value>
                <value>
                    <fullName>NotRelevant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__First_Day_Of_Week__c</fullName>
        <description>Describes the days of the week</description>
        <label>First Day Of Week</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__First_Week_Of_Year__c</fullName>
        <description>This field displays the week for call scheduling</description>
        <label>First Week Of Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Global_Sales_Org__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Global Sales Org</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Language_1__c</fullName>
        <description>Language for the sales organization</description>
        <label>Language 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>it</fullName>
                </value>
                <value>
                    <fullName>es</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Language_2__c</fullName>
        <label>Language 2</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>it</fullName>
                </value>
                <value>
                    <fullName>es</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Language_3__c</fullName>
        <label>Language 3</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>it</fullName>
                </value>
                <value>
                    <fullName>es</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Language_4__c</fullName>
        <label>Language 4</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>it</fullName>
                </value>
                <value>
                    <fullName>es</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Promotion_Access_Definition_Policy__c</fullName>
        <description>Defines whether the edit and access rights are dependent on the product categories the user has assigned or the account and product category relationship.</description>
        <label>Promotion Access Definition Policy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Independent_Anchors</fullName>
                    <default>true</default>
                    <label>Independent Anchors</label>
                </value>
                <value>
                    <fullName>Combined_Anchors</fullName>
                    <label>Combined Anchors</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Promotion_Aggregation_Level__c</fullName>
        <description>Defines at which level the product is located.</description>
        <label>Promotion Aggregation Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Category</fullName>
                </value>
                <value>
                    <fullName>SubCategory</fullName>
                </value>
                <value>
                    <fullName>Brand</fullName>
                    <default>true</default>
                    <label>Brand</label>
                </value>
                <value>
                    <fullName>Flavor</fullName>
                </value>
                <value>
                    <fullName>Package</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org_Value__c</fullName>
        <label>Sales Org Value</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Sales Organization</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organization</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AddOnSalesOrgTestFactory.cls
@isTest
public with Sharing class AddOnSalesOrgTestFactory {
    //FLS_Create, FLS_Create_Partial - False Positive
    //This class is used for unit test data creation and is used in other test classes. It will be executed in System context, hence no FLS/CRUD check is required.
    //Default Sales_Organization__c
    public static ACCL__Sales_Organization__c defaultSalesOrg;
    public static ACCL__Sales_Organization__c defaultSalesOrganization;

    /**This function is for getting default SalesOrg Data 
    *  @name getDefaultSalesOrg
    *  @param No parameters
    *  @return Sales Org
    */
    public static ACCL__Sales_Organization__c getDefaultSalesOrg() {
        if( defaultSalesOrg == null ){
            defaultSalesOrg = insertSalesOrg();
        }
        return defaultSalesOrg;
    }

     /**This function is for inserting default SalesOrg Data 
    *  @name getDefaultSalesOrg
    *  @param No parameters
    *  @return Sales Org
    */
    public static ACCL__Sales_Organization__c insertSalesOrg()
    {
        ACCL__Sales_Organization__c sOrg = buildSalesOrg();
        insert sOrg;
        return sOrg;
    }

    /**This function is for building default SalesOrg Data 
    *  @name getDefaultSalesOrg
    *  @param No parameters
    *  @return Sales Org
    */
    public static ACCL__Sales_Organization__c buildSalesOrg() {
        return buildSalesOrgList()[0];
    }

    /**This function is for building List of Sales Org data
    *  @name buildSalesOrgList
    *  @param No parameters
    *  @return list of Sales Org
    */
    public static List<ACCL__Sales_Organization__c> buildSalesOrgList()
    {
        List<ACCL__Sales_Organization__c> listSalesOrg = new List<ACCL__Sales_Organization__c>();

        for(String salesOrg: AddOnUserTestFactory.getSalesOrg())
        {
            ACCL__Sales_Organization__c sOrg = new ACCL__Sales_Organization__c();
            sOrg.Name = salesOrg;
            sOrg.ACCL__Currency__c = 'USD';
            sOrg.ACCL__Default_Price_Type__c = 'Factory';
            sOrg.ACCL__Default_Price_List_Type__c = 'Direct Customers';
            sOrg.ACCL__Description_Language_1__c = salesOrg +  '(Engish)';

            //set the language using enums
            sOrg.ACCL__Language_1__c = AddOnConstants.LANGUAGE.en.name();
            sOrg.ACCL__Language_2__c = AddOnConstants.LANGUAGE.de.name();
            sOrg.ACCL__Language_3__c = AddOnConstants.LANGUAGE.es.name();
            sOrg.ACCL__Language_4__c = AddOnConstants.LANGUAGE.fr.name();
            
            //set Sales Org field value to pass validation 
            sOrg.ACCL__Sales_Org_Value__c = salesOrg;
            listSalesOrg.add(sOrg);
        }

        return listSalesOrg;
    }
     /**This function is for inserting List of Sales Org data
    *  @name buildSalesOrgList
    *  @param No parameters
    *  @return list of Sales Org
    */
    public static List<ACCL__Sales_Organization__c> insertSalesOrgList()
    {
        List<ACCL__Sales_Organization__c> listSalesOrg =  buildSalesOrgList();
        insert listSalesOrg;
        return listSalesOrg;
    }
     /**This function is for inserting Sales Org data for call planning
    *  @name insertSalesOrgData
    *  @param No parameters
    *  @return Sales Org
    */
    public static ACCL__Sales_Organization__c insertSaleOrgData(String firstDayOfWeek,String firstWeekOfYear ) {
        ACCL__Sales_Organization__c salesOrg = new ACCL__Sales_Organization__c();
        
        //commenting old name value and adding new Sales Organization name to pass the validation 
        //salesOrg.Name='global';
        salesOrg.Name= AddOnUserTestFactory.getSalesOrg()[0];
        salesOrg.ACCL__Sales_Org_Value__c = salesOrg.Name;
        
        salesOrg.ACCL__First_Day_Of_Week__c=firstDayOfWeek;
        salesOrg.ACCL__Description_Language_1__c='English';
        salesOrg.ACCL__First_Week_Of_Year__c=firstWeekOfYear;
        salesOrg.ACCL__Global_Sales_Org__c=true;
        insert salesOrg;
        return salesOrg;
    }
     /**This function is for inserting Sales Org data for call planning
    *  @name insertSalesOrgData
    *  @param No parameters
    *  @return Sales Org
    */
    //Test_Methods_With_No_Assert – False Positive
    //This class is used for unit test data creation and is used in other test classes. Hence assert is not required.
    public static ACCL__Sales_Organization__c insertSaleOrgData() {
        ACCL__Sales_Organization__c salesOrg = new ACCL__Sales_Organization__c();
        
        //commenting old name value and adding new Sales Organization name to pass the validation 
        //salesOrg.Name='global';
        salesOrg.Name= AddOnUserTestFactory.getSalesOrg()[0];
        salesOrg.ACCL__Sales_Org_Value__c = salesOrg.Name;
        
        salesOrg.ACCL__First_Day_Of_Week__c='1';
        salesOrg.ACCL__Description_Language_1__c='English';
        salesOrg.ACCL__First_Week_Of_Year__c='0';
        salesOrg.ACCL__Global_Sales_Org__c=false;
        insert salesOrg;
        return salesOrg;
    }
    public static ACCL__Consider_Default_SalesOrg__c insertDefaultSalesOrg() {
        ACCL__Consider_Default_SalesOrg__c defaultsales = new ACCL__Consider_Default_SalesOrg__c();
        defaultsales.ACCL__Consider_Global__c = True;
        insert defaultsales;
        return defaultsales;
    }
    //Test_Methods_With_No_Assert – False Positive
    //This class is used for unit test data creation and is used in other test classes. Hence assert is not required.
    public static ACCL__Sales_Organization__c insertGlobalSalesOrg(String Name,String Currency1){
            ACCL__Sales_Organization__c sOrg = new ACCL__Sales_Organization__c();
            sOrg.Name = Name;
            sOrg.ACCL__Currency__c = Currency1;
            sOrg.ACCL__Default_Price_Type__c = 'Factory';
            sOrg.ACCL__Default_Price_List_Type__c = 'Direct Customers';
            sOrg.ACCL__Description_Language_1__c = Name + '(Engish)';
            sOrg.ACCL__Global_Sales_Org__c = true;

            //set the language using enums
            sOrg.ACCL__Language_1__c = AddOnConstants.LANGUAGE.en.name();
            sOrg.ACCL__Language_2__c = AddOnConstants.LANGUAGE.de.name();
            sOrg.ACCL__Language_3__c = AddOnConstants.LANGUAGE.es.name();
            sOrg.ACCL__Language_4__c = AddOnConstants.LANGUAGE.fr.name();
            insert sOrg; 
            return sOrg;
    }
    //Test_Methods_With_No_Assert – False Positive
    //This class is used for unit test data creation and is used in other test classes. Hence assert is not required.
    public static ACCL__Sales_Organization__c insertSalesOrg(String Name, String Currency1){
            ACCL__Sales_Organization__c sOrg = new ACCL__Sales_Organization__c();
            sOrg.Name = Name;
            sOrg.ACCL__Currency__c = Currency1;
            sOrg.ACCL__Default_Price_Type__c = 'Factory';
            sOrg.ACCL__Default_Price_List_Type__c = 'Direct Customers';
            sOrg.ACCL__Description_Language_1__c = Name + '(Engish)';

            //set the language using enums
            sOrg.ACCL__Language_1__c = AddOnConstants.LANGUAGE.en.name();
            sOrg.ACCL__Language_2__c = AddOnConstants.LANGUAGE.de.name();
            sOrg.ACCL__Language_3__c = AddOnConstants.LANGUAGE.es.name();
            sOrg.ACCL__Language_4__c = AddOnConstants.LANGUAGE.fr.name();
            insert sOrg; 
            return sOrg;
    }
     /*************************************Method Which has been copied from Other SalesOrganizationTestFactory***********/ 
      //Author of this methods from origninal class is unknown. Defect Fix: Defect 326046:Duplicate SalesOrganisationTestFactory

      public static ACCL__Sales_Organization__c buildSalesOrganization( String name ){
            return buildSalesOrganization(name, false);
        }

       public static ACCL__Sales_Organization__c buildSalesOrganization( String name, Boolean isGlobal ) {
            ACCL__Sales_Organization__c salesOrg = new ACCL__Sales_Organization__c();
            salesOrg.Name = name; 
            salesOrg.ACCL__Description_Language_1__c = 'desc 1 ';
            salesOrg.ACCL__Language_1__c = 'English';
            salesOrg.ACCL__Currency__c = 'EUR';
            salesOrg.ACCL__First_Week_Of_Year__c = '1';
            salesOrg.ACCL__First_Day_Of_Week__c = '1';
            salesOrg.ACCL__Promotion_Aggregation_Level__c = 'Brand';
            salesOrg.ACCL__Global_Sales_Org__c = isGlobal;
            salesOrg.ACCL__Sales_Org_Value__c = name;
            return salesOrg;
        }

       public static ACCL__Sales_Organization__c buildDefaultSalesOrganization() {
            return buildSalesOrganization(AddOnUserTestFactory.getSalesOrg()[0], true);
        }

        //Test_Methods_With_No_Assert – False Positive
        //This class is used for unit test data creation and is used in other test classes. Hence assert is not required.
        public static ACCL__Sales_Organization__c insertSalesOrganization(String name){
            ACCL__Sales_Organization__c salesOrg = buildSalesOrganization( name );
            insert salesOrg;
            return salesOrg;
        }

        public static ACCL__Sales_Organization__c insertSalesOrganization(String name, String promotionAccessDefinitionPolicy){
            ACCL__Sales_Organization__c salesOrg = buildSalesOrganization( name );
            salesOrg.ACCL__Promotion_Access_Definition_Policy__c = promotionAccessDefinitionPolicy;
            insert salesOrg;
            return salesOrg;
        }

        public static ACCL__Sales_Organization__c insertDefaultSalesOrganization(){
            ACCL__Sales_Organization__c s = buildDefaultSalesOrganization();
            insert s;
            return s;
        }

        public static ACCL__Sales_Organization__c getDefaultSalesOrganization() {
            if( defaultSalesOrganization == null ){
                defaultSalesOrganization = insertDefaultSalesOrganization();
            }
            return defaultSalesOrganization;
        }
}