src/objects/ACCL__Product__c.object
<CustomObject>
    <description>This object records the attributes of a product.</description>
    <fields>
        <fullName>ACCL__Category__c</fullName>
        <description>Product category.</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Beverages</fullName>
                </value>
                <value>
                    <fullName>Chips</fullName>
                </value>
                <value>
                    <fullName>Detergent</fullName>
                </value>
                <value>
                    <fullName>Frozen</fullName>
                </value>
                <value>
                    <fullName>Hygiene</fullName>
                </value>
                <value>
                    <fullName>Snacks</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Delivery_Valid_From__c</fullName>
        <description>Delivery status valid from date.</description>
        <label>Delivery Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Delivery_Valid_Thru__c</fullName>
        <defaultValue>date(12,31,2099)</defaultValue>
        <description>Delivery status valid thru date.</description>
        <label>Delivery Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_1_Language_1__c</fullName>
        <description>Holds the first description of language 1.</description>
        <label>Description 1 Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Field_Valid_From__c</fullName>
        <description>Field status valid from date.</description>
        <label>Field Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Field_Valid_Thru__c</fullName>
        <defaultValue>date(12,31,2099)</defaultValue>
        <description>Field status valid thru date.</description>
        <label>Field Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Fund_Valid_From__c</fullName>
        <description>Fund Role status valid from date.</description>
        <label>Fund Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Fund_Valid_Thru__c</fullName>
        <description>Fund Role status valid thru date.</description>
        <label>Fund Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__KAM_Valid_From__c</fullName>
        <description>KAM status valid from date.</description>
        <label>KAM Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__KAM_Valid_Thru__c</fullName>
        <defaultValue>date(12,31,2099)</defaultValue>
        <description>KAM status valid thru date.</description>
        <label>KAM Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__New_Item_Valid_From__c</fullName>
        <description>New Item status valid from date.</description>
        <label>New Item Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__New_Item_Valid_Thru__c</fullName>
        <defaultValue>date(12,31,2099)</defaultValue>
        <description>New Item status valid thru date.</description>
        <label>New Item Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Product_Code__c</fullName>
        <description>Unique identification of a product.</description>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ACCL__Product_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to product template.</description>
        <label>Product Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Product_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Product_Template__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__State__c</fullName>
        <description>State of the product.</description>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
	 <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddOnProductTestFactory.cls
@isTest
public with sharing class AddOnProductTestFactory {
    
  public static ACCL__Product__c buildProduct(
    Integer nameSuffix,
    ACCL__Product_Template__c template
  ) {
    ACCL__Product__c product = new ACCL__Product__c();
    product.Name = AddOnConstants.NAME + nameSuffix;
    product.ACCL__State__c = '4';
    product.ACCL__Description_1_Language_1__c = 'description' + nameSuffix;
    product.ACCL__Product_Code__c = 'ProductCode' + nameSuffix;
    product.ACCL__Product_Template__c = template.Id;
    product.ACCL__Field_Valid_From__c = System.today();
    product.ACCL__Field_Valid_Thru__c = System.today().addMonths(5);
    product.ACCL__Delivery_Valid_From__c = System.today();
    product.ACCL__Delivery_Valid_Thru__c = System.today().addMonths(5);
    product.ACCL__KAM_Valid_From__c = System.today();
    product.ACCL__KAM_Valid_Thru__c = System.today().addMonths(5);
    product.ACCL__New_Item_Valid_From__c = System.today();
    product.ACCL__New_Item_Valid_Thru__c = System.today().addMonths(5);
    product.ACCL__Fund_Valid_From__c = System.today();
    product.ACCL__Fund_Valid_Thru__c = System.today().addMonths(5);
    product.ACCL__Category__c = null;
    return product;
  }

  //Test_Methods_With_No_Assert – False Positive
  //This class is used for unit test data creation and is used in other test classes. Hence assert is not required.
  public static List<ACCL__Product__c> insertProducts(Integer noOfRecords) {
    List<ACCL__Product__c> products = new List<ACCL__Product__c>();
    for (integer i = 0; i < noOfRecords; i++) {
      products.add(
        buildProduct(
          i,
          AddOnProductTemplateTestFactory.getDefaultProductTemplateForProduct()
        )
      );
    }
    insert products;
    return products;
  }
}