src/objects/ACCL__Account_Set__c.object
<CustomObject>
    <description>Object for the creation of Customer Sets.</description>
    <label>Customer Set</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Account_Set_Account__c.object
<CustomObject>
    <description>Junction object between Customer and Customer Set.</description>
    <fields>
        <fullName>ACCL__Account_Set_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Set Customers (Customer)</relationshipLabel>
        <relationshipName>Account_Set_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Account_Set__c</fullName>
        <description>Reference to Customer Set.</description>
        <label>Customer Set</label>
        <referenceTo>ACCL__Account_Set__c</referenceTo>
        <relationshipLabel>Customer Set Customers</relationshipLabel>
        <relationshipName>Account_Set_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Set Customer</label>
    <nameField>
        <displayFormat>ASA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Set Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Promotion__c.object
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <fields>
        <fullName>ACCL__Anchor_Account_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer Set</description>
        <label>Anchor Customer Set</label>
        <referenceTo>ACCL__Account_Set__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Anchor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Customer</description>
        <label>Anchor Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Account_Number__c</fullName>
        <description>Customer Number.</description>
        <label>Customer Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MDLZ_Ad_Break_Day__c</fullName>
        <defaultValue>&quot;Sunday&quot;</defaultValue>
        <label>Ad-Break Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MDLZ_Promotion_Store__c.object
<CustomObject>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>ACCL__Promotion__c</referenceTo>
        <relationshipLabel>Promotion Stores</relationshipLabel>
        <relationshipName>MDLZ_Promotion_Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotion Stores</relationshipLabel>
        <relationshipName>MDLZ_Promotion_Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion Store</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>MDLZ_Promotion_Store Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_PromotionStoreCreateBatchHandler.cls
/***************************************************************
Name: MDLZ_PromotionStoreCreateBatchHandler
======================================================
Purpose: Handler class for batch MDLZ_PromotionStoreCreateBatch, this class will and create Promotion Store records 
using either Account Hierarchy or Customer Set. Accounts will be queried for all the valid promotions 
based on the Anchor Customer or the Anchor customer set.

======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE                DETAIL              Description
1.0      Gaurav Gupta                 09/19/2022        Initial Development    

***************************************************************/
public with sharing class MDLZ_PromotionStoreCreateBatchHandler {

    public static void createPromoStoreRecord(List<ACCL__Promotion__c> promotionList){

        List<MDLZ_Promotion_Store__c> promotionStoreRecords = new List<MDLZ_Promotion_Store__c>();
        List<Database.SaveResult> srList = new List<Database.SaveResult>();
        MDLZ_ErrorExceptionHandler exc = new MDLZ_ErrorExceptionHandler();

        if(promotionList.size() > 1){
            exc.insertExceptions('MDLZ_PromotionStoreCreateBatchHandler()', MDLZ_ConstantHelper.promoExportBatchSizeError, 0, 'batchSizeError');
        } else {

            try{

                if(promotionList[0].ACCL__Anchor_Account__c != null){
                    //Query to fetch all L6 Accounts that are related to promotion Anchor Account in the Account Hierarchy
                    for(ACCL__Flatten_Account_Hierarchy__c rec : [Select ACCL__Account__c from ACCL__Flatten_Account_Hierarchy__c 
                                                    where (NOT ACCL__Account__r.ACCL__Account_Number__c LIKE 'US%') AND ACCL__Account__r.MDLZ_Ad_Break_Day__c != null AND
                                                    (ACCL__Account_Level_01__c = :promotionList[0].ACCL__Anchor_Account__c OR 
                                                    ACCL__Account_Level_02__c = :promotionList[0].ACCL__Anchor_Account__c OR
                                                    ACCL__Account_Level_03__c = :promotionList[0].ACCL__Anchor_Account__c OR
                                                    ACCL__Account_Level_04__c = :promotionList[0].ACCL__Anchor_Account__c OR
                                                    ACCL__Account_Level_05__c = :promotionList[0].ACCL__Anchor_Account__c)]){
                                                        promotionStoreRecords.add(new MDLZ_Promotion_Store__c(Promotion__c = promotionList[0].Id,
                                                                                                                Store__c = rec.ACCL__Account__c));
                                                    }
        
                } else if(promotionList[0].ACCL__Anchor_Account_Set__c != null) {
                    //Query to fetch all the account in a Customer set related to promotion
                    for(ACCL__Account_Set_Account__c csa : [Select Id, ACCL__Account_Set_Account__c from ACCL__Account_Set_Account__c where 
                                                ACCL__Account_Set__c = : promotionList[0].ACCL__Anchor_Account_Set__c AND ACCL__Account_Set_Account__r.MDLZ_Ad_Break_Day__c != null]){
                                                    promotionStoreRecords.add(new MDLZ_Promotion_Store__c(Promotion__c = promotionList[0].Id,
                                                                                                            Store__c = csa.ACCL__Account_Set_Account__c));
                                                }
                }
        
                //Inserting the promotion store records and logging the failure if any
                srList = Database.Insert(promotionStoreRecords,false);
                exc.saveResultErrors(srList,promotionStoreRecords,'MDLZ_PromotionStoreCreateBatchHandler().createPromoStoreRecord','MDLZ_Promotion_Store__c','Store__c');

            } catch (Exception e){
                exc.insertExceptions('MDLZ_PromotionStoreCreateBatchHandler()',e.getMessage(),e.getLineNumber(),e.getTypeName());
            }
        }
        
    }
}