src/objects/ACCL__Account_Set__c.object
<CustomObject>
    <description>Object for the creation of Customer Sets.</description>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds Description in Language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer set belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Customer Set</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Account_Set_Account__c.object
<CustomObject>
    <description>Junction object between Customer and Customer Set.</description>
    <fields>
        <fullName>ACCL__Account_Set_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Set Customers (Customer)</relationshipLabel>
        <relationshipName>Account_Set_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Account_Set__c</fullName>
        <description>Reference to Customer Set.</description>
        <label>Customer Set</label>
        <referenceTo>ACCL__Account_Set__c</referenceTo>
        <relationshipLabel>Customer Set Customers</relationshipLabel>
        <relationshipName>Account_Set_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Set Customer</label>
    <nameField>
        <displayFormat>ASA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Set Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Account_Task__c.object
<CustomObject>
    <description>Holds the details of the customer task (customer issue).</description>
    <fields>
        <fullName>ACCL__Account_Task_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the template.</description>
        <label>Customer Task Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Account_Task_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Account_Task_Template__c</referenceTo>
        <relationshipLabel>Customer Tasks</relationshipLabel>
        <relationshipName>Customer_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Account__c</fullName>
        <description>Reference to the customer.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Tasks</relationshipLabel>
        <relationshipName>Customer_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds the description of language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Due_Date__c</fullName>
        <description>The date the action should have been done.</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Priority__c</fullName>
        <description>Priority of the customer task.</description>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org to which the account task belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MDLZ_Customer_Sets__c</fullName>
        <label>Customer Sets</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MDLZ_Master_Record__c</fullName>
        <label>Master Record</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_Parent_RecordId__c</fullName>
        <label>Parent RecordId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Customer Task</label>
    <nameField>
        <displayFormat>CT-{00000}</displayFormat>
        <label>Customer Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Account_Task_Template__c.object
<CustomObject>
    <description>Holds the details of the customer task template,  to be used for customer tasks.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>The customer task template is active and can be used for customer task creation.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds the description of language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>The customer task template is available for the sales org specified.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Customer Task Template</label>
    <nameField>
        <label>Customer Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Account_Number__c</fullName>
        <description>Customer Number.</description>
        <label>Customer Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ACCL__Account_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to customer template.</description>
        <label>Customer Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Account_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Account_Template__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer belongs to.</description>
        <formula>Text(ACCL__Account_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MDLZ_Trigger_Switch__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mondelez Trigger Switch</description>
    <fields>
        <fullName>MDLZ_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>MDLZ Trigger Switch</label>
</CustomObject>

src/classes/MDLZ_AddCustomerSetToCustomerTaskTest.cls
/***************************************************************
Name: MDLZ_AddCustomerSetToCustomerTaskTest
======================================================
Purpose:
Tset class for MDLZ_AddCustomerSetToCustomerTask and MDLZ_CustomerTaskTrigger
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0         Namitha_Francis     Vaidehi       07/06/2021     Initial Development   
***************************************************************/
@isTest
private class MDLZ_AddCustomerSetToCustomerTaskTest {
    
    
    static testMethod void testClass(){
        
     Map<Id, ACCL__Account_Task__c> customerTaskMap = new Map<Id, ACCL__Account_Task__c>();
        Map<Id, ACCL__Account_Task__c> customerTaskMapOld = new Map<Id, ACCL__Account_Task__c>();
        //Customer Task Template
        ACCL__Account_Task_Template__c customerTaskTemp = new ACCL__Account_Task_Template__c();
        customerTaskTemp.Name = 'Customer Announcement Template';
        customerTaskTemp.ACCL__Description_Language_1__c ='Test data';
        customerTaskTemp.ACCL__Sales_Org__c ='US01';
        customerTaskTemp.ACCL__Active__c = true;
        Database.insert(customerTaskTemp,false);
      
        //Account Template
        ACCL__Account_Template__c acctemp = new ACCL__Account_Template__c();
        acctemp.Name ='Customer Template';
        acctemp.ACCL__Initial_Roles__c ='Customer';
        acctemp.ACCL__Sales_Org__c='US01';
        acctemp.ACCL__Active__c =true;
        acctemp.ACCL__Description_Language_1__c='Test Data';
        acctemp.RecordTypeId =Schema.SObjectType.ACCL__Account_Template__c.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
         Database.insert(acctemp,false);
     System.assertEquals('US01', acctemp.ACCL__Sales_Org__c);
     
        //Acount
        Account acct = new Account();
        acct.Name ='Demo Account';
        acct.ACCL__Account_Number__c='Demo Unique123';
        acct.Description ='Test Descr';
        acct.ACCL__Account_Template__c =acctemp.id;
        Database.insert(acct,false);
        System.assertNotEquals('US01', acct.ACCL__Sales_Org__c);
        
        Account acct1 = new Account();
        acct1.Name ='Demo Account';
        acct1.ACCL__Account_Number__c='Demo Unique123';
        acct1.Description ='Test Descr';
        acct1.ACCL__Account_Template__c =acctemp.id;
        Database.insert(acct1,false);
        System.assertNotEquals('US01', acct1.ACCL__Sales_Org__c);
     
        //Customer Set
        ACCL__Account_Set__c custSet = new ACCL__Account_Set__c();
        custSet.ACCL__Description_Language_1__c ='Mondelez Description';
        custSet.ACCL__Sales_Org__c ='US01';
       Database.insert(custSet,false);
        System.assertEquals('US01', custSet.ACCL__Sales_Org__c);
       
       //Customer set account
        ACCL__Account_Set_Account__c custSetaccount = new ACCL__Account_Set_Account__c();
        custSetaccount.ACCL__Account_Set_Account__c = acct1.Id;
        custSetaccount.ACCL__Account_Set__c =custSet.Id;
       Database.insert(custSetaccount,false);
       
       //Customer Task
        List<ACCL__Account_Task__c> custTaskList = new List<ACCL__Account_Task__c>(); 
        ACCL__Account_Task__c custTask = new ACCL__Account_Task__c(); 

        custTask.ACCL__Account_Task_Template__c=customerTaskTemp.Id;
        custTask.ACCL__Description_Language_1__c ='Test Demo';
        custTask.ACCL__Sales_Org__c=customerTaskTemp.ACCL__Sales_Org__c;
        custTask.ACCL__Due_Date__c=system.today()+5;
        custTask.ACCL__Account__c =acct.id;
        custTask.MDLZ_Master_Record__c = custTask.Id;
        custTask.ACCL__Priority__c ='A';
        custTask.MDLZ_Customer_Sets__c=custSet.Id;
        custTask.MDLZ_Parent_RecordId__c=custTask.Id;
        custTask.MDLZ_Unique_Name__c =custTask.MDLZ_Unique_Name__c; 
        Database.insert(custTask,false);
        
        custTaskList.add(custTask);
    //vf page
        PageReference pageRef = Page.MDLZ_AddCustomerSetToCustomerTask;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(custTask.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(custTask);
        MDLZ_AddCustomerSetToCustomerTask controller = new MDLZ_AddCustomerSetToCustomerTask(sc);
        controller.selectedPicklistValues = new List<String>{'Mondelez Description','Mondelez Description-2'};
            
        Test.startTest(); 
        List<SelectOption> options = controller.getCustomerSets();
        System.debug('options' + options);
        controller.save();
        controller.getmyID();
        controller.doFinish(); 
        controller.reset();
        Test.stopTest();
        
        Delete custTaskList; 
        
        //calling the methods
        MDLZ_CustomerTaskTriggerHandler triggerHandler = new MDLZ_CustomerTaskTriggerHandler();
    triggerHandler.beforeInsert(custTaskList);
        triggerHandler.afterDelete(customerTaskMap);
        triggerHandler.afterInsert(customerTaskMap);
        triggerHandler.AfterUndelete(customerTaskMap);
        triggerHandler.BeforeDelete(customerTaskMap);
        triggerHandler.afterUpdate(customerTaskMap,customerTaskMapOld);
        triggerHandler.beforeUpdate(customerTaskMap,customerTaskMapOld);
    
     /*List<ACCL__Account_Task__c> custTaskList11 = MDLZ_TestDataFactory.insertCustomerTask(1,false);
        custTaskList11[0].ACCL__Account__c = acct.Id;
        insert custTaskList11[0]; 
        
        delete custTaskList11;*/    
    }
    @isTest 
        static void testSaveErrorExceptions(){
        
        List<Database.SaveResult> srList = new List<Database.SaveResult>();
        MDLZ_ErrorExceptionHandler exc = new MDLZ_ErrorExceptionHandler();
        List<Database.UpsertResult> upsertcustomerSetList;
        List<ACCL__Account_Set__c> custSetList = MDLZ_TestDataFactory.insertCustomerSetList(5,true);   
        system.assertEquals(5, custSetList.size());
        List<ACCL__Account_Task__c> custTaskList = MDLZ_TestDataFactory.insertCustomerTask(5,true);   
        system.assertEquals(5, custTaskList.size());
            
        Test.startTest();
        
        srList = Database.update(custTaskList,false);
        upsertcustomerSetList = Database.upsert(custSetList,false);
        exc.saveResultErrors(srList,custTaskList,'MDLZ_AddCustomerSetToCustomerTaskTest().testSaveErrorExceptions','ACCL__Account_Task__c', 'Name');
        exc.upsertResultErrors(upsertcustomerSetList,custSetList,'MDLZ_AddCustomerSetToCustomerTaskTest().testSaveErrorExceptions','ACCL__Account_Set__c');
       
        Test.stopTest();            
    }
    @isTest 
        static void testInsertErrorExceptions(){
        test.startTest();
        List<ACCL__Account_Task__c> custTaskList = MDLZ_TestDataFactory.insertCustomerTask(2,true);          
         system.debug(custTaskList);
        update custTaskList;
        delete custTaskList;
        test.stopTest();
        
    }
    @isTest 
        static void testDelete(){
        ACCL__Account_Task__c custTaskParent = MDLZ_TestDataFactory.insertCustomerTask(); 
        ACCL__Account_Task__c custTaskChild = MDLZ_TestDataFactory.insertCustomerTask();
        custTaskChild.MDLZ_Parent_RecordId__c = custTaskParent.Id;
        update custTaskChild;
        test.startTest();
        delete custTaskParent ;
        test.stopTest();       
    }
    
    @isTest
    static void testDeleteSwitchOff(){
        ACCL__Account_Task__c custTaskParent = MDLZ_TestDataFactory.insertCustomerTask(); 
        ACCL__Account_Task__c custTaskChild = MDLZ_TestDataFactory.insertCustomerTask();
        custTaskChild.MDLZ_Parent_RecordId__c = custTaskParent.Id;
        update custTaskChild;
        MDLZ_Trigger_Switch__c s = new MDLZ_Trigger_Switch__c ();
        s.name = 'MDLZ_CustomerTaskTrigger';
        s.MDLZ_Active__c = False;
        insert s;
        test.startTest();
        delete custTaskParent ;
        test.stopTest();       
    }
}