src/objects/ACCL__Account_Extension__c.object
<CustomObject>
    <description>Object to record account roles and further product related attributes.</description>
    <fields>
        <fullName>ACCL__Account__c</fullName>
        <description>Reference to the customer to which the extension record is assigned.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Extensions</relationshipLabel>
        <relationshipName>Account_Extensions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Extension</label>
    <nameField>
        <displayFormat>AEX-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Account_Trade_Org_Hierarchy__c.object
<CustomObject>
    <description>Holds the details of the account hierarchy. From points to the higher trade org, to points to the lower trade org or store, The relation is time dependent.</description>
    <fields>
        <fullName>ACCL__Child_Account__c</fullName>
        <description>Reference to the business partner the relation is going to.</description>
        <label>Child Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Trade Org Hierarchies</relationshipLabel>
        <relationshipName>Account_Trade_Org_Child</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference from the business partner from which the relation is out going.</description>
        <label>Parent Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Trade Org Hierarchies (Parent Account)</relationshipLabel>
        <relationshipName>Account_Trade_Org_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Customer Trade Org Hierarchy</label>
    <nameField>
        <displayFormat>TOH-{0000}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Trade Org Hierarchies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountClearEffectiveParentInputView.cls
public class AccountClearEffectiveParentInputView{

    Date today = System.today();    
	private static String query = 'SELECT Id, (SELECT Id from ACCL__Account_Extensions__r) FROM Account WHERE Id NOT IN (SELECT ACCL__Child_Account__c FROM ACCL__Account_Trade_Org_Hierarchy__c WHERE ACCL__Valid_From__c <= :today AND ACCL__Valid_Thru__c >= :today AND ACCL__Parent_Account__c != null) AND ParentID != null';

    /**Returning query for database.queryLocator passing this to start method in AccountEffectiveParentClearBatch
     *  @name getObjectDataReader 
     *  @param None
     *  @return Database.QueryLocator
     */
    public Database.QueryLocator getObjectDataReader() {         
        return Database.getQueryLocator(query);
    }

}