src/objects/ACCL__Product_Assortment_Account__c.object
<CustomObject>
    <description>Holds the details of the relationship bettween a product assortment and a business partner. A product assortment can have no, one or several business partners assigned. In this table the assigned business partners are kept time dependent.</description>
    <label>Product Assortment Customer</label>
    <nameField>
        <displayFormat>PAA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Assortment Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Account_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to customer template.</description>
        <label>Customer Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Account_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Account_Template__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer belongs to.</description>
        <formula>Text(ACCL__Account_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MDLZ_ProdAssortment_ByCustBranchTest.cls
/***************************************************************
Name: MDLZ_ProdAssortment_ByCustBranchTest
======================================================
Purpose:
1. Test Class for MDLZ_ProdAssortment_ByCustBranch
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0      Priya Tubachi                11/02/2022     Initial Development    

***************************************************************/
@isTest
private class MDLZ_ProdAssortment_ByCustBranchTest {
    
    private MDLZ_ProdAssortment_ByCustBranchTest(){
        
    }
    static testMethod void custBranch(){
        
        MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.createCustomSettings();
        
        List<Account> acList = MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.insertAccount(2);
        sObject prodAssortTemplate = MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.insertProductAssortmentTemplate();
        sObject prodAssortment = MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.getProductAssortmentWithValidRange(
            System.today(), System.today().addYears(2), prodAssortTemplate);
        ACCL__Product_Assortment_Account__c prodAssortmentAccount =
            MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.insertProductAssortmentAccount(prodAssortment, acList[1]);
        ACCL__Product_Assortment_Account__c prodAssortmentAccountInValid = 
            MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.insertProductAssortmentAccountInValid(prodAssortment, acList[0]);
         System.assertEquals(acList[1].ACCL__Sales_Org__c, null);
      	MDLZ_ProdAssortment_ByCustBranch pr = new MDLZ_ProdAssortment_ByCustBranch();
        pr.updateProductAssortment( acList );
        Test.startTest();
        acList[0].ACCL__Account_Template__c =null;
        MDLZ_ProdAssortment_ByCustBranchBatch b = new MDLZ_ProdAssortment_ByCustBranchBatch(10);
        Database.executebatch(b);
        SchedulableContext sc = null;        
        MDLZ_ProdAssortment_ByCustBranchBatch bdsec=new MDLZ_ProdAssortment_ByCustBranchBatch(10);
        bdsec.execute(sc);
       
        Test.stopTest();
        
    }
}