src/objects/ACCL__Product_Assortment__c.object
<CustomObject>
    <description>Holds the details of a set of products which are often used together.</description>
    <fields>
        <fullName>ACCL__Product_Assortment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to product assortment template.</description>
        <label>Product Assortment Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Product_Assortment_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Product_Assortment_Template__c</referenceTo>
        <relationshipLabel>Product Assortments</relationshipLabel>
        <relationshipName>Product_Assortments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Product Assortment</label>
    <nameField>
        <label>Product Assortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Assortments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Product_Assortment_Account__c.object
<CustomObject>
    <description>Holds the details of the relationship bettween a product assortment and a business partner. A product assortment can have no, one or several business partners assigned. In this table the assigned business partners are kept time dependent.</description>
    <fields>
        <fullName>ACCL__Account__c</fullName>
        <description>Reference to customer.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Assortment Customers</relationshipLabel>
        <relationshipName>Product_Assortment_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ACCL__Product_Assortment__c</fullName>
        <description>Reference to product assortment.</description>
        <label>Product Assortment</label>
        <referenceTo>ACCL__Product_Assortment__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Product_Assortment_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Product Assortment Customer</label>
    <nameField>
        <displayFormat>PAA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Assortment Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Product_Assortment_Template__c.object
<CustomObject>
    <description>Template for product assortments. Controls the behaviour of the instances of this template, for example if a business partner must be specified (AccountMultiplicity). This table is sales organization dependent.</description>
    <label>Product Assortment Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Assortment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_DeleteProdAssortBranchListingBatch.cls
/***************************************************************
Name: MDLZ_DeleteProdAssortBranchListingBatch
======================================================
Purpose:
Deletes the Product Assortment Store records for Branch listing assortment.
Creating this as a separate method as the existing method processFinish hits the limit of deleting 10K records
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              
1.0      Priya Tubachi                08/03/2022     Initial Development    
***************************************************************/

global class MDLZ_DeleteProdAssortBranchListingBatch implements Database.Batchable<sObject>,Schedulable{
	
    //Defining the Scheduled Batch Size thru custom label
    private integer defaultChildBatchSize;
    public MDLZ_DeleteProdAssortBranchListingBatch(integer childBatchSize){
        defaultChildBatchSize = childBatchSize;
    }
    
    //query locator extracts invalid PAA records for PA template = listing
    global Database.QueryLocator start(Database.BatchableContext bCtx){
        
        String templateName = MDLZ_ConstantHelper.Branch_Listing;
        String query ='select id,ACCL__Account__c,ACCL__Product_Assortment__c, ACCL__Product_Assortment__r.name,ACCL__Valid_Thru__c from ACCL__Product_Assortment_Account__c'
            +' where ACCL__Valid_Thru__c <= today and ACCL__Product_Assortment__r.ACCL__Product_Assortment_Template__r.name=:templateName';
        
        return Database.getQueryLocator(query);
    }
    
    //execute method of batch class
   global void execute(Database.BatchableContext BC, List<sobject> scope)
    {
        //Calling the apex handler class
        new MDLZ_DeleteProdAssortBranchListing().deleteInvalidPAARecord(scope);
    }
    
    //schedulable execute method of batch class
    global void execute(SchedulableContext ctx) {
        Database.executeBatch(new MDLZ_DeleteProdAssortBranchListingBatch(200), defaultChildBatchSize); 
        
    }
    
    //finish method of the batch class
    global void finish(Database.BatchableContext BC)
    {
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob details = [SELECT Id, Status,ExtendedStatus,MethodName, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email 
                                FROM AsyncApexJob WHERE Id =:BC.getJobId()];
          
    }
}