src/objects/ACCL__Product__c.object
<CustomObject>
    <description>This object records the attributes of a product.</description>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the product belongs to.</description>
        <formula>TEXT(ACCL__Product_Template__r.ACCL__Sales_Org__c)</formula>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <label>Product</label>
	 <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Product_Assortment__c.object
<CustomObject>
    <description>Holds the details of a set of products which are often used together.</description>
    <fields>
        <fullName>ACCL__Product_Assortment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to product assortment template.</description>
        <label>Product Assortment Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Product_Assortment_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Product_Assortment_Template__c</referenceTo>
        <relationshipLabel>Product Assortments</relationshipLabel>
        <relationshipName>Product_Assortments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the product assortment belongs to.</description>
        <formula>TEXT(ACCL__Product_Assortment_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Version_Off_Platform_APL__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Stores off platform version number of Account product list.</description>
        <label>Version Off Platform APL</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACCL__Version__c</fullName>
        <description>Stores version number of Authorization list.</description>
        <label>Version</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Assortment</label>
    <nameField>
        <label>Product Assortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Assortments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Product_Assortment_Product__c.object
<CustomObject>
    <description>Holds the relationship between a product assortment and a product.A product-assortment-relation is time-dependent. Assortments can be used as set of products which are restricted to an industry or a sales channel.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active flag.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Product_Assortment__c</fullName>
        <description>Reference to the assortment the product relation belongs to.</description>
        <label>Product Assortment</label>
        <referenceTo>ACCL__Product_Assortment__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Product_Assortment_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Product__c</fullName>
        <description>Reference to a product assigned to the assortment.</description>
        <label>Product</label>
        <referenceTo>ACCL__Product__c</referenceTo>
        <relationshipLabel>Product Assortment Products</relationshipLabel>
        <relationshipName>Product_Assortment_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Product Assortment Product</label>
    <nameField>
        <displayFormat>PAP-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Assortment Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Product_Assortment_Template__c.object
<CustomObject>
    <description>Template for product assortments. Controls the behaviour of the instances of this template, for example if a business partner must be specified (AccountMultiplicity). This table is sales organization dependent.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Boolean to identify if the Product Assortment template is active.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Consider_For_APL_Generation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines the Product Assortment to be considered in Account Product list.</description>
        <label>Consider For APL Generation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the product assortment template belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Product Assortment Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Assortment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductAssortmentAlignment.cls
/**
* This class is used to schedule and trigger product assortments sync process with off platform
*/
public class ProductAssortmentAlignment implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable {
    private String query = 'SELECT Id, ACCL__Version__c, ACCL__Version_Off_Platform_APL__c, ' +
        				   'ACCL__Product_Assortment_Template__r.ACCL__Consider_For_APL_Generation__c ' +
        				   'FROM ACCL__Product_Assortment__c WHERE  ACCL__Sales_Org__c =:salesOrg';
    private static Integer DEFAULTBATCHSIZE = 1;
    private static final Type classType = ProductAssortmentAlignment.class;
    private Integer batchSize;
    private String txId = ACCL.TransactionHandler.generateGUID();
    private static final string PROCESS_NAME = 'ProductAssortmentAlignment';
    private String salesOrg { get; set; }
    private Boolean refreshAccountProductList { get; set; }
    private Boolean executeNightlyCalculation { get; set; }
    private Set<Id> productAssortmentsSyncedIds = new Set<Id>();

    // BRS_PARAMS
    private static final String  JOBNAME = 'Update';
    private static final Integer JOBTHREADS = 1;
    private static final String  BATCHCHAIN = 'Assortment';
    private static final String  BATCHCHAINTYPE = 'default';



    /**
    * Constructor.
    * @param salesOrg string value from Configuration record.
    * @param refreshAccountProductList Boolean value from Configuration, identify AccountProductList is either partial or full.
    * @param executeNightlyCalculation Boolean value from Configuration, identify nightly calculation executed after product assortment alignment
    */
    public ProductAssortmentAlignment(String salesOrg, Boolean refreshAccountProductList, Boolean executeNightlyCalculation) {
        this.salesOrg = salesOrg;
        this.refreshAccountProductList = refreshAccountProductList;
        this.executeNightlyCalculation = executeNightlyCalculation;
        String batchCheckQuery ='SELECT ACCL__Batch_Size__c FROM ACCL__Batch_Process_Configuration__c WHERE Name=:PROCESS_NAME';
        List<sObject> sobjList = Database.query(batchCheckQuery);
        if(!sobjList.isEmpty()) {
            batchSize = ((Decimal)sobjList[0].get('ACCL__Batch_Size__c')).intValue();
        } else {
            batchSize = DEFAULTBATCHSIZE;
        }
    }

    /** start method of Batch class for input query
    *  @name start
    *  @param Database.BatchableContext BC
    *  @return Database.QueryLocator
    */
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    /** execute method of Batch class
    *  @name execute
    *  @param Database.BatchableContext BC, List<sobject> scope
    *  @return void
    */
    public void execute(Database.BatchableContext BC, List<ACCL__Product_Assortment__c> scope) {
        ACCL.LogTrace logTraceHandle;
        try {
            logTraceHandle = ACCL.LoggerUtility.enterMethod(txId, classType, 'execute', ACCL.LogTrace.SOURCETYPE.Batch, new String[] {String.join(scope,';')});
            Boolean isConsideredForAPLGeneration = false;
            for (ACCL__Product_Assortment__c prdAssortment : scope) {
                isConsideredForAPLGeneration = prdAssortment.ACCL__Product_Assortment_Template__r.ACCL__Consider_For_APL_Generation__c;
                if (isConsideredForAPLGeneration && (prdAssortment.ACCL__Version__c <> prdAssortment.ACCL__Version_Off_Platform_APL__c)) {
                    List<ACCL__Product_Assortment_Product__c> lstProducts = [SELECT Id, ACCL__Product__c, ACCL__Valid_From__c,
                                                                                     ACCL__Valid_Thru__c FROM ACCL__Product_Assortment_Product__c
                                                                       				 WHERE ACCL__Product_Assortment__c =: prdAssortment.Id AND ACCL__Active__c = true];
                    ACCL.ProductAssortmentWebServiceCall.generateAccountProductList(txId, prdAssortment.Id, lstProducts, JOBNAME, JOBTHREADS, BATCHCHAIN, BATCHCHAINTYPE);
                    productAssortmentsSyncedIds.add(prdAssortment.Id);
                }
            }
        } catch(Exception ex) {
            ACCL.LoggerUtility.log(txId, LoggingLevel.ERROR, 'ACN_CLOUD_INTERNAL', 'Internal Server Error', new Map<String, Object> {'Exception' => ex});
        } finally {
            ACCL.LoggerUtility.leaveMethod(logTraceHandle, '');
        }
    }

    /** finish method of Batch class
    *  @name finish
    *  @param Database.BatchableContext BC
    *  @return void
    */
    public void finish(Database.BatchableContext BC) {
        if(this.executeNightlyCalculation) {
      		Database.executeBatch(new NightlyCalculationBatch(this.salesOrg, this.refreshAccountProductList), 1000);
        }
    }

    /** execute method of Batch class for scheduling batch class
    *  @name execute
    *  @param Database.BatchableContext BC
    *  @return void
    */
    public void execute(SchedulableContext context) {
        Database.executeBatch(this, batchSize);
    }
}