src/objects/ACCL__Order__c.object
<CustomObject>
    <description>Holds the header details of the order entry.</description>
    <fields>
        <fullName>ACCL__Delivery_Date__c</fullName>
        <description>By default next day.Delivery date calculation is
			customized very often.</description>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to capture customer for which Order is
			created</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Customer)</relationshipLabel>
        <relationshipName>Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Id__c</fullName>
        <description>Specifies the user readable number used for print-outs
			and customer communication</description>
        <label>Order Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Order Template for Order Entry</description>
        <label>Order Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Order_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Order_Template__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Workflow neutral description of the order Entry status.</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Send to SAP</fullName>
                    <label>Sent to SAP</label>
                </value>
                <value>
                    <fullName>Received By SAP</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Routed</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Order_Template__c.object
<CustomObject>
    <description>Template which controls the behaviour of a sales document.</description>
    <label>Order Template</label>
    <nameField>
        <label>Order Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Account_Number__c</fullName>
        <description>Customer Number.</description>
        <label>Customer Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MDLZ_CreateWrapperOrderBatch.cls
/***************************************************************
Name: MDLZ_CreateWrapperOrderBatch
======================================================
Purpose:
a. 
======================================================
History
-------
VERSION     AUTHOR         REVIWER      DATE             DETAIL              Description
1.0               Bharath Vikkurthi        		 06/05/2022     Initial Development    
***************************************************************/
//Changes as per JIRA MRELKXIW-2299

global with sharing class MDLZ_CreateWrapperOrderBatch  implements Database.Batchable< sObject >, Schedulable,Database.Stateful{
    
      //Defining the Scheduled Batch Size thru constructor
    public integer defaultChildBatchSize;
    public MDLZ_CreateWrapperOrderBatch(integer childBatchSize){
        defaultChildBatchSize = childBatchSize;
    }
    
     global   Database.QueryLocator start(Database.BatchableContext BC)    
    {
        String query = 'Select Id, ACCL__Order_Account__c, ACCL__Delivery_Date__c,ACCL__Order__c.ACCL__Phase__c, ACCL__Order_Template__c,ACCL__Order__c.ACCL__Order_Id__c,'+
		+'ACCL__Order_Account__r.ACCL__Account_Number__c'+
            +' from ACCL__Order__c where ACCL__Order_Template__r.Name in (\'Order\',\'NOS\',\'EDI\') and  '+
            +'ACCL__Phase__c NOT IN (\'REJECTED\',\'DELETED\',\'CANCELLED\') and createdDate >=yesterday';

        return Database.getQueryLocator(query);
        
    }
    
    global void execute(Database.BatchableContext BC, List<sobject> scope)
    {
        new MDLZ_CreateWrapperCAOOrder().createWrapper(scope);
    }
    
      global void execute(SchedulableContext ctx) {
        Database.executeBatch(this, defaultChildBatchSize);    
    } 
    
    global void finish(Database.BatchableContext BC)
    {
          // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob details = [SELECT Id, Status,ExtendedStatus, NumberOfErrors, JobItemsProcessed,TotalJobItems, 
                                CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        System.debug('Batch Process Details' +details);
    }
    

}