src/objects/ACCL__Product_Assortment__c.object
<CustomObject>
    <description>Holds the details of a set of products which are often used together.</description>
    <fields>
        <fullName>ACCL__Product_Assortment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to product assortment template.</description>
        <label>Product Assortment Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Product_Assortment_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Product_Assortment_Template__c</referenceTo>
        <relationshipLabel>Product Assortments</relationshipLabel>
        <relationshipName>Product_Assortments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Assortment</label>
    <nameField>
        <label>Product Assortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Assortments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Product_Assortment_Account__c.object
<CustomObject>
    <description>Holds the details of the relationship bettween a product assortment and a business partner. A product assortment can have no, one or several business partners assigned. In this table the assigned business partners are kept time dependent.</description>
    <fields>
        <fullName>ACCL__Account__c</fullName>
        <description>Reference to customer.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Assortment Customers</relationshipLabel>
        <relationshipName>Product_Assortment_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ACCL__Product_Assortment__c</fullName>
        <description>Reference to product assortment.</description>
        <label>Product Assortment</label>
        <referenceTo>ACCL__Product_Assortment__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Product_Assortment_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Assortment Customer</label>
    <nameField>
        <displayFormat>PAA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Assortment Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Product_Assortment_Template__c.object
<CustomObject>
    <description>Template for product assortments. Controls the behaviour of the instances of this template, for example if a business partner must be specified (AccountMultiplicity). This table is sales organization dependent.</description>
    <label>Product Assortment Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Assortment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_DeleteProdAssortBranchListing.cls
/***************************************************************
Name: MDLZ_DeleteProdAssortBranchListing
======================================================
Purpose:
Deletes the Product Assortment Store records for Branch listing assortment.
Creating this as a separate method as the existing method processFinish hits the limit of deleting 10K records
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              
1.0      Priya Tubachi                08/03/2022     Initial Development    
***************************************************************/
public with sharing class MDLZ_DeleteProdAssortBranchListing {
	//called from the batch class to delete invalid PAA records
    public void deleteInvalidPAARecord(List<ACCL__Product_Assortment_Account__c> getPAARecords) {
        try {
            
            List<ACCL__Product_Assortment_Store__c> listProdAssortStoreToDelete = new List<ACCL__Product_Assortment_Store__c>();
            MDLZ_ErrorExceptionHandler exc = new MDLZ_ErrorExceptionHandler();  
            //get the PAA list 
             Map<id,ACCL__Product_Assortment_Account__c> allPAAMap = new Map<id,ACCL__Product_Assortment_Account__c>(getPAARecords);
            
            //create a map of existing records wiht key = acc|branchname and values as list of acc id's
            Map<String, Id> prodAssorAccMap = new Map<String, Id>();
            
            for(ACCL__Product_Assortment_Account__c prdAssortAcc : allPAAMap.values()){
                prodAssorAccMap.put(prdAssortAcc.ACCL__Account__c+'|'+prdAssortAcc.ACCL__Product_Assortment__r.name,
                                    prdAssortAcc.ACCL__Account__c);
            }
            
            List<ACCL__Product_Assortment_Store__c> listProdAssortStore = 
                [select id,ACCL__Assortment__c, ACCL__Assortment__r.name,
                 ACCL__Store__c,ACCL__Assortment__r.ACCL__Product_Assortment_Template__r.name 
                 from ACCL__Product_Assortment_Store__c where 
                 ACCL__Store__c in :prodAssorAccMap.values() and 
                 ACCL__Assortment__r.ACCL__Product_Assortment_Template__r.name = :MDLZ_ConstantHelper.Branch_Listing];
            
            if(listProdAssortStore.size()>0){
                for(ACCL__Product_Assortment_Store__c assortmentStore:listProdAssortStore)
                {
                    String key = assortmentStore.ACCL__Store__c+'|'+assortmentStore.ACCL__Assortment__r.name;
                   
                    if(prodAssorAccMap.containsKey(key))
                    {
                        listProdAssortStoreToDelete.add(assortmentStore);
                     }
                }
            }else{
                system.debug('Prod Assort Store list empty');
            }
            
            if(!listProdAssortStoreToDelete.isEmpty()) {
                List<Database.DeleteResult> srList =database.Delete(listProdAssortStoreToDelete);
                MDLZ_ErrorExceptionHandler error = new MDLZ_ErrorExceptionHandler();
                error.deleteResultErrors(srList, listProdAssortStoreToDelete, 'MDLZ_DeleteProdAssortBranchListing()',
                                         'ACCL__Product_Assortment_Store__c', 'id');
            }
            
        } catch(Exception ex) {
            system.debug('An exception has occurred');
             MDLZ_ErrorExceptionHandler exc = new MDLZ_ErrorExceptionHandler();
            //not re throwing the exceptions but handling in a different method.
            exc.insertExceptions('Exception-MDLZ_DeleteProdAssortBranchListing()',ex.getStackTraceString(),
                                 ex.getLineNumber(),ex.getTypeName()); 
        }
        
    }
}