src/objects/ACCL__Product__c.object
<CustomObject>
    <description>This object records the attributes of a product.</description>
	<fields>
        <fullName>MDLZ_PPG__c</fullName>
        <description>Stores the planning PPG for product</description>
        <label>PPG</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_SubPPG__c</fullName>
        <description>Stores the sub PPG for product</description>
        <label>Sub PPG</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
	 <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Tactic__c.object
<CustomObject>
    <description>Relation from a Promotion and Tactic.</description>
    <fields>
        <fullName>ACCL__Included__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Defines if a tactic is included in a promotion</description>
        <label>Included</label>
        <type>Checkbox</type>
    </fields>
    <label>Tactic</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tactic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tactics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Tactic_Product__c.object
<CustomObject>
    <description>Junction Object between Tactic and Product</description>
    <fields>
        <fullName>ACCL__Included__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Product__c</fullName>
        <label>Product</label>
        <referenceTo>ACCL__Product__c</referenceTo>
        <relationshipLabel>Tactic Products</relationshipLabel>
        <relationshipName>Tactic_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Tactic__c</fullName>
        <label>Tactic</label>
        <referenceTo>ACCL__Tactic__c</referenceTo>
        <relationshipLabel>Tactic Products</relationshipLabel>
        <relationshipName>Tactic_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>MDLZ_Location__c</fullName>
        <description>Stores the location for Tactic product</description>
        <label>Location</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_PPG__c</fullName>
        <description>Stores the PPG for Tactic product</description>
        <label>PPG</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_Price__c</fullName>
        <description>Stores the price for Tactic product</description>
        <label>SRP</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MDLZ_SubPPG__c</fullName>
        <description>Stores the Sub PPG for Tactic product</description>
        <label>Sub PPG</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Tactic Product</label>
    <nameField>
        <displayFormat>TP-{00000000}</displayFormat>
        <label>Tactic Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tactic Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MDLZ_AddPPGTest.cls
/***************************************************************
Name: MDLZ_AddPPGTest
======================================================
Purpose:
Test class for MDLZ_AddPPG class
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0      Gaurav Gupta                 06/07/2022     Initial Development

***************************************************************/

@isTest
private class MDLZ_AddPPGTest {
    static testMethod void getTacticProductsTest(){
        List<ACCL__Tactic_Product__c> tacticProdList = new List<ACCL__Tactic_Product__c>();
        List<ACCL__Tactic_Product__c> tacticProd = new List<ACCL__Tactic_Product__c>();
        ACCL__Tactic__c tacticId = new ACCL__Tactic__c();
        test.startTest();
        tacticProd = MDLZ_TestDataFactory.insertTacticProducts(1,true);
        tacticId = [Select id From ACCL__Tactic__c Limit 1];
        tacticProdList=MDLZ_AddPPG.getTacticProducts(tacticId.id);
        test.stopTest();
        system.assertEquals(tacticProd.size(), 1);
    }
    
    static testMethod void getProductsTest(){
        List<ACCL__Product__c> productList = new List<ACCL__Product__c>();
        test.startTest();
        productList = MDLZ_TestDataFactory.createProductRecords(5);
        Map<string,List<String>> getProductsResult = MDLZ_AddPPG.getProducts();
        test.stopTest();
        system.assertEquals(getProductsResult.get('Big Bags').size(), 5);
    }
    
    static testMethod void updateTacticProdTest(){
        Map<String, String> updateResult = new Map<String, String>();
        List<ACCL__Tactic_Product__c> tacticProdList = new List<ACCL__Tactic_Product__c>();
        List<ACCL__Tactic_Product__c> data = new List<ACCL__Tactic_Product__c>();
        ACCL__Tactic__c tacticId = new ACCL__Tactic__c();
        test.startTest();
        tacticProdList = MDLZ_TestDataFactory.insertTacticProducts(1,true);
        tacticId = [Select id From ACCL__Tactic__c Limit 1];
        ACCL__Tactic_Product__c tacticProd = new ACCL__Tactic_Product__c();
        tacticProd.Id = tacticProdList[0].id;
        tacticProd.MDLZ_PPG__c = tacticProdList[0].MDLZ_PPG__c;
        tacticProd.MDLZ_SubPPG__c = tacticProdList[0].MDLZ_SubPPG__c;
        tacticProd.MDLZ_Price__c = tacticProdList[0].MDLZ_Price__c + 1;
        tacticProd.MDLZ_Location__c = 'new ' + tacticProdList[0].MDLZ_Location__c;
        data.add(tacticProd);
        updateResult = MDLZ_AddPPG.updateTacticProd(tacticProdList[0], data, tacticId.Id);
        test.stopTest();
        List<ACCL__Tactic_Product__c> tacticProdUpdated = [Select MDLZ_Location__c From ACCL__Tactic_Product__c Limit 1];
        System.assertEquals('new ' + tacticProdList[0].MDLZ_Location__c, tacticProdUpdated[0].MDLZ_Location__c);
        System.assertEquals(MDLZ_ConstantHelper.ResultMap_KeySuccess, updateResult.get(MDLZ_ConstantHelper.ResultMap_KeySuccess));
    }
    
    static testMethod void insertTacticProdTest(){
        String insertResult;
        List<ACCL__Tactic_Product__c> tacticProdToInsert = new List<ACCL__Tactic_Product__c>();
        List<ACCL__Product__c> productList = new List<ACCL__Product__c>();
        String jsonOfListOfTPRoducts;
        test.startTest();
        ACCL__Tactic__c tactic = MDLZ_TestDataFactory.insertTactic();
        productList = MDLZ_TestDataFactory.createProductRecords(1);
        ACCL__Tactic_Product__c tatcProd = new ACCL__Tactic_Product__c();
        tatcProd.MDLZ_PPG__c = productList[0].MDLZ_PPG__c;
        tatcProd.MDLZ_SubPPG__c = productList[0].MDLZ_SubPPG__c;
        tatcProd.MDLZ_Price__c = 5;
        tatcProd.MDLZ_Location__c='xff'; 
        tatcProd.ACCL__Tactic__c=tactic.id; 
        tatcProd.ACCL__Included__c=true;
        tatcProd.ACCL__Product__c =productList[0].id;
        tacticProdToInsert.add(tatcProd);
        jsonOfListOfTPRoducts = JSON.serialize(tacticProdToInsert);
        insertResult = MDLZ_AddPPG.insertTProds(jsonOfListOfTPRoducts);
        test.stopTest();
        List<ACCL__Tactic_Product__c> tacticProdInserted = [Select Id From ACCL__Tactic_Product__c];
		System.assertEquals(1, tacticProdInserted.size());
        System.assertEquals('Success : Products updated successfully', insertResult);
    }
    
    static testMethod void insertTacticProdTestBlankSubPPG(){
        String insertResult;
        List<ACCL__Tactic_Product__c> tacticProdToInsert = new List<ACCL__Tactic_Product__c>();
        List<ACCL__Product__c> productList = new List<ACCL__Product__c>();
        String jsonOfListOfTPRoducts;
        test.startTest();
        ACCL__Tactic__c tactic = MDLZ_TestDataFactory.insertTactic();
        productList = MDLZ_TestDataFactory.createProductRecords(1);
        ACCL__Tactic_Product__c tatcProd = new ACCL__Tactic_Product__c();
        tatcProd.MDLZ_PPG__c = productList[0].MDLZ_PPG__c;
        tatcProd.MDLZ_Price__c = 5;
        tatcProd.MDLZ_Location__c='xff'; 
        tatcProd.ACCL__Tactic__c=tactic.id; 
        tatcProd.ACCL__Included__c=true;
        tatcProd.ACCL__Product__c =productList[0].id;
        tacticProdToInsert.add(tatcProd);
        jsonOfListOfTPRoducts = JSON.serialize(tacticProdToInsert);
        insertResult = MDLZ_AddPPG.insertTProds(jsonOfListOfTPRoducts);
        test.stopTest();
        List<ACCL__Tactic_Product__c> tacticProdInserted = [Select Id From ACCL__Tactic_Product__c];
		System.assertEquals(1, tacticProdInserted.size());
        System.assertEquals('Success : Products updated successfully', insertResult);
    }
    
    static testMethod void deleteTacticProdTest(){
        Map<String, String> deleteResult = new Map<String, String>();
        List<ACCL__Tactic_Product__c> tacticProdList = new List<ACCL__Tactic_Product__c>();
        List<ACCL__Tactic_Product__c> tacticProd = new List<ACCL__Tactic_Product__c>();
        ACCL__Tactic__c tacticId = new ACCL__Tactic__c();
        test.startTest();
        tacticProd = MDLZ_TestDataFactory.insertTacticProducts(1,true);
        tacticId = [Select id From ACCL__Tactic__c Limit 1];
        deleteResult = MDLZ_AddPPG.deleteTacticProd(tacticProd[0], tacticId.Id);
        test.stopTest();
        List<ACCL__Tactic_Product__c> tacticProdRemaining = [Select Id From ACCL__Tactic_Product__c];
		System.assertEquals(0, tacticProdRemaining.size());
        System.assertEquals(MDLZ_ConstantHelper.ResultMap_KeySuccess, deleteResult.get(MDLZ_ConstantHelper.ResultMap_KeySuccess));
    }
    
}