src/objects/ACCL__Account_Set__c.object
<CustomObject>
    <description>Object for the creation of Customer Sets.</description>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds Description in Language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer set belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Customer Set</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Account_Set_Account__c.object
<CustomObject>
    <description>Junction object between Customer and Customer Set.</description>
    <fields>
        <fullName>ACCL__Account_Set_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Set Customers (Customer)</relationshipLabel>
        <relationshipName>Account_Set_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Account_Set__c</fullName>
        <description>Reference to Customer Set.</description>
        <label>Customer Set</label>
        <referenceTo>ACCL__Account_Set__c</referenceTo>
        <relationshipLabel>Customer Set Customers</relationshipLabel>
        <relationshipName>Account_Set_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Set Customer</label>
    <nameField>
        <displayFormat>ASA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Set Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Promotion__c.object
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Decides whether a promotion is available.</description>
        <inlineHelpText>Defines if the promotion is considered in the Trade Calendar and the Account Plan.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Anchor_Account_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer Set</description>
        <label>Anchor Customer Set</label>
        <referenceTo>ACCL__Account_Set__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Anchor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Customer</description>
        <label>Anchor Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_From__c</fullName>
        <description>Promotion date from</description>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_Thru__c</fullName>
        <description>Promotion date thru</description>
        <label>Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Phase of the promotion</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Preparation</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Modeling</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                    <default>true</default>
                    <label>Committed</label>
                </value>
                <value>
                    <fullName>ForApproval</fullName>
                    <label>For Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Promotion_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to promotion template.</description>
        <label>Promotion Template</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>ACCL__Promotion_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Promotion_Template__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <formula>TEXT (ACCL__Promotion_Template__r.ACCL__Sales_Org__c)</formula>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Slogan_Language_1__c</fullName>
        <description>Holds the slogan in language 1.</description>
        <label>Slogan Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Account_Number__c</fullName>
        <description>Customer Number.</description>
        <label>Customer Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MDLZ_Ad_Break_Day__c</fullName>
        <defaultValue>&quot;Sunday&quot;</defaultValue>
        <label>Ad-Break Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer belongs to.</description>
        <formula>Text(ACCL__Account_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MDLZ_Promotion_Export__c.object
<CustomObject>
    <description>This will be used for the purpose of exporting promotion data to TRAX</description>
    <fields>
        <fullName>MDLZ_Activity_Ad_Break_Date__c</fullName>
        <description>Batch job will populate this field based on Ad break Day field on Account.</description>
        <label>Activity Ad Break Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MDLZ_Activity_ID__c</fullName>
        <description>To store Promotion Salesforce record Id</description>
        <label>Activity ID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MDLZ_Activity_Task_Description__c</fullName>
        <description>To store unique values of PPG/Sub PPG</description>
        <label>Activity Task Description</label>
        <type>TextArea</type>
    </fields>
    <label>Promotion Export</label>
    <nameField>
        <label>Promotion Export Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Exports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDLZ_Promotion_Store__c.object
<CustomObject>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>ACCL__Promotion__c</referenceTo>
        <relationshipLabel>Promotion Stores</relationshipLabel>
        <relationshipName>MDLZ_Promotion_Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotion Stores</relationshipLabel>
        <relationshipName>MDLZ_Promotion_Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion Store</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>MDLZ_Promotion_Store Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_PromotionExportDeleteBatchTest.cls
/***************************************************************
Name: MDLZ_PromotionExportDeleteBatchTest
======================================================
Purpose:
Test class for MDLZ_PromotionExportDeleteBatch, MDLZ_PromotionStoreDeleteBatch, MDLZ_PromotionStoreCreateBatch and
MDLZ_PromotionStoreCreateBatchHandler class
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0      Gaurav Gupta                 09/22/2022     Initial Development

***************************************************************/
@isTest
private class MDLZ_PromotionExportDeleteBatchTest {
    
    @testSetup static void dataCreation(){
       //test setup, creating promotionTemplate
       List<ACCL__Promotion_Template__c> promotionTemplateList = new List<ACCL__Promotion_Template__c>();
        
       ACCL__Promotion_Template__c promoFandDScriptedTemplate= new ACCL__Promotion_Template__c(Name='F&D Scripted', ACCL__Promotion_Type__c='SellablePromotion',
                                                                                   ACCL__Sales_Org__c='US01',ACCL__Description_Language_1__c='F&D Scripted',
                                                                                   ACCL__Product_Definition_Level__c='Tactic' ,ACCL__UI_Type__c='StandardUI');
        promotionTemplateList.add(promoFandDScriptedTemplate);
        
        if(promotionTemplateList.size() > 0){
            Database.Insert(promotionTemplateList,false);
        }
        system.assertEquals(1,promotionTemplateList.size());
        
    }
    
    //test method for testing the batch for promotion with customer set relation
    @isTest static void testDeletePromoExportBatchForCustomerSet(){
        List<ACCL__Promotion_Template__c> promotionTemplateList = [Select Id from ACCL__Promotion_Template__c];
        // accountList for Customer Set Customer
        List<Account> accountList = MDLZ_TestDataFactory.insertAccount(1,true);
        accountList[0].MDLZ_Ad_Break_Day__c = 'Wednesday';
        
        Database.Update(accountList,false);
                
        // Customer Set 
        ACCL__Account_Set__c customerSet = new ACCL__Account_Set__c(ACCL__Description_Language_1__c ='Mondelez Description', ACCL__Sales_Org__c='US01');
        Insert customerSet;
        
        // Customer Set Customers
        ACCL__Account_Set_Account__c customerSetCust = new ACCL__Account_Set_Account__c();
        customerSetCust.ACCL__Account_Set_Account__c = accountList[0].id;
        customerSetCust.ACCL__Account_Set__c = customerSet.Id;
        Insert customerSetCust;
        
        //Creating promotion test record
        ACCL__Promotion__c promotion1 = new ACCL__Promotion__c();
        promotion1.ACCL__Promotion_Template__c = promotionTemplateList[0].Id;
        promotion1.ACCL__Date_From__c= Date.Today();
        promotion1.ACCL__Date_Thru__c= Date.Today().addDays(60);
        promotion1.ACCL__Anchor_Account_Set__c = customerSet.Id;
        promotion1.ACCL__Slogan_Language_1__c='Test Promotion 1';
        promotion1.ACCL__Active__c=True;
        promotion1.ACCL__Phase__c='Committed';

        Database.Insert(promotion1,false);
        
        //Creating promotion store list record
        List<MDLZ_Promotion_Store__c> promoStoreList = new List<MDLZ_Promotion_Store__c>{new MDLZ_Promotion_Store__c(Promotion__c = promotion1.Id,
                                                                                                            Store__c = accountList[0].Id)};
        Database.Insert(promoStoreList,false);
        
        //Creating promotion export list records
        List<MDLZ_Promotion_Export__c> promoExportList = new List<MDLZ_Promotion_Export__c>();
        
        for(Integer i=0 ; i<5 ; i++){
            MDLZ_Promotion_Export__c promoExp = new MDLZ_Promotion_Export__c();
            promoExp.MDLZ_Activity_ID__c = 'TestPromotion' + i;
            promoExp.MDLZ_Activity_Task_Description__c = 'Test Template'+i;
            promoExp.MDLZ_Activity_Ad_Break_Date__c = Date.Today().addDays(3);
            promoExportList.add(promoExp);
        }
        
        if(promoExportList.size() > 0){
            Database.Insert(promoExportList,false);
        }
        
        Test.startTest();
        SchedulableContext sc = null;
        MDLZ_PromotionExportDeleteBatch obj = new MDLZ_PromotionExportDeleteBatch();
        obj.execute(sc);
        Test.stopTest();
    }
    
    //test method for testing the batch for promotion with anchor account relation
    @isTest static void testDeletePromoExportBatchForAnchorAccount(){
        List<ACCL__Promotion_Template__c> promotionTemplateList = [Select Id from ACCL__Promotion_Template__c];
        
        // accountList for Anchor Account
        List<Account> accountList = MDLZ_TestDataFactory.insertAccount(2,true);
        accountList[0].MDLZ_Ad_Break_Day__c = 'Wednesday';
        accountList[0].ACCL__Account_Number__c='24Demo Unique567'+Integer.valueOf(Math.random() * 10);
        
        //Flatten Account Hierarchy record for testing anchor account query
        ACCL__Flatten_Account_Hierarchy__c accountHierarchy = new ACCL__Flatten_Account_Hierarchy__c();
        accountHierarchy.ACCL__Account_Level_01__c = accountList[1].Id;
        accountHierarchy.ACCL__Account__c = accountList[0].Id;
        Database.insert(accountHierarchy, false);
        
        Database.Update(accountList,false);
        
        //Creating promotion record
        ACCL__Promotion__c promotion1 = new ACCL__Promotion__c();
        promotion1.ACCL__Promotion_Template__c = promotionTemplateList[0].Id;
        promotion1.ACCL__Date_From__c= Date.Today();
        promotion1.ACCL__Date_Thru__c= Date.Today().addDays(60);
        promotion1.ACCL__Anchor_Account__c = accountList[1].Id;
        promotion1.ACCL__Slogan_Language_1__c='Test Promotion 1';
        promotion1.ACCL__Active__c=True;
        promotion1.ACCL__Phase__c='Committed';
        
        Database.Insert(promotion1,false);
        
        Test.startTest();
        SchedulableContext sc = null;
        MDLZ_PromotionExportDeleteBatch obj = new MDLZ_PromotionExportDeleteBatch();
        obj.execute(sc);
        Test.stopTest();
    }

}