src/objects/ACCL__Tactic_Template__c.object
<CustomObject>
    <description>Template which controls the behaviour of a tactic</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates wether a tactic template is active or not.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Default_Lift_Type__c</fullName>
        <label>Default Lift Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ACCL__Possible_Lift_Types__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Percentage</fullName>
                    <default>true</default>
                    <label>Percentage</label>
                </value>
                <value>
                    <fullName>Absolute</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Possible_Lift_Types__c</fullName>
        <label>Possible Lift Types</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ACCL__Tactic_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Percentage</fullName>
                    <default>true</default>
                    <label>Percentage</label>
                </value>
                <value>
                    <fullName>Percentage/Absolute</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Tactic_Type__c</fullName>
        <description>Specifies the type of a tactic</description>
        <inlineHelpText>Specifies the type of a tactic</inlineHelpText>
        <label>Tactic Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                    <default>true</default>
                    <label>Retail</label>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>DisplayPerAbs</fullName>
                </value>
                <value>
                    <fullName>PriceReduction</fullName>
                </value>
                <value>
                    <fullName>PriceReductionPerAbs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tactic Template</label>
    <nameField>
        <label>Tactic Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tactic Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddOnTacticTemplateTestFactory.cls
@isTest
public class AddOnTacticTemplateTestFactory {
    public AddOnTacticTemplateTestFactory() {
    }
    
    public static ACCL__Tactic_Template__c defaultTacticTemplate;
    public static String theSalesOrg;
    
    public static ACCL__Tactic_Template__c getDefaultTacticTemplate() {
        if( defaultTacticTemplate == null ){
          defaultTacticTemplate = insertDefaultTacticTemplate( );
        }
        return defaultTacticTemplate;
    }
    
    public static ACCL__Tactic_Template__c insertDefaultTacticTemplate() {
        ACCL__Tactic_Template__c tctMeta = buildDefaultTacticTemplate();
        insert tctMeta;
        return tctMeta;
    }
    
    public static ACCL__Tactic_Template__c buildDefaultTacticTemplate() {
        return buildTacticTemplate(true, 'Display');
    }
    
    public static ACCL__Tactic_Template__c buildTacticTemplate(Boolean active, String tacticType) {
        ACCL__Tactic_Template__c tctMeta = new ACCL__Tactic_Template__c();
        tctMeta.ACCL__Active__c = active;
        tctMeta.ACCL__Tactic_Type__c = tacticType;
        tctMeta.ACCL__Default_Lift_Type__c = 'Percentage';
        tctMeta.ACCL__Possible_Lift_Types__c = 'Percentage';
        Return tctMeta;
    }
    
    //Test Methods With No Assert - This method creates test factory data, Assert is not needed - False Positive
    public static ACCL__Tactic_Template__c buildAndInsertTacticTemplate() {
        ACCL__Tactic_Template__c tctMeta = buildDefaultTacticTemplate();
        insert tctMeta;
        return tctMeta;
    }
    
    public static ACCL__Tactic_Template__c buildTacticTemplateWithSalesOrg(Boolean active, String tacticType) {
        ACCL__Tactic_Template__c tctMeta = new ACCL__Tactic_Template__c();
        tctMeta.ACCL__Active__c = active;
        tctMeta.ACCL__Tactic_Type__c = tacticType;
        tctMeta.ACCL__Default_Lift_Type__c = 'Percentage';
        tctMeta.ACCL__Possible_Lift_Types__c = 'Percentage';
        tctMeta.ACCL__Sales_Org__c = AddOnUserTestFactory.getSalesOrg()[0];
        Return tctMeta;
    }
    
    public static ACCL__Tactic_Template__c insertDefaultTacticTemplateWithSalesOrg(String salesOrg) {
        ACCL__Tactic_Template__c tctMeta = buildTacticTemplateWithSalesOrg(true, 'Display');
        tctMeta.ACCL__Sales_Org__c = salesOrg;
        insert tctMeta;
        return tctMeta;
    }
    
    public static ACCL__Tactic_Template__c getDefaultTacticTemplateWithSalesOrg(String salesOrg) {
        if( defaultTacticTemplate == null || salesOrg != theSalesOrg){
          defaultTacticTemplate = insertDefaultTacticTemplateWithSalesOrg(salesOrg); 
            theSalesOrg = salesOrg;
        }
        return defaultTacticTemplate;
    }


    public static ACCL__Tactic_Template__c insertDefaultTacticTemplateWithSalesOrg() {
        ACCL__Tactic_Template__c tctMeta = buildTacticTemplateWithSalesOrg(true, 'Display');
        insert tctMeta;
        return tctMeta;
    }

    public static ACCL__Tactic_Template__c getDefaultTacticTemplateWithSalesOrg() {
        return getDefaultTacticTemplateWithSalesOrg(AddOnUserTestFactory.getSalesOrg()[0]);
        }
    
}