src/objects/ACCL__Order__c.object
<CustomObject>
    <description>Holds the header details of the order entry.</description>
    <fields>
        <fullName>ACCL__Delivery_Date__c</fullName>
        <description>By default next day.Delivery date calculation is
			customized very often.</description>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to capture customer for which Order is
			created</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Customer)</relationshipLabel>
        <relationshipName>Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Order Template for Order Entry</description>
        <label>Order Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Order_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Order_Template__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Workflow neutral description of the order Entry status.</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Send to SAP</fullName>
                    <label>Sent to SAP</label>
                </value>
                <value>
                    <fullName>Received By SAP</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Routed</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MDLZ_Total_Case_Quantity__c</fullName>
        <description>Sum of case quantity of all products in the order item</description>
        <label>Total Case Quantity</label>
        <summarizedField>ACCL__Order_Item__c.ACCL__Quantity__c</summarizedField>
        <summaryForeignKey>ACCL__Order_Item__c.ACCL__Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Order_Template__c.object
<CustomObject>
    <description>Template which controls the behaviour of a sales document.</description>
    <label>Order Template</label>
    <nameField>
        <label>Order Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_OrderConsolidation.cls
/***************************************************************
Name: MDLZ_OrderConsolidation
======================================================
Purpose:
a. batch2 to update CAO orders to Routed or cancelled refer 
conditions in confluence matrix based on customer and delivery date
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              
1.0      Priya Tubachi            	 18/09/2021     Initial Development   
1.1      Vaidehi Heda                28/03/2022     Maqde the changes as per Novasaas Report
1.2      Priya Tubachi               10/05/2022     Optimizing class for AMS issues
1.3      Vaidehi Heda                08/03/2022     Updated condition for Locked and Cancelled Phase orders 
1.4      Samiksha Reddy              09/12/2022     Removed condition for Locked
***************************************************************/
public with sharing class MDLZ_OrderConsolidation {
    
    public void updateCAOOrdersNew(List<ACCL__Order__c> orderList){ 
        
        List<ACCL__Order__c> updateDBList = new List<ACCL__Order__c>();
        Set<Id> accountId = new Set<Id>();
        Map<String,ACCL__Order__c> caoOrderMap = new Map<String,ACCL__Order__c>();
        Map<String,String> ediNOSMap = new Map<String,string>();
        MDLZ_ErrorExceptionHandler exc = new MDLZ_ErrorExceptionHandler();
        
        try{ 
        // get the unique accounts from the orderList
        for(ACCL__Order__c order: orderList){
            accountId.add(order.ACCL__Order_Account__c);
            caoOrderMap.put(order.ACCL__Order_Account__c+'|'+order.ACCL__Delivery_Date__c, order);
        }
        
        //for the account list retrieve NOS/EDI orders for the same delivery date
        for(ACCL__Order__c ord :[SELECT Id, ACCL__Delivery_Date__c,ACCL__Order_Account__c, 
                                 ACCL__Order_Template__r.Name,ACCL__Phase__C,MDLZ_Total_Case_Quantity__c 
                                 FROM ACCL__Order__c WHERE ACCL__Delivery_Date__c >=today and ACCL__Delivery_Date__c <= tomorrow and
                                 ACCL__Order_Template__r.Name in ('NOS','EDI','Order') and ACCL__Phase__c in ('Routed','Cancelled','Received By SAP') and
                                 ACCL__Order_Account__c in: accountId ]){
                                     
                                     string uniqueKey = ord.ACCL__Order_Account__c+'|'+ord.ACCL__Delivery_Date__c;
                                     String value = ord.ACCL__Phase__c;
                                     
                                     if(ediNOSMap.containsKey(uniqueKey)){
                                     	value = value+'|'+ediNOSMap.get(uniqueKey);                                         
                                     }
                                     
                                     ediNOSMap.put(uniqueKey,value);    
                                 }
        
        if(caoOrderMap.size() > 0){
            ACCL__order__c ord = new ACCL__order__c();
            for(String caoKey:caoOrderMap.keyset()){
                ord = caoOrderMap.get(caoKey);
                if(ediNOSMap.containsKey(caoKey) && ((ediNOSMap.get(caoKey).indexOf(MDLZ_ConstantHelper.PhaseRouted) != -1))){
                    ord.ACCL__Phase__c = MDLZ_ConstantHelper.PhaseRouted;
                }else if(ediNOSMap.containsKey(caoKey) && ((ediNOSMap.get(caoKey).indexOf(MDLZ_ConstantHelper.PhaseCancelled) != -1)
                        && (ediNOSMap.get(caoKey).indexOf(MDLZ_ConstantHelper.ReceivedBySAP) == -1))){
                    ord.ACCL__Phase__c = MDLZ_ConstantHelper.PhaseCancelled;
                }
                /*else{
                    ord.ACCL__Phase__c = MDLZ_ConstantHelper.PhaseRouted;
                }*/
                updateDBList.add(ord);
            }
            
        }
        
        system.debug('updating data into db of size '+updateDBList.size());
        if(updateDBList.size() > 0){                
            List<Database.SaveResult> srList =  database.update(updateDBList,false);
            if(srList.size()>0){
                exc.saveResultErrors(srList,updateDBList,'MDLZ_OrderConsolidation()','ACCL__order__c','id');
            }
            
        }else{
            system.debug('No records to be updated');
        } 
       }catch(exception e){
            //not re throwing the exceptions but handling in a different method.
            exc.insertExceptions('MDLZ_OrderConsolidation()',e.getStackTraceString(),e.getLineNumber(),e.getTypeName()); 
        } 
        
    }
    
}