src/objects/ACCL__Account_Set__c.object
<CustomObject>
    <description>Object for the creation of Customer Sets.</description>
    <fields>
        <fullName>ACCL__Description__c</fullName>
        <description>Description based on the user specific language.</description>
        <formula>CASE($User.ACCL__Language_Postfix__c,
&quot;Language1&quot;, ACCL__Description_Language_1__c,
&quot;Language2&quot;, BLANKVALUE(ACCL__Description_Language_2__c,ACCL__Description_Language_1__c),
&quot;Language3&quot;, BLANKVALUE(ACCL__Description_Language_3__c,ACCL__Description_Language_1__c),
&quot;Language4&quot;, BLANKVALUE(ACCL__Description_Language_4__c,ACCL__Description_Language_1__c),
ACCL__Description_Language_1__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <label>Customer Set</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Promotion__c.object
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Decides whether a promotion is available.</description>
        <inlineHelpText>Defines if the promotion is considered in the Trade Calendar and the Account Plan.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Anchor_Account_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer Set</description>
        <label>Anchor Customer Set</label>
        <referenceTo>ACCL__Account_Set__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Anchor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Customer</description>
        <label>Anchor Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_From__c</fullName>
        <description>Promotion date from</description>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_Thru__c</fullName>
        <description>Promotion date thru</description>
        <label>Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Phase of the promotion</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Preparation</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Modeling</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                    <default>true</default>
                    <label>Committed</label>
                </value>
                <value>
                    <fullName>ForApproval</fullName>
                    <label>For Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Promotion_Template_Description__c</fullName>
        <formula>ACCL__Promotion_Template__r.ACCL__Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Promotion Template Description</label>
        <type>Text</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MDLZ_Ad_Break_Day__c</fullName>
        <defaultValue>&quot;Sunday&quot;</defaultValue>
        <label>Ad-Break Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MDLZ_Promotion_Export_AdBreak__mdt.object
<CustomObject>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <label>Batch Size</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Friday__c</fullName>
        <label>Friday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monday__c</fullName>
        <label>Monday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Saturday__c</fullName>
        <label>Saturday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sunday__c</fullName>
        <label>Sunday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Thursday__c</fullName>
        <label>Thursday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tuesday__c</fullName>
        <label>Tuesday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wednesday__c</fullName>
        <label>Wednesday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week_End_Sat__c</fullName>
        <label>Week End Sat</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week_Start_Sun__c</fullName>
        <label>Week Start Sun</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MDLZ Promotion Export AdBreak</label>
    <pluralLabel>MDLZ Promotion Export Adbreaks</pluralLabel>
</CustomObject>

src/classes/MDLZ_PromotionStoreCreateBatch.cls
/***************************************************************
Name: MDLZ_PromotionStoreCreateBatch
======================================================
Purpose: this batch process will create the records for junction Object Promotion Store and will call
the promotion export creation batch from the finish method.

======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE                DETAIL              Description
1.0      Gaurav Gupta                 09/19/2022     Initial Development    

***************************************************************/

global class MDLZ_PromotionStoreCreateBatch implements Database.Batchable<sObject>{

    //Creating custom exception
    public class applicationException extends Exception {}

    String promotionStage = MDLZ_ConstantHelper.Promotion_Stage_Committed;
    public static MDLZ_Promotion_Export_AdBreak__mdt adbreakMetadata = getMetadataRecord();
    
    global Database.QueryLocator start(Database.BatchableContext btx){
        
        Date weekStartDate = Date.Today().addDays(Integer.valueOf(adbreakMetadata.Week_Start_Sun__c));
        Date weekEndDate = Date.Today().addDays(Integer.valueOf(adbreakMetadata.Week_End_Sat__c));
        String query = 'Select Id ,name,ACCL__Anchor_Account__c,ACCL__Anchor_Account_Set__c,'+
                        +'ACCL__Date_From__c,ACCL__Date_Thru__c,ACCL__Phase__c,ACCL__Active__c, '+
                        +'ACCL__Anchor_Account__r.MDLZ_Ad_Break_Day__c,ACCL__Anchor_Account__r.Name, '+
                        +'ACCL__Anchor_Account_Set__r.Name,ACCL__Promotion_Template_Description__c, '+
                        +'ACCL__Anchor_Account_Set__r.ACCL__Description__c from ACCL__Promotion__c'+
                        +' where ACCL__Active__c = TRUE AND ACCL__Date_From__c <= :weekEndDate AND ACCL__Date_Thru__c >= :weekStartDate AND ACCL__Phase__c = :promotionStage';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sobject> scope){
        //Calling the handler class to create the relevant records for Promotion store 
        MDLZ_PromotionStoreCreateBatchHandler.createPromoStoreRecord(scope);
    }
    
    global void finish(Database.BatchableContext BC){
        //Calling the MDLZ_PromotionExportBatch to create the promotion Export Records
        if(Integer.valueOf(Label.MDLZ_PromotionStoreCreateBatch) > 1){
            //throwing exception for batch size greater than 1
            throw new applicationException(MDLZ_ConstantHelper.promoExportBatchSizeError);
        }
        else {
            Integer PromotionExportBatchSize = Integer.valueOf(Label.MDLZ_PromotionExportBatch);
            MDLZ_PromotionExportBatch createPromotionExportBatch = new MDLZ_PromotionExportBatch();
            database.executeBatch(createPromotionExportBatch, PromotionExportBatchSize);
        }
    }
    
    
    public static MDLZ_Promotion_Export_AdBreak__mdt getMetadataRecord(){
        Datetime dt = DateTime.newInstance(Date.today(), Time.newInstance(0, 0, 0, 0));
        String dayOfWeek=dt.format('EEEE');
        System.debug('###### Day : ' + dayOfWeek);
        
        MDLZ_Promotion_Export_AdBreak__mdt metadataRec = [Select Id , Label, Week_Start_Sun__c,Week_End_Sat__c,
                                                          Monday__c,Tuesday__c,Wednesday__c,Thursday__c,Friday__c,
                                                          Saturday__c,Sunday__c,Batch_Size__c
                                                          from MDLZ_Promotion_Export_AdBreak__mdt 
                                                          where Label = :dayOfWeek limit 1];
        
        return metadataRec;
        
    }
    
}