src/objects/ACCL__Order__c.object
<CustomObject>
    <description>Holds the header details of the order entry.</description>
	<fields>
        <fullName>MDLZ_isOrderAccepted__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Showing if an order was accepted (true) or rejected by SAP (false).</description>
        <label>Is Order Accepted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Workflow neutral description of the order Entry status.</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Send to SAP</fullName>
                    <label>Sent to SAP</label>
                </value>
                <value>
                    <fullName>Received By SAP</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Routed</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Order_Item__c.object
<CustomObject>
    <description>Holds the details of the order item object.</description>
    <fields>
        <fullName>ACCL__Order__c</fullName>
        <description>ID of the order where Order Item is associated with</description>
        <label>Order</label>
        <referenceTo>ACCL__Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{0000}</displayFormat>
        <label>Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MDLZ_Orders_To_Flip__c.object
<CustomObject>
    <description>Addressing 2154 issue will be used in a batch to flip the order items</description>
	<fields>
        <fullName>MDLZ_Is_Order_Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This will be true when MDLZ_Is_Order_Accepted on order is true.</description>
        <label>Is Order Accepted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>OrderId</label>
        <referenceTo>ACCL__Order__c</referenceTo>
        <relationshipLabel>Orders To Flip</relationshipLabel>
        <relationshipName>Orders_To_Flip</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Orders To Flip</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Orders To Flip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders To Flip</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_OrderFlipBatchTest.cls
/***************************************************************
Name: MDLZ_OrderFlipBatchTest
======================================================
Purpose:
Test class for MDLZ_OrderFlipBatch class 
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0      Vaidehi Heda              20/04/2022     Initial Development 
1.1      Vaidehi Heda              10/05/2022     Added other method to cover else if condition

***************************************************************/
@isTest
private class MDLZ_OrderFlipBatchTest {
    static testMethod void createLineItem(){
        List<ACCL__Order_Item__c> ordItemList ;
        List<MDLZ_Orders_To_Flip__c> flipList ;
        test.startTest();
        system.runAs(MDLZ_TestDataFactory.getUser(MDLZ_ConstantHelper.UserPermOPSADM)){
            integer defaultChildBatchSize = integer.valueOf(Label.MDLZ_OrderFlipBatch);
            MDLZ_OrderFlipBatch batch = new MDLZ_OrderFlipBatch(defaultChildBatchSize);             
            ordItemList = MDLZ_TestDataFactory.insertOrderLineItem(1, true);
            MDLZ_Orders_To_Flip__c flip = new MDLZ_Orders_To_Flip__c(OrderID__c=ordItemList[0].ACCL__Order__c, MDLZ_Is_Order_Accepted__c = true);
            insert flip;
            SchedulableContext ctx = null;
            batch.execute(ctx);
            //Database.executeBatch(new MDLZ_OrderFlipBatch(defaultChildBatchSize), defaultChildBatchSize);
            delete ordItemList;
            batch.execute(ctx);
            undelete ordItemList;
            test.stopTest();           
        }
        system.assertEquals(ordItemList.size(), 1)  ;
    }
    
    //covering other else if condition
    static testMethod void createLineItem2(){
        List<ACCL__Order__c>ordList;
        List<ACCL__Order_Item__c> ordItemList ;
        test.startTest();
        system.runAs(MDLZ_TestDataFactory.getUser(MDLZ_ConstantHelper.UserPermOPSADM)){
            integer defaultChildBatchSize = integer.valueOf(Label.MDLZ_OrderFlipBatch);
            MDLZ_OrderFlipBatch batch = new MDLZ_OrderFlipBatch(defaultChildBatchSize);
            ordList =MDLZ_TestDataFactory.insertOrder(1, False);
            ordList[0].MDLZ_isOrderAccepted__c = false;
            ordList[0].ACCL__Phase__c= MDLZ_ConstantHelper.PhaseRejected;
            insert ordList; 
            ordList[0].ACCL__Phase__c= MDLZ_ConstantHelper.PhaseDeleted;
            update ordList;
            ordItemList = MDLZ_TestDataFactory.insertOrderLineItem(1, false);
            ordItemList[0].ACCL__Order__c = ordList[0].id;
            insert ordItemList;
            SchedulableContext ctx = null;
            batch.execute(ctx);
        }
        test.stopTest();  
    }
    
    //covering wrapper order condition
    static testMethod void createWrapperOrder(){
        test.startTest();
        system.runAs(MDLZ_TestDataFactory.getUser(MDLZ_ConstantHelper.UserPermOPSADM)){
            integer defaultChildBatchSize = integer.valueOf(Label.MDLZ_OrderFlipBatch);
            MDLZ_OrderFlipBatch batch = new MDLZ_OrderFlipBatch(defaultChildBatchSize);
            List<ACCL__Order__c> ordList =MDLZ_TestDataFactory.insertWrapperOrder(1, true);
            SchedulableContext ctx = null;
            batch.execute(ctx);
        }
        test.stopTest();
    }
}