src/objects/ACCL__Org_Unit_User__c.object
<CustomObject>
    <description>Holds the details of the relationship between organization unit and user.</description>
    <fields>
        <fullName>MDLZ_isOrgUnitChanged__c</fullName>
        <description>This field is updated by Integration to &quot;Int Updated&quot; when there is a org unit change for the user.</description>
        <label>isOrgUnitChanged</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Int Updated</fullName>
                </value>
                <value>
                    <fullName>Batch Processed</fullName>
                </value>
                <value>
                    <fullName>TT Processed</fullName>
                </value>
                <value>
                    <fullName>RDR Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a user assigned to an org unit.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Org_Unit_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Unit User</label>
    <nameField>
        <displayFormat>OUU-{0000}</displayFormat>
        <label>Org Unit User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Unit Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>MDLZ_isChanged__c</fullName>
        <description>Field to be updated by integration as Int Updated when there is a change on the user record. To be updated by Batch as Batch Processed post processing of the record</description>
        <label>isChanged</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Int Updated</fullName>
                </value>
                <value>
                    <fullName>Batch Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MDLZ_UpdateOrgUnitUserValidityBatch.cls
/***************************************************************
Name: MDLZ_UpdateOrgUnitUserValidityBatch
======================================================
Purpose: this is the pre-processing batch process will be created for Org Unit User Clean-up
o New process will run before the current Org Unit User process runs
o New process will identify all users that have updates and deactivate all Org Unit User records (Today - 1) and then unset the new "update" flag
o Existing process will then run and expand the existing District and Team Org Unit User records from the top down (G4->G5 and G5->G6)
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE                DETAIL              Description
1.0      Priya Tubachi                03/30/2022     Initial Development    

***************************************************************/

global class MDLZ_UpdateOrgUnitUserValidityBatch implements Database.Batchable<sObject>,Schedulable{  
    
    //Defining the Scheduled Batch Size thru custom label
    public integer defaultChildBatchSize;
    global MDLZ_UpdateOrgUnitUserValidityBatch(integer childBatchSize){
        defaultChildBatchSize = childBatchSize;
    }
    
    //query locator for the batch to retrieve records
    global Database.QueryLocator start(Database.BatchableContext BC)    
    {
        String intUpdated = MDLZ_ConstantHelper.IntUpdated;
        String query ;
        if(test.isRunningTest()){
         query = 'Select Id from User where MDLZ_isChanged__c =: intUpdated and isActive = true LIMIT 1';   
        }else{
            //Made changes to the query as part of MRELKXIW-4033
        	query = 'Select Id from User where MDLZ_isChanged__c =: intUpdated and IsActive = true and id in (select ACCL__User__c from ACCL__Org_Unit_User__c where MDLZ_isOrgUnitChanged__c =: intUpdated)';}
        return Database.getQueryLocator(query);
        
    }
    
    //execute method of the batch class
    global void execute(Database.BatchableContext BC, List<sobject> scope)
    {
        //Calling the apex handler class
        system.debug('size of the list '+ scope.size());
        new MDLZ_UpdateOrgUnitUserValidity().updateUserValidity(scope); 
    }
    
    //schedulable execute method for the batch class
    global void execute(SchedulableContext ctx) {
        Database.executeBatch(this, defaultChildBatchSize); 
    } 
    
    //finish method of the batch class
    global void finish(Database.BatchableContext BC)
    {
        //Chaining Batch chain the L4 -> L5 -> L6 batch         
             Database.executeBatch(new MDLZ_RDRTeamUserAssignBatch(defaultChildBatchSize), defaultChildBatchSize);
        
    }
}