src/objects/ACCL__Order__c.object
<CustomObject>
    <description>Holds the header details of the order entry.</description>
    <fields>
        <fullName>ACCL__Delivery_Date__c</fullName>
        <description>By default next day.Delivery date calculation is
			customized very often.</description>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to capture customer for which Order is
			created</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Customer)</relationshipLabel>
        <relationshipName>Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Workflow neutral description of the order Entry status.</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Send to SAP</fullName>
                    <label>Sent to SAP</label>
                </value>
                <value>
                    <fullName>Received By SAP</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Routed</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MDLZ_isChanged__c</fullName>
        <description>Functionality introduced for RDT pilot for Order Redesign to address following defects:
MRELKXIW-1925, MRELKXIW-1912, MRELKXIW-1918</description>
        <label>IsChanged</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FALSE</fullName>
                    <default>true</default>
                    <label>FALSE</label>
                </value>
                <value>
                    <fullName>TRUE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MDLZ_WOForceSAPReceivedBatch.cls
/***************************************************************
Name: MDLZ_WOForceSAPReceivedBatch
======================================================
Purpose:
a. Batch apex class that will force update as "Receiced by SAP" on the wrapper / shelf order
======================================================
History
-------
VERSION     AUTHOR         REVIWER      DATE             DETAIL              Description
1.0     Bharath Vikkurthi              08/10/2021                    Initial Development    

***************************************************************/
//Cmt: fixing defects: MRELKXIW-1925, MRELKXIW-1912, MRELKXIW-1918 & INC1062101

global class MDLZ_WOForceSAPReceivedBatch implements Database.Batchable<sObject>,Schedulable  {
    
    private integer defaultChildBatchSize;
    
    //Constructor for MDLZ_WOForceSAPReceivedBatch
    public MDLZ_WOForceSAPReceivedBatch(integer childBatchSize){
        defaultChildBatchSize = childBatchSize;
    }
    //Fetching orders that have phase as 'SENT TO SAP' and Ischanged to false
    global Database.QueryLocator start(Database.BatchableContext BC)    
    {
        
        //Cmt: 
        string sentToSap = MDLZ_ConstantHelper.PhaseSentToSAP;
        string changeFalse =  MDLZ_ConstantHelper.ChangeFalse;
        
        String query = ' SELECT ACCL__Phase__c, MDLZ_isChanged__c, LastModifiedDate, ACCL__Order_Account__c, ACCL__Delivery_Date__c'
           + ' FROM ACCL__Order__c WHERE '
            + ' ACCL__Phase__c = :sentToSap  AND ' 
            + '  MDLZ_isChanged__c = :changeFalse ';        
        return Database.getQueryLocator(query);
    }
    
    //Calling execute method
    global void execute(Database.BatchableContext BC, List<ACCL__Order__c> listOrders)
    { 
        MDLZ_ErrorExceptionHandler exc = new MDLZ_ErrorExceptionHandler();
        try{
            string sentToSAP = MDLZ_ConstantHelper.PhaseSentToSAP;
            string changeFalse =  MDLZ_ConstantHelper.ChangeFalse;
            string changeTrue = MDLZ_ConstantHelper.ChangeTrue;
            //MRELKXIW-3984 - AND MDLZ_isChanged__c = :changeTrue ';
            string relatedQuery = 'select count() from ACCL__Order__c  WHERE ' 
                + ' ACCL__Phase__c = :sentToSAP   ' 
                + ' AND MDLZ_isChanged__c = :changeTrue ';
            
            List<string> listWhereClause = new List<string>(); 
            string relatedCriteria, storeID;
            Date deliveryDate;
            id orderID;
            List<ACCL__Order__c> orderPhaseToUpd = new List<ACCL__Order__c>();
            
            //Cmt: stay below a few 1000 query size (10K soql query size limit)
            for(ACCL__Order__c odr:listOrders){
                storeID = odr.ACCL__Order_Account__c;
                deliveryDate = odr.ACCL__Delivery_Date__c;
                orderID = odr.id;
                relatedCriteria = ' AND ( ACCL__Order_Account__c = :storeID AND ACCL__Delivery_Date__c = :deliveryDate '
                    + ' AND id != :orderID )';
         
                
                integer relatedRecordCount = Database.countQuery(relatedQuery + relatedCriteria);
                system.debug('relatedRecordCount:' + relatedRecordCount);    
                if(relatedRecordCount == 0 )
                {
                    odr.ACCL__Phase__c = MDLZ_ConstantHelper.ReceivedBySAP;
                    orderPhaseToUpd.add(odr);
                }                
            }            
            List<Database.SaveResult> srList =  database.update(orderPhaseToUpd, false);            
            exc.saveResultErrors(srList,orderPhaseToUpd,'MDLZ_WOForceSAPReceivedBatch()','ACCL__Order__c', 'Name');
            
        }catch(exception e){           
            exc.insertExceptions('MDLZ_WOForceSAPReceivedBatch',e.getMessage(),e.getLineNumber(),e.getTypeName());
        }
    }
    
    //Executing the method using Database.executeBatch
    global void execute(SchedulableContext ctx) {
        Database.executeBatch(new MDLZ_WOForceSAPReceivedBatch(200), defaultChildBatchSize);   
    }   
    
    //Chaining CAO order Wrapper batch for EDI, execute after current batch is complete
    global void finish(Database.BatchableContext BC)
    {
         //  Id batchJobId = Database.executeBatch(new MDLZ_CreateWrapperEDIOrderBatch(200), defaultChildBatchSize);
        //  Database.executeBatch(new MDLZ_CreateWrapperEDIOrderBatch(200), defaultChildBatchSize);
		 Database.executeBatch(new MDLZ_CreateWrapperOrderBatch(200), defaultChildBatchSize);
    }
    
}