src/objects/ACCL__Org_Unit__c.object
<CustomObject>
    <description>Holds the details of the organization unit object, defining a manufacturer´s organizational structure.</description>
    <fields>
        <fullName>ACCL__Org_Level__c</fullName>
        <description>Level of an organization unit regarding a organization type.</description>
        <label>Org Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>SalesOrganization</fullName>
                </value>
                <value>
                    <fullName>SalesOffice</fullName>
                </value>
                <value>
                    <fullName>SalesRep</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Org Unit</label>
    <nameField>
        <label>Org Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Org_Unit_User__c.object
<CustomObject>
    <description>Holds the details of the relationship between organization unit and user.</description>
    <fields>
        <fullName>MDLZ_isOrgUnitChanged__c</fullName>
        <description>This field is updated by Integration to &quot;Int Updated&quot; when there is a org unit change for the user.</description>
        <label>isOrgUnitChanged</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Int Updated</fullName>
                </value>
                <value>
                    <fullName>Batch Processed</fullName>
                </value>
                <value>
                    <fullName>TT Processed</fullName>
                </value>
                <value>
                    <fullName>RDR Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Org_Unit__c</fullName>
        <description>Reference to an org unit assigned to a user.</description>
        <label>Org Unit</label>
        <lookupFilter>
            <active>false</active>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Org_Unit__c</referenceTo>
        <relationshipLabel>Org Unit Users</relationshipLabel>
        <relationshipName>Org_Unit_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Org Unit User</label>
    <nameField>
        <displayFormat>OUU-{0000}</displayFormat>
        <label>Org Unit User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Unit Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MDLZ_UpdateTerritoryFlagBatchTest.cls
/***************************************************************
Name: MDLZ_UpdateTerritoryFlagBatchTest
======================================================
Purpose:
Test class for MDLZ_UpdateTerritoryFlagBatch class 
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0      Gaurav Gupta                 07/05/2022     Initial Development 

***************************************************************/
@isTest
private class MDLZ_UpdateTerritoryFlagBatchTest {
    static testMethod void createOrgUnit(){
        ACCL__Org_Unit__c OrgUnit = MDLZ_TestDataFactory.insertOrgUnit();
        User user = MDLZ_TestDataFactory.getUser(MDLZ_ConstantHelper.UserPermOPSADM);
        test.startTest();
        List<ACCL__Org_Unit_User__c> orgUnitUsers = MDLZ_TestDataFactory.createOrgUnitUserRecords(1, MDLZ_ConstantHelper.IntUpdated, OrgUnit, user);
        system.runAs(user){
            MDLZ_UpdateTerritoryFlagBatch batch = new MDLZ_UpdateTerritoryFlagBatch(10);             
            SchedulableContext ctx = null;
            batch.execute(ctx);
            test.stopTest();           
        }
        
        List<ACCL__Org_Unit_User__c> orgUnitUsersUpdated = [Select MDLZ_isOrgUnitChanged__c from ACCL__Org_Unit_User__c where ACCL__Org_Unit__r.ACCL__Org_Level__c =: MDLZ_ConstantHelper.Territory Limit 1];
        System.assertEquals(MDLZ_ConstantHelper.BatchProcessed, orgUnitUsersUpdated[0].MDLZ_isOrgUnitChanged__c);
    }
}