src/objects/ACCL__Product_Assortment__c.object
<CustomObject>
    <description>Holds the details of a set of products which are often used together.</description>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds the description of language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Product_Assortment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to product assortment template.</description>
        <label>Product Assortment Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Product_Assortment_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Product_Assortment_Template__c</referenceTo>
        <relationshipLabel>Product Assortments</relationshipLabel>
        <relationshipName>Product_Assortments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the product assortment belongs to.</description>
        <formula>TEXT(ACCL__Product_Assortment_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Product Assortment</label>
    <nameField>
        <label>Product Assortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Assortments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Product_Assortment_Account__c.object
<CustomObject>
    <description>Holds the details of the relationship bettween a product assortment and a business partner. A product assortment can have no, one or several business partners assigned. In this table the assigned business partners are kept time dependent.</description>
    <fields>
        <fullName>ACCL__Account__c</fullName>
        <description>Reference to customer.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Assortment Customers</relationshipLabel>
        <relationshipName>Product_Assortment_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ACCL__Product_Assortment__c</fullName>
        <description>Reference to product assortment.</description>
        <label>Product Assortment</label>
        <referenceTo>ACCL__Product_Assortment__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Product_Assortment_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Product Assortment Customer</label>
    <nameField>
        <displayFormat>PAA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Assortment Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Product_Assortment_Template__c.object
<CustomObject>
    <description>Template for product assortments. Controls the behaviour of the instances of this template, for example if a business partner must be specified (AccountMultiplicity). This table is sales organization dependent.</description>
    <fields>
        <fullName>ACCL__Account_Multiplicity__c</fullName>
        <description>How many business partners can be assigned to an assortment of this template.</description>
        <label>Customer Multiplicity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>n</fullName>
                </value>
                <value>
                    <fullName>m</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Boolean to identify if the Product Assortment template is active.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds the description of language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the product assortment template belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Product Assortment Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Assortment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Account_Number__c</fullName>
        <description>Customer Number.</description>
        <label>Customer Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ACCL__Account_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to customer template.</description>
        <label>Customer Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Account_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Account_Template__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer belongs to.</description>
        <formula>Text(ACCL__Account_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MDLZ_SAPBranchId__c</fullName>
        <label>SAP Branch Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MDLZ_LastmodifiedDate__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to customize the last modified date in the query locator of batches</description>
    <fields>
        <fullName>MDLZ_NoOfDays__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MDLZ_NoOfDays</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MDLZ_LastmodifiedDate</label>
</CustomObject>

src/classes/MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.cls
/***************************************************************
Name: MDLZ_ProdAssortmnt_ByCustBrnchTestFctry
======================================================
Purpose:
Test Factory for MDLZ_ProdAssortment_ByCustBranchBatch
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0      Priya Tubachi                11/02/2022     Initial Development    

***************************************************************/

public class MDLZ_ProdAssortmnt_ByCustBrnchTestFctry {
    private static MDLZ_ErrorExceptionHandler exc = new MDLZ_ErrorExceptionHandler();
    public static void createCustomSettings (){
        try{
            MDLZ_LastmodifiedDate__c trgs = new MDLZ_LastmodifiedDate__c();
            trgs.MDLZ_NoOfDays__c = 2;
            trgs.Name ='MDLZ_ProdAssortBranch';
            insert trgs;
            System.assertEquals(trgs.MDLZ_NoOfDays__c, 2);
        }catch(Exception ex){
            exc.insertExceptions('MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.createCustomSettings()',ex.getMessage(),
                                 ex.getLineNumber(),ex.getTypeName());
        }
    }                           
    
    public static ACCL__Account_Template__c insertAccTemplate(){
        ACCL__Account_Template__c acctemp = new ACCL__Account_Template__c();
        try{
            acctemp.Name ='Customer Template';
            acctemp.ACCL__Initial_Roles__c ='Customer';
            acctemp.ACCL__Sales_Org__c='US01';
            acctemp.ACCL__Active__c =true;
            acctemp.ACCL__Description_Language_1__c='Test Data';
            acctemp.RecordTypeId =Schema.SObjectType.ACCL__Account_Template__c.getRecordTypeInfosByName().
                get('Customer').getRecordTypeId();
            insert acctemp;
            // System.assertEquals(acctemp.ACCL__Sales_Org__c,'US01');
        }
        catch(Exception ex){
            exc.insertExceptions('MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.insertAccTemplate()',ex.getMessage(),
                                 ex.getLineNumber(),ex.getTypeName());
        }  
        return acctemp;
    }
    
    public static List<Account> insertAccount(Integer cnt){
        List<Account> accList = new List<Account>();
        try{
            for(Integer i=0; i<cnt; i++) {
                Account acct = new Account();
                acct.Name ='Demo Account';
                acct.ACCL__Account_Number__c='Demo Unique123'+i;
                acct.Description ='Test Descr';
                acct.ACCL__Account_Template__c =insertAccTemplate().id;
                acct.MDLZ_SAPBranchId__c ='234'+i;
                accList.add(acct);
            }       
            insert accList;
            //System.assertEquals('Demo Account', accList[0].Name); 
            
        }catch(Exception ex){
            exc.insertExceptions('MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.insertAccount()',ex.getMessage(),
                                 ex.getLineNumber(),ex.getTypeName());
        } 
        return accList;
    }
    
    public static ACCL__Product_Assortment_Template__c insertProductAssortmentTemplate() {
        RecordType rt = [SELECT Id,name FROM RecordType WHERE sObjectType='ACCL__Product_Assortment_Template__c' 
                         AND DeveloperName='Assortment_List'];
        ACCL__Product_Assortment_Template__c pat = new ACCL__Product_Assortment_Template__c();
        try{
            pat.Name = 'listing';
            pat.ACCL__Account_Multiplicity__c = 'Exactly One';
            pat.ACCL__Active__c = true;
            pat.ACCL__Description_Language_1__c = 'English';
            pat.RecordTypeId = rt.Id;
            pat.ACCL__Sales_Org__c = 'US01';
            
            insert pat;
            System.assertEquals(pat.ACCL__Sales_Org__c, 'US01');
        }catch(Exception ex){
            exc.insertExceptions('MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.insertProductAssortmentTemplate()',ex.getMessage(),ex.getLineNumber(),
                                 ex.getTypeName());
        } 
        return pat;
    }
    
    public static ACCL__Product_Assortment__c getProductAssortmentWithValidRange(Date validFrom, Date validThru, 
                                                                                 sObject productAssortmentTemplate) {
                                                                                     ACCL__Product_Assortment__c prodAssort = new ACCL__Product_Assortment__c();
                                                                                     try{
                                                                                         prodAssort.name ='testName';
                                                                                         prodAssort.ACCL__Product_Assortment_Template__c = productAssortmentTemplate.Id;
                                                                                         prodAssort.ACCL__Valid_From__c = validFrom;
                                                                                         prodAssort.ACCL__Valid_Thru__c = validThru;
                                                                                         prodAssort.ACCL__Description_Language_1__c='English'; 
                                                                                         insert prodAssort;
                                                                                         System.assertEquals('testName', prodAssort.Name); 
                                                                                     }catch(Exception ex){
                                                                                         exc.insertExceptions('MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.getProductAssortmentWithValidRange()',ex.getMessage(),
                                                                                                              ex.getLineNumber(),ex.getTypeName());
                                                                                     } 
                                                                                     return prodAssort;
                                                                                 }
    
    
    public static ACCL__Product_Assortment_Account__c insertProductAssortmentAccount
        (sObject productAssortment, sObject account) {
            ACCL__Product_Assortment_Account__c prodAssortAcc = new ACCL__Product_Assortment_Account__c();
            try{
                prodAssortAcc.ACCL__Account__c= account.Id;
                prodAssortAcc.ACCL__Product_Assortment__c= productAssortment.Id;
                prodAssortAcc.ACCL__Valid_From__c=System.today();
                prodAssortAcc.ACCL__Valid_Thru__c= System.today().addYears(1);
                insert prodAssortAcc;
                System.assertEquals(System.today(), prodAssortAcc.ACCL__Valid_From__c); 
            }catch(Exception ex){
                exc.insertExceptions('MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.insertProductAssortmentAccount()',ex.getMessage(),
                                     ex.getLineNumber(),ex.getTypeName());
            } 
            return prodAssortAcc;     
        }
    
    public static ACCL__Product_Assortment_Account__c insertProductAssortmentAccountInValid(sObject productAssortment,
                                                                                            sObject account) {
                                                                                                ACCL__Product_Assortment_Account__c prodAssortAcc = new ACCL__Product_Assortment_Account__c();
                                                                                                try{
                                                                                                    prodAssortAcc.ACCL__Account__c= account.Id;
                                                                                                    prodAssortAcc.ACCL__Product_Assortment__c= productAssortment.Id;
                                                                                                    prodAssortAcc.ACCL__Valid_From__c=System.today().addYears(-3);
                                                                                                    prodAssortAcc.ACCL__Valid_Thru__c= System.today().addYears(-1);
                                                                                                    insert prodAssortAcc;
                                                                                                    System.assertEquals(System.today().addYears(-3), prodAssortAcc.ACCL__Valid_From__c);             
                                                                                                }catch(Exception ex){
                                                                                                    exc.insertExceptions('MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.insertProductAssortmentAccountInValid()',ex.getMessage(),
                                                                                                                         ex.getLineNumber(),ex.getTypeName());
                                                                                                } 
                                                                                                return prodAssortAcc;
                                                                                            }
    
    public static ACCL__Product_Assortment_Store__c insertProductAssortmentStore(sObject productAssort, sObject acc) {
        ACCL__Product_Assortment_Store__c prodAssortStore = new ACCL__Product_Assortment_Store__c();
        try{
            prodAssortStore.ACCL__Store__c= acc.Id;
            prodAssortStore.ACCL__Assortment__c= productAssort.Id;
            insert prodAssortStore;
            // System.assertEquals(prodAssortStore.ACCL__Assortment__c,productAssort.Id);            
        }catch(Exception ex){
            exc.insertExceptions('MDLZ_ProdAssortmnt_ByCustBrnchTestFctry.insertProductAssortmentStore()',ex.getMessage(),
                                 ex.getLineNumber(),ex.getTypeName());
        } 
        return prodAssortStore;
    }
}