src/objects/ACCL__Account_Extension__c.object
<CustomObject>
    <description>Object to record account roles and further product related attributes.</description>
    <fields>
        <fullName>ACCL__Account_Plan_Type__c</fullName>
        <description>Specifies the level of the customer in the trade org hierarchies which is used for aggregation of KPIs.</description>
        <label>Account Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Account__c</fullName>
        <description>Reference to the customer to which the extension record is assigned.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Extensions</relationshipLabel>
        <relationshipName>Account_Extensions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Describes in which systems the record is stored.</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer extension belongs to.</description>
        <formula>ACCL__Account__r.ACCL__Sales_Org__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <label>Customer Extension</label>
    <nameField>
        <displayFormat>AEX-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Product__c.object
<CustomObject>
    <description>This object records the attributes of a product.</description>
    <fields>
        <fullName>ACCL__Product_Level__c</fullName>
        <description>Describes the Product Level.</description>
        <label>Product Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Category</fullName>
                </value>
                <value>
                    <fullName>SubCategory</fullName>
                    <label>Sub Category</label>
                </value>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Flavor</fullName>
                </value>
                <value>
                    <fullName>Package</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                    <default>true</default>
                    <label>Product</label>
                </value>
                <value>
                    <fullName>PPG</fullName>
                </value>
                <value>
                    <fullName>Case Config</fullName>
                </value>
                <value>
                    <fullName>Main Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the product belongs to.</description>
        <formula>TEXT(ACCL__Product_Template__r.ACCL__Sales_Org__c)</formula>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <label>Product</label>
	 <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Promotion__c.object
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Decides whether a promotion is available.</description>
        <inlineHelpText>Defines if the promotion is considered in the Trade Calendar and the Account Plan.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Anchor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Customer</description>
        <label>Anchor Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Phase of the promotion</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Preparation</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Modeling</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                    <default>true</default>
                    <label>Committed</label>
                </value>
                <value>
                    <fullName>ForApproval</fullName>
                    <label>For Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <formula>TEXT (ACCL__Promotion_Template__r.ACCL__Sales_Org__c)</formula>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Version__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Current version of the record. Updated on each operation.</description>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Account_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to customer template.</description>
        <label>Customer Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Account_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Account_Template__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer belongs to.</description>
        <formula>Text(ACCL__Account_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/NightlyCalculationBatch.cls
/** This class is used to set the necessary parameters which is expected by each Schedule class (Example: ScheduleReorganization,ScheduleAccountWriteback).
 *  This class calls the Schedule worker class in specific order which invokes all the worker endpoints.(order of endpoint execution -> ScheduleReorgnization,ScheduleAccountProductList,PromotionLoader and ScheduleAccountWriteback).
 */

public class NightlyCalculationBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {

	private static final String JOB_NAME = 'Promotions';
	private static final String PHASE_CANCELLED = 'Cancelled';
	private static final String PHASE_PREPARATION = 'Preparation';

	private String query = 'SELECT Id, ACCL__Version__c FROM ACCL__Promotion__c WHERE ACCL__Sales_Org__c = :salesOrg AND ACCL__Anchor_Account__c IN :accountIds AND ACCL__Phase__c NOT IN (\'' + PHASE_PREPARATION + '\',\'' + PHASE_CANCELLED + '\') AND ACCL__Active__c = true';
	public NightlyAccountSchedulingParameters scheduleParameters {
		get;set;
	}

	 /**
	 * Parmaters container used by the NightlyCalculationBatch.
	 */
	public class NightlyAccountSchedulingParameters {
		public String salesOrg {
			get; set;
		}
		public Set<Id> accountIds {
			get; set;
		}
		public Map<Id, List<Set<Id>>> kpiSetToSetOfAccounts {
			get; set;
		}
		public String txId {
			get; set;
		}
		public Set<Id> categoryids {
			get; set;
		}
		public Boolean refreshAccountProductList {
			get; set;
		}
        public String batchChain {
            get; set;
        }
	}

	 /**
     * Constructor.
     * @param salesOrg string value from Configuration record.
     * @param refreshAccountProductList Boolean value from Configuration, identify AccountProductList is either partial or full.
     */
	public NightlyCalculationBatch(String salesOrg, Boolean refreshAccountProductList) {
		this.scheduleParameters = new NightlyAccountSchedulingParameters();
		this.scheduleParameters.salesOrg = salesOrg;
		this.scheduleParameters.txId = ACCL.TransactionHandler.generateGUID();
		this.scheduleParameters.refreshAccountProductList = refreshAccountProductList;

        setScheduleParameters();

        ScheduleReorganization.schedule(this.scheduleParameters.txId, this.scheduleParameters.salesOrg, this.scheduleParameters.batchChain);
        ScheduleAccountProductList.schedule(this.scheduleParameters);
	}

	 /**
     *  @Description start function used to query the necessary SOQL data.
     *  @param BC BatchableContext
     *  @return query result
     */
	public Database.QueryLocator start(Database.BatchableContext BC) {
		Set<Id> accountIds = scheduleParameters.accountIds;
		String salesOrg = scheduleParameters.salesOrg;
		return Database.getQueryLocator(query);
	}

	/**
    *  @Description execute
    *  @param BatchableContext BC hold the values which we queried in start method.
    *  @param scope List of promotion records.
    *  @return void.
    */

	public void execute(Database.BatchableContext BC, List<ACCL__Promotion__c> scope) {
        Set<Id> promotionIds = new Map<Id, ACCL__Promotion__c>(scope).keySet();
		try {
            PromotionScheduleRequest request = new PromotionScheduleRequest(JOB_NAME, this.scheduleParameters.salesOrg, promotionIds, this.scheduleParameters.batchChain);
            ACCL.OffPlatformCallout calloutRequest = new ACCL.OffPlatformCallout('SCHEDULE_PROMOTION_CALCULATION', this.scheduleParameters.salesOrg);
            calloutRequest.execute(this.scheduleParameters.txId, null, JSON.serialize(request));
        } catch(Exception ex) {
                String jobId = BC.getJobId();
                System.abortJob(jobId);
            }
        }

	/**
    *  @Description finish
    *  @param BC BatchableContext BC hold the values which we queried in start method.
    *  @return void.
    */

	public void finish(Database.BatchableContext BC) {
        try {
            ScheduleAccountWriteback.schedule(this.scheduleParameters);
        } catch(Exception ex) {
                String jobId = BC.getJobId();
                System.abortJob(jobId);
            }
        }

	public void setScheduleParameters() {
		this.scheduleParameters.batchChain = String.format('TPM_Batches_{0}_{1}', new List<String>{ this.scheduleParameters.salesOrg, System.now().format('YYYYMMdd') });
		this.scheduleParameters.accountIds = new Set<Id>();
		this.scheduleParameters.kpiSetToSetOfAccounts = new Map<Id,List<Set<Id>>>();
		for (ACCL__Account_Extension__c a : [SELECT ACCL__Account__c, ACCL__Account__r.ACCL__Account_Template__c , ACCL__Account__r.ACCL__Account_Template__r.ACCL__KPI_Set_Plan_Dependent__c , ACCL__Account__r.ACCL__Account_Template__r.ACCL__Available_Product_Level__c FROM ACCL__Account_Extension__c WHERE ACCL__Account__r.ACCL__Sales_Org__c =:scheduleParameters.salesOrg  AND ACCL__Account_Plan_Type__c = 'Plan' AND ACCL__Account__r.ACCL__Account_Template__r.ACCL__KPI_Set_Plan_Dependent__c !=null ]){
			Id currentKpiSetId = a.ACCL__Account__r.ACCL__Account_Template__r.ACCL__KPI_Set_Plan_Dependent__c;
			List<Set<Id>> currentAccIdsForKpiSet = scheduleParameters.kpiSetToSetOfAccounts.get(currentKpiSetId);
			if(currentAccIdsForKpiSet == null ) {
				scheduleParameters.kpiSetToSetOfAccounts.put(currentKpiSetId, new List<Set<Id>> { new Set<Id>{a.ACCL__Account__c}  });
			} else {
				Set<Id> currentSetOfValues = currentAccIdsForKpiSet.get(currentAccIdsForKpiSet.size()-1);
				if(currentSetOfValues.size() == 1000) { 
					currentAccIdsForKpiSet.add(new Set<Id>{a.ACCL__Account__c});
				} else {
					currentSetOfValues.add(a.ACCL__Account__c);
				}
			}
			scheduleParameters.accountIds.add(a.ACCL__Account__c);
		}
		this.scheduleParameters.categoryids = new Map<Id, ACCL__Product__c>([SELECT Id FROM ACCL__Product__c WHERE ACCL__Sales_Org__c =:scheduleParameters.salesOrg AND ACCL__Product_Level__c ='Category']).keySet();
	}

	/**
	* Parameters container used by WebServiceUtils invoking the Promotion endpoint.
	*/
	private class PromotionScheduleRequest {
		String jobname;
		String salesorg;
		Set<Id> promotionids;
		String batchchain;

		private PromotionScheduleRequest( String jobName, String salesOrg, Set<Id> promotionIds, String batchChain) { 
			this.jobname = jobName;
			this.salesorg = salesOrg;
			this.promotionids = promotionIds; 
			this.batchchain = batchChain;
		}
	}
}