src/objects/ACCL__Unit_of_Measure__c.object
<CustomObject>
    <description>Holds the details od the units of measure (logistic unit) of a product.</description>
    <fields>
        <fullName>ACCL__Is_Consumer_Unit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Consumer unit.</description>
        <label>Is Consumer Unit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Is_Order_Unit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default order unit.</description>
        <inlineHelpText>Unit of Measure is default order unit.</inlineHelpText>
        <label>Is Order Unit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Is_Price_Unit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Price unit.</description>
        <inlineHelpText>Unit of Measure is default price unit.</inlineHelpText>
        <label>Is Price Unit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Ability__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Unit of Measure can be ordered.</description>
        <inlineHelpText>Unit of Measue is allowed for ordering.</inlineHelpText>
        <label>Order Ability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Unit_Type__c</fullName>
        <description>Type of the unit of measure.</description>
        <label>Unit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SalesUnit</fullName>
                    <default>true</default>
                    <label>SalesUnit</label>
                </value>
                <value>
                    <fullName>Layer</fullName>
                </value>
                <value>
                    <fullName>Pallet</fullName>
                </value>
                <value>
                    <fullName>ConsumerUnit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Unit of Measure</label>
    <nameField>
        <displayFormat>UoM-{00000}</displayFormat>
        <label>Unit of Measure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units of Measure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ExceptionLog__c.object
<CustomObject>
    <description>To track all exceptions occuring</description>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EXCP - {00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_ProductUnitFlagChange.cls
/***************************************************************
Name: MDLZ_ProductUnitFlagChange
======================================================
Purpose:
a.Update the UOM for each product as an interim fix for SAP issue
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              
1.0      Priya Tubachi         		  22/09/2021     Initial Development    
1.1      Priya Tubachi    Abir Ghosh  07/01/2022     
***************************************************************/
public with sharing class MDLZ_ProductUnitFlagChange {
    
    public static Boolean isTriggered = MDLZ_ConstantHelper.isTrue;
    
    public void ConsumerSalesUnitChange(List<ACCL__Unit_of_Measure__c> uomList){
          MDLZ_ErrorExceptionHandler exc = new MDLZ_ErrorExceptionHandler();
        List<ACCL__Unit_of_Measure__c> updDBList = new List<ACCL__Unit_of_Measure__c>();
        try{ 
            //loop through the list of products to update the unit of measure
            for(ACCL__Unit_of_Measure__c uom : uomList ){
                ACCL__Unit_of_Measure__c dbUOM = new ACCL__Unit_of_Measure__c();
                
                //update the consumer unit flags
                if (uom.ACCL__Unit_Type__c == System.Label.MDLZ_ConsumerUnit){
                    dbUOM.Id = uom.Id;
                    //change made to set price unit = false for consumer unit as per JIRA 2116
                    dbUOM.ACCL__Is_Price_Unit__c = MDLZ_ConstantHelper.isFalse;
                    dbUOM.ACCL__Is_Consumer_Unit__c = MDLZ_ConstantHelper.isTrue;
                    dbUOM.ACCL__Is_Order_Unit__c = MDLZ_ConstantHelper.isFalse;
                    dbUOM.ACCL__Order_Ability__c = MDLZ_ConstantHelper.isTrue;
                }else if(uom.ACCL__Unit_Type__c == System.Label.MDLZ_SalesUnit){
                    
                    //change made to set price unit = true for salesunit as per JIRA 2116
                    dbUOM.ACCL__Is_Price_Unit__c = MDLZ_ConstantHelper.isTrue;
                    dbUOM.Id = uom.Id;
                    dbUOM.ACCL__Is_Consumer_Unit__c = MDLZ_ConstantHelper.isFalse;
                    dbUOM.ACCL__Is_Order_Unit__c = MDLZ_ConstantHelper.isTrue;
                    dbUOM.ACCL__Order_Ability__c = MDLZ_ConstantHelper.isTrue;
                }
                updDBList.add(dbUOM);
            }
            
            //DML statement to update the records in the db
           // ExceptionLog__c errorlog = new ExceptionLog__c();
           
            system.debug('size of the db list to be updated '+updDBList.size());
            Database.SaveResult[] srList =   database.update(updDBList,false);
            exc.saveResultErrors(srList,updDBList,'MDLZ_ProductUnitFlagChange()','ACCL__Unit_of_Measure__c', 'Id');
            
            
        }catch(exception e){
            system.debug('An exception has occurred');
            exc.insertExceptions('MDLZ_ProductUnitFlagChange',e.getMessage(),e.getLineNumber(),e.getTypeName());
        } 
        
    }
}