src/objects/ACCL__Promotion__c.object
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Decides whether a promotion is available.</description>
        <inlineHelpText>Defines if the promotion is considered in the Trade Calendar and the Account Plan.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Anchor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Customer</description>
        <label>Anchor Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Commit_Date__c</fullName>
        <description>The date the promotion was commited. This field is taken for getting the prices and discounts of a promotion.</description>
        <label>Commit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_From__c</fullName>
        <description>Promotion date from</description>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_Thru__c</fullName>
        <description>Promotion date thru</description>
        <label>Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Delivery_Date_From__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Delivery Date From</description>
        <label>Shipment Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Delivery_Date_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Delivery Date Thru</description>
        <label>Shipment Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Id of the promotion that is used as reference in external systems. This id will be used by integration to import tactic specific actuals into the offplatform backend.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ACCL__Order_Date_From__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Order Date From.</description>
        <label>Order Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Date_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Order Date Thru.</description>
        <label>Order Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Phase of the promotion</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Preparation</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Modeling</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                    <default>true</default>
                    <label>Committed</label>
                </value>
                <value>
                    <fullName>ForApproval</fullName>
                    <label>For Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Placement_Date_From__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Placement Date From</description>
        <label>In-Store Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Placement_Date_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Placement Date Thru</description>
        <label>In-Store Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Promotion_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to promotion template.</description>
        <label>Promotion Template</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>ACCL__Promotion_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Promotion_Template__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Relevant_For_Account_Plan__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field is for project customization. Through this field one can set if the Promotion is specific for the Account Plan.</description>
        <inlineHelpText>Through this field one can set if the Promotion is specific for the Account Plan.</inlineHelpText>
        <label>Relevant For Account Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Slogan_Language_1__c</fullName>
        <description>Holds the slogan in language 1.</description>
        <label>Slogan Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__City__c</fullName>
        <description>Name of a city.</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Holds the unique external id.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ACCL__Name_2__c</fullName>
        <description>Alternate name for the customer.</description>
        <label>Name 2</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Street__c</fullName>
        <description>Name of a street.</description>
        <label>Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AggregatePromotionTestFactory.cls
public class AggregatePromotionTestFactory {
 private static Map<String,Schema.SObjectType> allObjMetaType = AddOnConstants.allObjectMetadataTypes;
 private static String ns = AddOnConstants.NAMESPACEPREFIX;
 private final Static String PROMOTION_PHASE_COMMITTED = 'Committed';
 Date today = System.today();
 
 public static final String query = 'SELECT Id, ACCL__Anchor_Account__c FROM ACCL__Promotion__c WHERE ACCL__Date_From__c <=today AND ACCL__Date_Thru__c >= today AND ACCL__Active__c=true AND ACCL__Phase__c =:PROMOTION_PHASE_COMMITTED AND ACCL__Anchor_Account__c != NULL';
    
    public static sobject getDefaultAccount() {
        sObject acc = allObjMetaType.get('Account').newSObject();
        acc.put('Name', 'testName');
        acc.put('ACCL__City__c', 'testCity');
        acc.put('ACCL__Street__c', 'testStreet');
        acc.put('ACCL__Name_2__c', 'testName2');
        insert acc;
        return acc;
    }
    
    public static List<sobject> insertBulkAccounts(Integer noOfAcc) {
        List<sObject> accList = new List<sObject>();
        for(Integer i=0; i<noOfAcc; i++) {
            sObject acc = allObjMetaType.get('Account').newSObject();
            acc.put('Name', 'testName'+i);
            acc.put('ACCL__City__c', 'testCity');
            acc.put('ACCL__Street__c', 'testStreet');
            acc.put('ACCL__Name_2__c', 'testName2'+i);
            accList.add(acc);
        }
        insert accList;
        return accList;
    }
    
    public static sobject getDefaultPromotionTemplate() {
        sObject promTemp = allObjMetaType.get('ACCL__Promotion_Template__c').newSObject();
        promTemp.put('Name', 'testName');
        promTemp.put('ACCL__Description_Language_1__c', 'testDesc');
        promTemp.put('ACCL__Active__c', true);
        promTemp.put('ACCL__Active_Policy__c', true);
        promTemp.put('ACCL__Consider_Listing__c', true);
        promTemp.put('ACCL__Creation_Platform__c', 'Laptop');
        promTemp.put('ACCL__Display_In_call__c', true);
        promTemp.put('ACCL__Mobility_Color__c', 'White');
        promTemp.put('ACCL__Sort__c', 1);
        promTemp.put('ACCL__Promotion_Type__c', 'Promotion');
        promTemp.put('ACCL__Product_Definition_Level__c', 'Tactic');
        promTemp.put('ACCL__Product_Definition_Policy__c', 'Dynamic');
        promTemp.put('ACCL__Is_Derivable__c', false);
        promTemp.put('ACCL__Anchor_Type__c', 'Customer');
        insert promTemp;
        return promTemp;
    }
    
    public static List<sobject> getDefaultPromotion(Integer noOfProm, sObject promTemp, sObject acc, String promPhase) {
        List<sObject> promList = new List<sObject>();
        Date dateFrom = System.today();
        Date dateThru = System.today().addYears(1);
        for(Integer i=0; i<noOfProm; i++) {
            sObject prom = allObjMetaType.get('ACCL__Promotion__c').newSObject();
            prom.put('ACCL__Active__c', true);
            prom.put('ACCL__Anchor_Account__c', acc != null ? acc.Id : null);
            prom.put('ACCL__Commit_Date__c', dateFrom);
            prom.put('ACCL__Promotion_Template__c', promTemp != null ? promTemp.Id : null);
            prom.put('ACCL__Date_From__c', dateFrom);
            prom.put('ACCL__Date_Thru__c', dateThru);
            prom.put('ACCL__Delivery_Date_From__c', dateFrom);
            prom.put('ACCL__Delivery_Date_Thru__c', dateFrom.addDays(30));
            prom.put('ACCL__Order_Date_From__c', dateFrom);
            prom.put('ACCL__Order_Date_Thru__c', dateThru);
            prom.put('ACCL__Placement_Date_From__c', dateFrom);
            prom.put('ACCL__Placement_Date_Thru__c', dateThru);
            prom.put('ACCL__Slogan_Language_1__c', 'testSlogan'+i);
            prom.put('ACCL__Phase__c', promPhase);
            prom.put('ACCL__Relevant_For_Account_Plan__c', true);
            promList.add(prom);
        }
        insert promList;
        return promList;
    }
    
    public static sobject getDefaultPromotion(sObject acc, Date dateFrom, Date dateThru, String promPhase) {
        sObject prom = allObjMetaType.get('ACCL__Promotion__c').newSObject();
        prom.put('ACCL__Active__c', true);
        prom.put('ACCL__Anchor_Account__c', acc != null ? acc.Id : null);
        prom.put('ACCL__Commit_Date__c', dateFrom);
        //prom.put('ACCL__Promotion_Template__c', promTemp != null ? promTemp.Id : null);
        prom.put('ACCL__Date_From__c', dateFrom);
        prom.put('ACCL__Date_Thru__c', dateThru);
        prom.put('ACCL__Delivery_Date_From__c', dateFrom);
        prom.put('ACCL__Delivery_Date_Thru__c', dateFrom.addDays(30));
        prom.put('ACCL__Order_Date_From__c', dateFrom);
        prom.put('ACCL__Order_Date_Thru__c', dateThru);
        prom.put('ACCL__Placement_Date_From__c', dateFrom);
        prom.put('ACCL__Placement_Date_Thru__c', dateThru);
        prom.put('ACCL__Slogan_Language_1__c', 'testSlogan');
        prom.put('ACCL__Phase__c', promPhase);
        prom.put('ACCL__Relevant_For_Account_Plan__c', true);
        insert prom;
        return prom;
    }
    
    public static sobject getDefaultPromotion(sObject acc, sObject promTemp, Date dateFrom, Date dateThru, String promPhase) {
        sObject prom = allObjMetaType.get('ACCL__Promotion__c').newSObject();
        prom.put('ACCL__Active__c', true);
        prom.put('ACCL__Anchor_Account__c', acc != null ? acc.Id : null);
        prom.put('ACCL__Commit_Date__c', dateFrom);
        prom.put('ACCL__Promotion_Template__c', promTemp.Id);
        prom.put('ACCL__Date_From__c', dateFrom);
        prom.put('ACCL__Date_Thru__c', dateThru);
        prom.put('ACCL__Delivery_Date_From__c', dateFrom);
        prom.put('ACCL__Delivery_Date_Thru__c', dateFrom.addDays(30));
        prom.put('ACCL__Order_Date_From__c', dateFrom);
        prom.put('ACCL__Order_Date_Thru__c', dateThru);
        prom.put('ACCL__Placement_Date_From__c', dateFrom);
        prom.put('ACCL__Placement_Date_Thru__c', dateThru);
        prom.put('ACCL__Slogan_Language_1__c', 'testSlogan');
        prom.put('ACCL__Phase__c', promPhase);
        prom.put('ACCL__Relevant_For_Account_Plan__c', true);
        insert prom;
        return prom;
    }
    
    public static sObject insertFlattenAccountHierarchy(sObject childAccount, sObject parentAccount) {
        sObject level1 = allObjMetaType.get('ACCL__Flatten_Account_Hierarchy__c').newSObject();
        level1.put('ACCL__Account__c', parentAccount.Id);
        level1.put('ACCL__Account_Level_01__c', parentAccount.Id);
        level1.put('ACCL__Node_Level__c', 1);
        level1.put('ACCL__Result_Level__c', 'Store;Trade Org');
        level1.put('ACCL__ExternalID__c', 'ExternalId');
        
        sObject level2 = allObjMetaType.get('ACCL__Flatten_Account_Hierarchy__c').newSObject();
        level2.put('ACCL__Account__c', childAccount.Id);
        level2.put('ACCL__Account_Level_01__c', parentAccount.Id);
        level2.put('ACCL__Account_Level_02__c', childAccount.Id);
        level2.put('ACCL__Node_Level__c', 2);
        level2.put('ACCL__Result_Level__c', 'Store');
        level2.put('ACCL__ExternalID__c', 'ExternalId');
        
        insert level1;
        insert level2;
        return level1;
    }
 
 }