src/objects/ACCL__Order__c.object
<CustomObject>
    <description>Holds the header details of the order entry.</description>
	<fields>
        <fullName>MDLZ_LastSavedByUser__c</fullName>
        <label>Last Saved By User</label>
        <type>DateTime</type>
    </fields>
	<fields>
        <fullName>MDLZ_isOrderAccepted__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Showing if an order was accepted (true) or rejected by SAP (false).</description>
        <label>Is Order Accepted</label>
        <type>Checkbox</type>
    </fields>
	<fields>
        <fullName>MDLZ_LastupdatedbySAP__c</fullName>
        <description>This field will be updated with the MDLZ_ReceivedBySAP__c field value and it is referred in MDLZ_OrderTriggerHandler.</description>
        <label>LastupdatedbySAP</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ACCL__Delivery_Date__c</fullName>
        <description>By default next day.Delivery date calculation is
			customized very often.</description>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to capture customer for which Order is
			created</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Customer)</relationshipLabel>
        <relationshipName>Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Order Template for Order Entry</description>
        <label>Order Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Order_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Order_Template__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Workflow neutral description of the order Entry status.</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Send to SAP</fullName>
                    <label>Sent to SAP</label>
                </value>
                <value>
                    <fullName>Received By SAP</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Routed</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MDLZ_IsSFAutoGenerated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Updated when a CAO wrapper order is created for NOS and EDI order</description>
        <label>Is SF AutoGenerated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MDLZ_SAPDeliveryDate__c</fullName>
        <label>SAP Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MDLZ_isChanged__c</fullName>
        <description>Functionality introduced for RDT pilot for Order Redesign to address following defects:
MRELKXIW-1925, MRELKXIW-1912, MRELKXIW-1918</description>
        <label>IsChanged</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FALSE</fullName>
                    <default>true</default>
                    <label>FALSE</label>
                </value>
                <value>
                    <fullName>TRUE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Order_Item__c.object
<CustomObject>
    <description>Holds the details of the order item object.</description>
    <fields>
        <fullName>ACCL__Order__c</fullName>
        <description>ID of the order where Order Item is associated with</description>
        <label>Order</label>
        <referenceTo>ACCL__Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
	<fields>
        <fullName>MDLZ_BkpItemStatus__c</fullName>
        <label>Bkp Item Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Empty</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
	<fields>
        <fullName>MDLZ_BkpSuggestedQty__c</fullName>
        <label>Bkp Suggested Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACCL__Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Quantity for this product.</description>
        <label>Quantity</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACCL__Suggested_Quantity__c</fullName>
        <description>The value contains the suggested order quantity that has been calculated via algorithm or that is given by a relevant promotion.</description>
        <label>Suggested Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MDLZ_ItemStatus__c</fullName>
        <label>Item Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Empty</fullName>
                    <default>true</default>
                    <label>Empty</label>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
	<fields>
        <fullName>MDLZ_LastSavedByUser__c</fullName>
        <description>Indicates whether item was added or updated by user on device</description>
        <label>Last Saved By User</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MDLZ_LineItemNumber__c</fullName>
        <label>Line Item Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{0000}</displayFormat>
        <label>Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Order_Template__c.object
<CustomObject>
    <description>Template which controls the behaviour of a sales document.</description>
	<fields>
        <fullName>MDLZ_IsOrderWrapper__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To identify the order wrapper template</description>
        <label>Is Order Wrapper</label>
        <type>Checkbox</type>
    </fields>
    <label>Order Template</label>
    <nameField>
        <label>Order Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDLZ_Orders_To_Flip__c.object
<CustomObject>
    <description>Addressing 2154 issue will be used in a batch to flip the order items</description>
	<fields>
        <fullName>MDLZ_Is_Order_Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This will be true when MDLZ_Is_Order_Accepted on order is true.</description>
        <label>Is Order Accepted</label>
        <type>Checkbox</type>
    </fields>
	<fields>
        <fullName>MDLZ_NewPhase__c</fullName>
        <length>50</length>
        <description>This field will save order's new phase value.</description>
        <label>NewPhase</label>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MDLZ_OldPhase__c</fullName>
		<length>50</length>
        <description>This field will save order's old phase value.</description>
        <label>OldPhase</label>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MDLZ_Operation__c</fullName>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OrderAccepted</fullName>
                </value>
                <value>
                    <fullName>DupWrapper</fullName>
                </value>
                <value>
                    <fullName>OrderSync</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>OrderId</label>
        <referenceTo>ACCL__Order__c</referenceTo>
        <relationshipLabel>Orders To Flip</relationshipLabel>
        <relationshipName>Orders_To_Flip</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Orders To Flip</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Orders To Flip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders To Flip</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>MDLZ_isChanged__c</fullName>
        <description>Field to be updated by integration as Int Updated when there is a change on the user record. To be updated by Batch as Batch Processed post processing of the record</description>
        <label>isChanged</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Int Updated</fullName>
                </value>
                <value>
                    <fullName>Batch Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MDLZ_OrderFlipBatch.cls
/***************************************************************
Name: MDLZ_OrderFlipBatch
======================================================
Purpose:
This batch will update order header and line item to address MRELKXIW-2154.
i.e. Mobile is overwriting updates from SAP due to sync / timing issue

Several options were evaluated to address JIRA-2154 issue before the batch implementation
Option 1: Before & After triggers on Order header. with after trigger applying switch of line item records
Ran into order of execution error --> 1) line item update, 2) after trigger because of rollup summary field and 3) after trigger because of header record
So the line items were getting updated thrice, switch not handled correctly

Option 2: Workflow field update on Line Items
Limitations as picklist field MDLZ_ItemStatus__c be updated from MDLZ_BkpItemStatus__c
Order of execution will make Workflow to fire before Order Hdr BeforeUpdate

Option 3: BeforeUpdate trigger on Line Items
Order of execution will make Workflow to fire before Order Hdr BeforeUpdate (https://help.salesforce.com/s/articleView?id=000333606&type=1)
So the line items didnt have context whether to apply the switch or not, and resulting in incorrect updates

Option 4: Queueable Class invoked from Header, to update line items
Will lead to recursive invocation of header trigger, because - when line items are updated, header trigger will fire again
and queueable class cannot be controlled to run as "Sysadmin" user, so header will initiate queueable class again
Static variables to stop recursive trigger execution, will not work too, as context for queueable execution is different each time.

Option 5: Batch jobs to handle Order header and line switch
Finally it was decided to move the code to scheduled batch class. Order Header Trigger will insert relevant OrderIds into MDLZ_Orders_To_Flip__c object
Batch class running as "Sysadmin" will perform the switch. Since its executing as Sysadmin, header trigger will not fire again

======================================================
History
-------
VERSION     AUTHOR               REVIEWER     DATE        DETAIL                Description
1.0         Amit Mirchandani     Navaneet N   20/04/2022  Initial Development   As stated above
1.2         Vaidehi Heda                      27/04/2022  As per 2928,MDLZ_Is_Order_Accepted__c will be marked as true on order if flip object records also has MDLZ_Is_Order_Accepted__c = true
1.3         Amit Mirchandani                  04/05/2022  Added filter/comparison condition for lastsavedbyUser and MDLZ_LastupdatedbySAP
1.4         Vaidehi Heda                      10/05/2022  Changes added to avoid phase change in orders as per below logic if old version in (Routed/Cancelled), then flip, but phase should remain Routed/Cancelled
if new version is Deleted and old version is Routed, the flip but leave phase as Routed.
1.5        Vaidehi Heda                       17/05/2022  As per 3584, This will delete duplicate wrappers based on account and delivery date  
1.6        Vaidehi Heda                       21/09/2022  Removed the condition to check created by for duplicate wrappers
***************************************************************/
global class MDLZ_OrderFlipBatch implements Database.Batchable<sObject> ,Schedulable {
    
    public integer defaultChildBatchSize;
    //Adding deleted and routed phase in set
    Set<String> orderPhase = new  Set<String>{MDLZ_ConstantHelper.PhaseRouted ,MDLZ_ConstantHelper.PhaseDeleted ,MDLZ_ConstantHelper.PhaseCancelled};
        Set<String> orderItemStatus = new  Set<String>{'A', 'C'};    
            public MDLZ_OrderFlipBatch(integer childBatchSize){
                defaultChildBatchSize = childBatchSize;
            }
    
    global Database.QueryLocator start(Database.BatchableContext BC)    
    { String query ;
     if(test.isRunningtest()){
         query = 'SELECT ID, MDLZ_NewPhase__c,MDLZ_OldPhase__c,MDLZ_Operation__c,MDLZ_Is_Order_Accepted__c, OrderID__c FROM MDLZ_Orders_To_Flip__c LIMIT 1';
     }
     else{ 
         query = 'SELECT ID, MDLZ_NewPhase__c,MDLZ_OldPhase__c,MDLZ_Operation__c,MDLZ_Is_Order_Accepted__c, OrderID__c FROM MDLZ_Orders_To_Flip__c ';
     }
     
     return Database.getQueryLocator(query);
    }
    
    //pending change public to global
    global void execute(Database.BatchableContext BC, List<MDLZ_Orders_To_Flip__c> listOrdersToFip){
        Map<Id, MDLZ_Orders_To_Flip__c>flipMap = new  Map<Id, MDLZ_Orders_To_Flip__c>();
        Set<Id>wrapperOrderIDs = new Set<Id>();
        List<ACCL__Order__c> ordList = new List<ACCL__Order__c>();
        Set<ID> orderIDs = new Set<Id>();    
        Set<ID> acceptedOrderIDs = new Set<Id>();
        Set<Id> orderAccount = new Set<Id>();
        Map<String, Date>orderstobeDeleted = new Map<String, Date>();    
        //SELECT ID FROM ACCL__Order__c WHERE ID IN (
        for(MDLZ_Orders_To_Flip__c odrFlip:listOrdersToFip){
            if(odrFlip.MDLZ_Operation__c == MDLZ_ConstantHelper.OrderSync){
                flipMap.put(odrFlip.OrderID__c , odrFlip);
            }
            //Added as per 2928
            else if(odrFlip.MDLZ_Operation__c == MDLZ_ConstantHelper.OrderAccepted){acceptedOrderIDs.add(odrFlip.OrderID__c);}
            //Added as per 3584
            else if(odrFlip.MDLZ_Operation__c == MDLZ_ConstantHelper.DupWrapper){wrapperOrderIDs.add(odrFlip.OrderID__c);}
            orderIDs.add(odrFlip.OrderID__c);
        }
        //Adding orders in map for delayed line items
        Map<Id, ACCL__Order__c> orderMap =getLineItems(orderIDs);
        
        List<ACCL__Order__c> listOfOrderToFlip = [SELECT id,MDLZ_LastupdatedbySAP__c,MDLZ_LastSavedByUser__c, MDLZ_isChanged__c,MDLZ_isOrderAccepted__c, ACCL__Delivery_Date__c,ACCL__Order_Account__c,
                                                  ACCL__Phase__c, MDLZ_SAPDeliveryDate__c FROM ACCL__Order__c 
                                                  WHERE Id  IN : orderIDs ];
        //AM: Code updated
        Set<ID> orderIDsThatFlipped = new Set<Id>();
        for(ACCL__Order__c order: listOfOrderToFlip){
            if(wrapperOrderIDs.contains(order.id)){
                orderstobeDeleted.put(order.ACCL__Order_Account__c+'|'+order.ACCL__Delivery_Date__c, order.ACCL__Delivery_Date__c );  
                orderAccount.add(order.ACCL__Order_Account__c);
            }else if(acceptedOrderIDs.contains(order.Id)){
                order.MDLZ_isOrderAccepted__c = true;
                order.ACCL__Phase__c =MDLZ_ConstantHelper.ReceivedBySAP;
                order.MDLZ_isChanged__c =MDLZ_ConstantHelper.ChangeFalse;
                order.ACCL__Delivery_Date__c =order.MDLZ_SAPDeliveryDate__c; 
                //AM: Code updated
                orderIDsThatFlipped.add(order.Id);
            }//Added as per 2928
            
            //AM: Code updated
            else if(order.MDLZ_LastSavedByUser__c!= null 
                    && order.MDLZ_LastupdatedbySAP__c!= null
                    && order.MDLZ_LastSavedByUser__c < order.MDLZ_LastupdatedbySAP__c)
            {               
                order.MDLZ_isChanged__c =MDLZ_ConstantHelper.ChangeFalse;
                order.ACCL__Delivery_Date__c =order.MDLZ_SAPDeliveryDate__c; //Added as per 2154
                
                if(orderPhase.Contains(flipMap.get(order.Id).MDLZ_OldPhase__c)){
                    order.ACCL__Phase__c =flipMap.get(order.Id).MDLZ_OldPhase__c;
                    orderIDsThatFlipped.add(order.Id);
                }else if(flipMap.get(order.Id).MDLZ_NewPhase__c== MDLZ_ConstantHelper.PhaseDeleted && flipMap.get(order.Id).MDLZ_OldPhase__c!=MDLZ_ConstantHelper.PhaseRouted){
                    order.ACCL__Phase__c =flipMap.get(order.Id).MDLZ_NewPhase__c; }
                else { 
                    if(orderMap.containsKey(order.Id)){
                        order.MDLZ_isChanged__c =MDLZ_ConstantHelper.ChangeTrue;
                    }else{
                        order.ACCL__Phase__c =MDLZ_ConstantHelper.ReceivedBySAP;
                        orderIDsThatFlipped.add(order.Id);
                    }}
            }                
            
        }            
        
        List<ACCL__Order_Item__c> listOfLineItemsToFlip = [SELECT id, MDLZ_ItemStatus__c, ACCL__Quantity__c, ACCL__Suggested_Quantity__c, MDLZ_BkpItemStatus__c,
                                                           MDLZ_BkpSuggestedQty__c, ACCL__Order__c  FROM ACCL__Order_Item__c 
                                                           WHERE ACCL__Order__c  IN : orderIDsThatFlipped ];
        for(ACCL__Order_Item__c lineItem: listOfLineItemsToFlip){
            lineItem.MDLZ_ItemStatus__c = lineItem.MDLZ_BkpItemStatus__c; //added as per 2154
            lineItem.ACCL__Quantity__c = lineItem.MDLZ_BkpSuggestedQty__c; //added as per 2154
            lineItem.ACCL__Suggested_Quantity__c = lineItem.MDLZ_BkpSuggestedQty__c;//Added as per 2154
        }
        
        Savepoint dbSavepoint;
        try{
            //create save point so that we can rollback any changes in case of failure
            dbSavepoint = Database.setSavepoint();
            UPDATE listOfLineItemsToFlip;
            UPDATE listOfOrderToFlip;
            DELETE listOrdersToFip; 
            //Added as per 3584
            if(orderstobeDeleted.size()>0){
                ordList= getWrapperOrders(orderstobeDeleted, wrapperOrderIDs, orderAccount);
                DELETE ordList; 
            }           
            //Cmt: Check if we need to commit the dbSavePoint
        }catch(Exception ex){
            if(!Test.isRunningTest()) { Database.rollback(dbSavepoint);}
            system.debug('Error: ' + ex);
            throw ex;
        }        
    }
    
    global void execute(SchedulableContext ctx) {        
        //CMt : For scheduled batch the size will be taken from Label.MDLZ_OrderFlipBatch
        integer defaultChildBatchSize = integer.valueOf(Label.MDLZ_OrderFlipBatch);
        Database.executeBatch(new MDLZ_OrderFlipBatch(defaultChildBatchSize), defaultChildBatchSize);   
    }
    
    global void finish(Database.BatchableContext BC)
    {
        
    } 
    
    //method to get orders for delayed line items
    public Map<Id, ACCL__Order__c> getLineItems(Set<Id>orderIdSet){
        Map<Id, ACCL__Order__c> orderMap = New Map<Id,ACCL__Order__c >([SELECT id, name FROM ACCL__Order__c WHERE
                                                                        Id IN (SELECT ACCL__Order__c FROM ACCL__Order_Item__c WHERE ACCL__Order__c IN:orderIdSet
                                                                               AND (MDLZ_LineItemNumber__c = NULL
                                                                                    OR  MDLZ_BkpItemStatus__c NOT IN: orderItemStatus)) 
                                                                       ]);
        return orderMap;
    }
    
    
    
    //method to get the duplicate wrapper orders based on delivery date and account
    public List<ACCL__Order__c> getWrapperOrders(Map<String, Date>orderstobeDeleted , Set<Id>wrapperOrderIDs, Set<Id>orderAccount){
        List<ACCL__Order__c> ordList = new List<ACCL__Order__c>();
        Map<String, ACCL__Order__c>ordMap = new Map<String, ACCL__Order__c>();
        Map<Id, ACCL__Order__c>dupOrderMap = new Map<Id, ACCL__Order__c>();
		Set<String> deletePhaseSet = new  Set<String>{MDLZ_ConstantHelper.PhaseDeleted};
        string keyOrderAndDelivery;
        Id sysadmin = getProId(LABEL.MDLZ_OrDate_Profile2);
        for (ACCL__Order__c order :[SELECT id, ACCL__Delivery_Date__c,createdby.profileId, ACCL__Order_Account__c, CreatedById,MDLZ_IsSFAutoGenerated__c FROM ACCL__Order__c WHERE 
                                    ACCL__Order_Account__c IN :orderAccount AND ACCL__Delivery_Date__c > LAST_N_Days:0 AND ACCL__Delivery_Date__c IN: orderstobeDeleted.values()
                                    AND ACCL__Order_Template__r.MDLZ_IsOrderWrapper__c=true AND ACCL__Phase__c NOT IN: deletePhaseSet  ORDER BY CreatedDate])
        {  
            
            keyOrderAndDelivery = order.ACCL__Order_Account__c+'|'+order.ACCL__Delivery_Date__c;
            
            if (orderstobeDeleted.containsKey(keyOrderAndDelivery)){
                if(!ordMap.containsKey(keyOrderAndDelivery)){
                    //Order comes first time either a user created or Sys admin created
                    ordMap.put(keyOrderAndDelivery , order);
                }else{  
                    //this is executed only if Order wrapper is duplicate
                    dupOrderMap.put(order.id, order);//This map will keep all the duplicate wrapper ids
                }}}      
        return dupOrderMap.values();
    }
    
    public static Id getProId(String proName){
        Id sysAdminId = [SELECT id, name FROM PRofile WHERE name =:proName LIMIT 1].Id;
        system.debug(sysAdminId);
        return sysAdminId;
    }
}