src/objects/ACCL__Account_Set__c.object
<CustomObject>
    <description>Object for the creation of Customer Sets.</description>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds Description in Language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Description__c</fullName>
        <description>Description based on the user specific language.</description>
        <formula>CASE($User.ACCL__Language_Postfix__c,
&quot;Language1&quot;, ACCL__Description_Language_1__c,
&quot;Language2&quot;, BLANKVALUE(ACCL__Description_Language_2__c,ACCL__Description_Language_1__c),
&quot;Language3&quot;, BLANKVALUE(ACCL__Description_Language_3__c,ACCL__Description_Language_1__c),
&quot;Language4&quot;, BLANKVALUE(ACCL__Description_Language_4__c,ACCL__Description_Language_1__c),
ACCL__Description_Language_1__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer set belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Customer Set</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Account_Set_Account__c.object
<CustomObject>
    <description>Junction object between Customer and Customer Set.</description>
    <fields>
        <fullName>ACCL__Account_Set_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Set Customers (Customer)</relationshipLabel>
        <relationshipName>Account_Set_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Account_Set__c</fullName>
        <description>Reference to Customer Set.</description>
        <label>Customer Set</label>
        <referenceTo>ACCL__Account_Set__c</referenceTo>
        <relationshipLabel>Customer Set Customers</relationshipLabel>
        <relationshipName>Account_Set_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Set Customer</label>
    <nameField>
        <displayFormat>ASA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Set Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Sales_Folder__c.object
<CustomObject>
    <description>This object contains the attributes associated with the Sales Folder.</description>
    <fields>
        <fullName>ACCL__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the customer.</description>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ACCL__Sales_Org__c</field>
                <operation>equals</operation>
                <valueField>Account.ACCL__Sales_Org__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Folders</relationshipLabel>
        <relationshipName>Sales_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active flag.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds the description of language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Description__c</fullName>
        <description>Description based on the user specific language.</description>
        <formula>CASE($User.ACCL__Language_Postfix__c, 
&quot;Language1&quot;, ACCL__Description_Language_1__c, 
&quot;Language2&quot;, BLANKVALUE(ACCL__Description_Language_2__c,ACCL__Description_Language_1__c), 
&quot;Language3&quot;, BLANKVALUE(ACCL__Description_Language_3__c,ACCL__Description_Language_1__c), 
&quot;Language4&quot;, BLANKVALUE(ACCL__Description_Language_4__c,ACCL__Description_Language_1__c),ACCL__Description_Language_1__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Folder_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Sales Folder Template</description>
        <label>Sales Folder Template</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>No matches found or Sales Folder Template is not active.</errorMessage>
            <filterItems>
                <field>ACCL__Sales_Folder_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Sales_Folder_Template__c</referenceTo>
        <relationshipLabel>Sales Folders</relationshipLabel>
        <relationshipName>Sales_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the sales folder belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <description>First date of validity period of the sales folder.</description>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <description>Last date of validity period of the sales folder.</description>
        <label>Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MDLZ_Customer_Sets__c</fullName>
        <label>Customer Sets</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MDLZ_Master_Record__c</fullName>
        <label>Master Record</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_Parent_RecordId__c</fullName>
        <label>Parent RecordId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Sales Folder</label>
    <nameField>
        <label>Sales Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Folders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Sales_Folder_Sell_Sheet__c.object
<CustomObject>
    <description>The object holds the details of the relationship between sales folder and sell sheet.</description>
    <fields>
        <fullName>ACCL__Sales_Folder__c</fullName>
        <description>Reference to the Sales Folder.</description>
        <label>Sales Folder</label>
        <referenceTo>ACCL__Sales_Folder__c</referenceTo>
        <relationshipLabel>Sell Sheets</relationshipLabel>
        <relationshipName>Sales_Folder_Sell_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the sales folder sell sheet belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sell_Sheet__c</fullName>
        <description>Reference to the Sell Sheet.</description>
        <label>Sell Sheet</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Sell_Sheet__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.ACCL__Sales_Org__c</field>
                <operation>equals</operation>
                <valueField>ACCL__Sell_Sheet__c.ACCL__Sales_Org__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Sell_Sheet__c</referenceTo>
        <relationshipLabel>Sales Folder Sell Sheets</relationshipLabel>
        <relationshipName>Sales_Folder_Sell_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Folder Sell Sheet</label>
    <nameField>
        <displayFormat>SFS-{00000000}</displayFormat>
        <label>Sales Folder Sell Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Folder Sell Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Sell_Sheet__c.object
<CustomObject>
    <description>This object contains the attributes associated with the sell sheet to be used on the sales folder.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active flag.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds the description of language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Description__c</fullName>
        <description>Description based on the user specific language.</description>
        <formula>CASE($User.ACCL__Language_Postfix__c, 
&quot;Language1&quot;, ACCL__Description_Language_1__c, 
&quot;Language2&quot;, BLANKVALUE(ACCL__Description_Language_2__c,ACCL__Description_Language_1__c), 
&quot;Language3&quot;, BLANKVALUE(ACCL__Description_Language_3__c,ACCL__Description_Language_1__c), 
&quot;Language4&quot;, BLANKVALUE(ACCL__Description_Language_4__c,ACCL__Description_Language_1__c),ACCL__Description_Language_1__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the sell sheet belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Sell Sheet</label>
    <nameField>
        <label>Sell Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sell Sheets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer belongs to.</description>
        <formula>Text(ACCL__Account_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ExceptionLog__c.object
<CustomObject>
    <description>To track all exceptions occuring</description>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EXCP - {00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_CustomersetPicklist.cls
/***************************************************************
Name: MDLZ_CustomersetPicklist
======================================================
Purpose:
a.Fetch all the customer set description and add to custom multiselect picklist datatype
b.Select the picklist value 
c.Create a record and add customers of the selected customerset along with Sellsheet
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL                 Description
1.0         Bharath_V                   07/06/2021     Initial Development    
1.1         Bharath_V     Abir Ghosh    01/02/2022     Initial Development 
***************************************************************/

Public with sharing class MDLZ_CustomersetPicklist {  
    
    
    Public List<String> selectedPicklistValues {get;set;}//Customer set Selected Value from picklist
    Public id currentRecordId {get;set;}//Current Record Id where customer set is to be assigned
    
    //Constructor to get current recordid 
    Public MDLZ_CustomersetPicklist(ApexPages.StandardController controller){
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id'); 
    } 
    
    //Fetching the customersets to display in the picklist
    Public List<SelectOption>  getCustomerSets(){
        List<SelectOption>  customerSets = new List<SelectOption>();
        try{  for( ACCL__Account_Set__c customer : [SELECT  Id, Name,ACCL__Description__c FROM ACCL__Account_Set__c LIMIT 900 ] ) {
            customerSets.add( new SelectOption( customer.ACCL__Description__c, customer.ACCL__Description__c ));
           
        }
            
           }catch(Exception e){
               
               system.debug('An exception has occurred');
               MDLZ_ErrorExceptionHandler exc = new MDLZ_ErrorExceptionHandler();
               exc.insertExceptions('MDLZ_CustomersetPicklist.getCustomerSets()',e.getMessage(),e.getLineNumber(),e.getTypeName()); 
           } 
        return customerSets;  
    }
    
    //Executed on click of save button
    //Creates salesfolder record for each customer in the selected customer sets
    //Also assigns sell sheets to each sales folder created.
    Public void save(){ 
        
        set<string> setCustomer = new set<string>();
        set<string> customerSetNames = new set<string>();
        MDLZ_ErrorExceptionHandler exc = new MDLZ_ErrorExceptionHandler();
        //List<ExceptionLog__c> expctlog = new List<ExceptionLog__c>();
        new List<ExceptionLog__c>();
        ACCL__Sales_Folder__c salesfolder = new ACCL__Sales_Folder__c();
        List<ACCL__Sales_Folder__c> customersetcustinsert = new List<ACCL__Sales_Folder__c>();
        List<ACCL__Sales_Folder_Sell_Sheet__c> ssListDb = new List<ACCL__Sales_Folder_Sell_Sheet__c>();
        Map<String,String> m2 = new Map<String,String>();
        Map<String,String> m3 = new Map<String,String>();
        try {
            //get the salesfolder details of the current record where customer set is being assigned
            salesfolder = [Select  Id, Name,ACCL__Account__c,MDLZ_Customer_Sets__c,
                           MDLZ_Master_Record__c,MDLZ_Parent_RecordId__c,
                           ACCL__Sales_Folder_Template__c,ACCL__Description_Language_1__c,ACCL__Sales_Org__c,ACCL__Valid_From__c,ACCL__Valid_Thru__c
                           From ACCL__Sales_Folder__c Where Id =: currentRecordId And ACCL__Active__c=true LIMIT 1]; 
            String singlePicklistValue = '';
            Boolean start = true;
            
            //create a string of selected customer sets to display in the details page.
            if(!selectedPicklistValues.isEmpty()) {          
                for(String str : selectedPicklistValues) { 
                    if(start) {
                        singlePicklistValue = str;
                        start = false;
                    }else{              
                        singlePicklistValue = singlePicklistValue + ' '+';'+' ' + str;                        
                    }
                    salesfolder.MDLZ_Customer_Sets__c = singlePicklistValue;
                    salesfolder.MDLZ_Master_Record__c =MDLZ_ConstantHelper.CustomerPicklist;                    
                }
                
                for(ACCL__Account_Set_Account__c prm: [Select Id,Name,ACCL__Account_Set__r.Id,
                                                       ACCL__Account_Set_Account__r.Name,
                                                       ACCL__Account_Set__r.Name,ACCL__Account_Set__r.ACCL__Description__c From 
                                                       ACCL__Account_Set_Account__c  Where  
                                                       ACCL__Account_Set__r.ACCL__Description__c IN:selectedPicklistValues ]){
                                                           m2.put(prm.ACCL__Account_Set_Account__r.Name, prm.ACCL__Account_Set_Account__r.Id);
                                                           setCustomer.add(prm.ACCL__Account_Set_Account__c);
                                                           customerSetNames.add(prm.Name);
                                                           if(salesfolder.ACCL__Account__c!=prm.ACCL__Account_Set_Account__c ){
                                                               ACCL__Sales_Folder__c salesfoldtemp = new ACCL__Sales_Folder__c(); 
                                                               salesfoldtemp.ACCL__Account__c =(String)prm.get('ACCL__Account_Set_Account__c');
                                                               salesfoldtemp.Name =salesfolder.Name ;
                                                               salesfoldtemp.ACCL__Active__c = true;
                                                               salesfoldtemp.ACCL__Sales_Folder_Template__c=salesfolder.ACCL__Sales_Folder_Template__c;
                                                               salesfoldtemp.ACCL__Description_Language_1__c= salesfolder.ACCL__Description_Language_1__c;
                                                               salesfoldtemp.ACCL__Sales_Org__c =salesfolder.ACCL__Sales_Org__c;
                                                               salesfoldtemp.ACCL__Valid_From__c =system.today();
                                                               salesfoldtemp.ACCL__Valid_Thru__c =Date.newInstance(2999, 12, 31);
                                                               salesfoldtemp.MDLZ_Customer_Sets__c =salesfolder.MDLZ_Customer_Sets__c;
                                                               salesfoldtemp.MDLZ_Parent_RecordId__c =salesfolder.Id;
                                                               salesfoldtemp.MDLZ_Unique_Name__c = (String)prm.get('Name');
                                                               
                                                               customersetcustinsert.add(salesfoldtemp);
                                                               
                                                               system.debug('salesfoldtemp :' +salesfoldtemp); 
                                                               
                                                           }    
                                                       }  
                for(ACCL__Sales_Folder__c exSalesfolder: [Select Id, Name,ACCL__Account__c From ACCL__Sales_Folder__c
                                                          Where MDLZ_Parent_RecordId__c =:salesfolder.Id ]){
                                                              m3.put(exSalesfolder.ACCL__Account__c, exSalesfolder.Id);
                                                              exSalesfolder.ACCL__Active__c = false;
                                                              exSalesfolder.ACCL__Valid_Thru__c = System.today(); 
                                                              customersetcustinsert.add(exSalesfolder);
                                                              
                                                          }
                
                if(customersetcustinsert.size()>0){
                    
                    List<Database.UpsertResult>  srList =  database.upsert(customersetcustinsert,false);
                    
                    exc.upsertResultErrors(srList,customersetcustinsert,'MDLZ_CustomersetPicklist().Save','ACCL__Sales_Folder__c');
                    
                }else{
                    system.debug('No records to be updated');
                }            
                
                //code to assign the sell sheets to newly created salesfolder records //Check with Abir 
                /* List<ACCL__Sales_Folder__c> childSFIds = [select id,ACCL__Sales_Org__c,MDLZ_Parent_RecordId__c from ACCL__Sales_Folder__c where
*  MDLZ_Parent_RecordId__c =: salesfolder.id AND ACCL__Active__c= true];
List<ACCL__Sales_Folder_Sell_Sheet__c> ssIds = [Select ACCL__Sell_Sheet__c from ACCL__Sales_Folder_Sell_Sheet__c 
where ACCL__Sales_Folder__c =: salesfolder.id];*/
                for(ACCL__Sales_Folder_Sell_Sheet__c sellSheet : [Select ACCL__Sell_Sheet__c from ACCL__Sales_Folder_Sell_Sheet__c 
                                                                  where ACCL__Sales_Folder__c =: salesfolder.id] ){
                    
                    for(ACCL__Sales_Folder__c childSF :[select id,ACCL__Sales_Org__c,MDLZ_Parent_RecordId__c
                                                        from ACCL__Sales_Folder__c where MDLZ_Parent_RecordId__c =: salesfolder.id
                                                        AND ACCL__Active__c= true]){
                                                            ACCL__Sales_Folder_Sell_Sheet__c ssLink = new ACCL__Sales_Folder_Sell_Sheet__c();   
                                                            ssLink.ACCL__Sell_Sheet__c =sellSheet.ACCL__Sell_Sheet__c;
                                                            ssLink.ACCL__Sales_Folder__c = childSF.id;
                                                            ssLink.ACCL__Sales_Org__c = childSF.ACCL__Sales_Org__c;
                                                            ssListDb.add(ssLink); 
                                                        }   
                }
                
                if(ssListDb.size()>0){
                    
                    List<Database.SaveResult> srList =   database.insert(ssListDb,false);
                    exc.saveResultErrors(srList,ssListDb,'MDLZ_CustomersetPicklist().Save','ACCL__Sales_Folder_Sell_Sheet__c', 'Name');
                    
                }
            }
            //Success Message for updating Customersets into salesfolder
            If(!selectedPicklistValues.isEmpty()  && m2.values()!=null ){
                database.update(salesfolder,false);
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Successfully Added Customer Sets'));
            }else{
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please Select Customer Set'));   
            }
            
        }catch(Exception e){   
            exc.insertExceptions('MDLZ_CustomersetPicklist()',e.getMessage(),e.getLineNumber(),e.getTypeName()); 
            
        } 
        
        
    }
    
    Public string getmyID(){
        if(currentRecordId==null)
            return'';
        else
            return currentRecordId;
    }
    //Redirect to previous page  
    Public PageReference doFinish(){
        PageReference pr = new PageReference('/'+ getmyID()); 
        pr.setRedirect(true);
        return pr;  
        
    }  
    Public void reset(){
        selectedPicklistValues.clear();
        
    } 
}