src/objects/ACCL__Account_Set__c.object
<CustomObject>
    <description>Object for the creation of Customer Sets.</description>
    <label>Customer Set</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Promotion__c.object
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <fields>
        <fullName>ACCL__Anchor_Account_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer Set</description>
        <label>Anchor Customer Set</label>
        <referenceTo>ACCL__Account_Set__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Anchor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Customer</description>
        <label>Anchor Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_From__c</fullName>
        <description>Promotion date from</description>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_Thru__c</fullName>
        <description>Promotion date thru</description>
        <label>Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Promotion_Template_Description__c</fullName>
        <formula>ACCL__Promotion_Template__r.ACCL__Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Promotion Template Description</label>
        <type>Text</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Account_Number__c</fullName>
        <description>Customer Number.</description>
        <label>Customer Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MDLZ_Ad_Break_Day__c</fullName>
        <defaultValue>&quot;Sunday&quot;</defaultValue>
        <label>Ad-Break Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MDLZ_Promotion_Export_AdBreak__mdt.object
<CustomObject>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <label>Batch Size</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Friday__c</fullName>
        <label>Friday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monday__c</fullName>
        <label>Monday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Saturday__c</fullName>
        <label>Saturday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sunday__c</fullName>
        <label>Sunday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Thursday__c</fullName>
        <label>Thursday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tuesday__c</fullName>
        <label>Tuesday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wednesday__c</fullName>
        <label>Wednesday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week_End_Sat__c</fullName>
        <label>Week End Sat</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week_Start_Sun__c</fullName>
        <label>Week Start Sun</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MDLZ Promotion Export AdBreak</label>
    <pluralLabel>MDLZ Promotion Export Adbreaks</pluralLabel>
</CustomObject>

src/objects/MDLZ_Promotion_Store__c.object
<CustomObject>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>ACCL__Promotion__c</referenceTo>
        <relationshipLabel>Promotion Stores</relationshipLabel>
        <relationshipName>MDLZ_Promotion_Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotion Stores</relationshipLabel>
        <relationshipName>MDLZ_Promotion_Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion Store</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>MDLZ_Promotion_Store Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_PromotionExportBatch.cls
/***************************************************************
Name: MDLZ_PromotionExportBatch
======================================================
Purpose: this batch process will update Ad-break date,Week start , Week End for Promotion Store records.
o New process will create those promotion Export records whose Promotion is active.
o New process will take into consideration Week Start as Sunday and week end as End date.Developed as
part of JIRA MRELKXIW-4366.
o Example: Promotion Start date = 1st July 2022 , Promotion End Date = 31st July 2022. Batch executes on 3rd July 2022,
On Account , Ad-Break Day = Wednesday.Then following will be populated by Batch on Promotion Export record,
Week Start = 3rd July , Week End = 9th July , Ad- break day = 6th July.

======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE                DETAIL              Description
1.0      Jinal Desai                  07/01/2022     Initial Development    

***************************************************************/

global class MDLZ_PromotionExportBatch implements Database.Batchable<sObject>{
    
    public static MDLZ_Promotion_Export_AdBreak__mdt adbreakMetadata = getMetadataRecord();
    
    global Database.QueryLocator start(Database.BatchableContext bCtx){
        
        String query = 'Select Id , Name , Promotion__c,Store__c,Store__r.ACCL__Account_Number__c, '+
            			+'Store__r.MDLZ_Ad_Break_Day__c, Promotion__r.ACCL__Date_From__c,Promotion__r.ACCL__Date_Thru__c, '+
            			+'Promotion__r.ACCL__Anchor_Account__r.Name , Promotion__r.ACCL__Anchor_Account_Set__r.ACCL__Description__c, '+
            			+'Promotion__r.ACCL__Promotion_Template_Description__c'
            			+' from MDLZ_Promotion_Store__c';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sobject> scope){
        
        MDLZ_PromotionExportHandler.createPromoExportRecord(scope,adbreakMetadata);
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
    
    /**
     * Custom metadata 'MDLZ_Promotion_Export_AdBreak__mdt' is created,
     * This custom metadata will store 'no of days' to be added to Batch execution Date,
	 * so that we can calculate Week Start , Week End date ,Ad break date.
	 * getMetadataRecord() method will pick up matadata record based on day on which batch is executed.
	 * Example: If batch is executed on Friday , matadata record name 'Friday' will be fetched and 
	 * accordingly calculations will be done.
    **/ 
    public static MDLZ_Promotion_Export_AdBreak__mdt getMetadataRecord(){
        Datetime dt = DateTime.newInstance(Date.today(), Time.newInstance(0, 0, 0, 0));
        String dayOfWeek=dt.format('EEEE');
        System.debug('###### Day : ' + dayOfWeek);
        
        MDLZ_Promotion_Export_AdBreak__mdt metadataRec = [Select Id , Label, Week_Start_Sun__c,Week_End_Sat__c,
                                                          Monday__c,Tuesday__c,Wednesday__c,Thursday__c,Friday__c,
                                                          Saturday__c,Sunday__c,Batch_Size__c
                                                          from MDLZ_Promotion_Export_AdBreak__mdt 
                                                          where Label = :dayOfWeek limit 1];
        
        return metadataRec;
        
    }
    
}