src/objects/ACCL__Account_Set__c.object
<CustomObject>
    <description>Object for the creation of Customer Sets.</description>
    <fields>
        <fullName>ACCL__Description__c</fullName>
        <description>Description based on the user specific language.</description>
        <formula>CASE($User.ACCL__Language_Postfix__c,
&quot;Language1&quot;, ACCL__Description_Language_1__c,
&quot;Language2&quot;, BLANKVALUE(ACCL__Description_Language_2__c,ACCL__Description_Language_1__c),
&quot;Language3&quot;, BLANKVALUE(ACCL__Description_Language_3__c,ACCL__Description_Language_1__c),
&quot;Language4&quot;, BLANKVALUE(ACCL__Description_Language_4__c,ACCL__Description_Language_1__c),
ACCL__Description_Language_1__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <label>Customer Set</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Promotion__c.object
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <fields>
        <fullName>ACCL__Anchor_Account_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer Set</description>
        <label>Anchor Customer Set</label>
        <referenceTo>ACCL__Account_Set__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Anchor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Customer</description>
        <label>Anchor Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_From__c</fullName>
        <description>Promotion date from</description>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_Thru__c</fullName>
        <description>Promotion date thru</description>
        <label>Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Promotion_Template_Description__c</fullName>
        <formula>ACCL__Promotion_Template__r.ACCL__Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Promotion Template Description</label>
        <type>Text</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Tactic__c.object
<CustomObject>
    <description>Relation from a Promotion and Tactic.</description>
    <fields>
        <fullName>ACCL__Date_From__c</fullName>
        <description>Start date of a tactic</description>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_Thru__c</fullName>
        <description>End date of a tactic</description>
        <label>Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Promotion__c</fullName>
        <description>Reference to the promotion</description>
        <label>Promotion</label>
        <referenceTo>ACCL__Promotion__c</referenceTo>
        <relationshipLabel>Tactics</relationshipLabel>
        <relationshipName>Tactics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tactic</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tactic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tactics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Tactic_Product__c.object
<CustomObject>
    <description>Junction Object between Tactic and Product</description>
    <fields>
        <fullName>ACCL__Tactic__c</fullName>
        <label>Tactic</label>
        <referenceTo>ACCL__Tactic__c</referenceTo>
        <relationshipLabel>Tactic Products</relationshipLabel>
        <relationshipName>Tactic_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>MDLZ_Location__c</fullName>
        <description>Stores the location for Tactic product</description>
        <label>Location</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_PPG__c</fullName>
        <description>Stores the PPG for Tactic product</description>
        <label>PPG</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_SubPPG__c</fullName>
        <description>Stores the Sub PPG for Tactic product</description>
        <label>Sub PPG</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Tactic Product</label>
    <nameField>
        <displayFormat>TP-{00000000}</displayFormat>
        <label>Tactic Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tactic Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Account_Number__c</fullName>
        <description>Customer Number.</description>
        <label>Customer Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MDLZ_Ad_Break_Day__c</fullName>
        <defaultValue>&quot;Sunday&quot;</defaultValue>
        <label>Ad-Break Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MDLZ_Promotion_Export__c.object
<CustomObject>
    <description>This will be used for the purpose of exporting promotion data to TRAX</description>
    <fields>
        <fullName>MDLZ_Activity_Ad_Break_Date__c</fullName>
        <description>Batch job will populate this field based on Ad break Day field on Account.</description>
        <label>Activity Ad Break Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MDLZ_Activity_Description__c</fullName>
        <description>To store Anchor Customer and Anchor Customer Set Names/Id.</description>
        <label>Activity Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MDLZ_Activity_End_Date__c</fullName>
        <description>To store Promotion End Date</description>
        <label>Activity End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MDLZ_Activity_ID__c</fullName>
        <description>To store Promotion Salesforce record Id</description>
        <label>Activity ID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MDLZ_Activity_Start_Date__c</fullName>
        <description>To store Promotion Start Date</description>
        <label>Activity Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MDLZ_Activity_Task_Description__c</fullName>
        <description>To store unique values of PPG/Sub PPG</description>
        <label>Activity Task Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MDLZ_Activity_Task_ID__c</fullName>
        <description>To store Tactic SF Id.</description>
        <label>Activity Task ID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MDLZ_Activity_Type__c</fullName>
        <description>To store Promotion Template Name</description>
        <label>Activity Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MDLZ_StoreECC__c</fullName>
        <label>StoreECC</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To store related account.</description>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotion Exports</relationshipLabel>
        <relationshipName>Promotion_Exports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion Export</label>
    <nameField>
        <label>Promotion Export Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotion Exports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDLZ_Promotion_Export_AdBreak__mdt.object
<CustomObject>
    <fields>
        <fullName>Friday__c</fullName>
        <label>Friday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monday__c</fullName>
        <label>Monday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Saturday__c</fullName>
        <label>Saturday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sunday__c</fullName>
        <label>Sunday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Thursday__c</fullName>
        <label>Thursday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tuesday__c</fullName>
        <label>Tuesday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wednesday__c</fullName>
        <label>Wednesday</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week_End_Sat__c</fullName>
        <label>Week End Sat</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week_Start_Sun__c</fullName>
        <label>Week Start Sun</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MDLZ Promotion Export AdBreak</label>
    <pluralLabel>MDLZ Promotion Export Adbreaks</pluralLabel>
</CustomObject>

src/objects/MDLZ_Promotion_Store__c.object
<CustomObject>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>ACCL__Promotion__c</referenceTo>
        <relationshipLabel>Promotion Stores</relationshipLabel>
        <relationshipName>MDLZ_Promotion_Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotion Stores</relationshipLabel>
        <relationshipName>MDLZ_Promotion_Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion Store</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>MDLZ_Promotion_Store Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_PromotionExportHandler.cls
/***************************************************************
Name: MDLZ_PromotionExportHandler
======================================================
Purpose: this batch process will create Ad-break date,Week start , Week End for Promotion export records.
o New process will create those promotion export records whose Promotion is active.
o New process will take into consideration Week Start as Sunday and week end as End date.Developed as
part of JIRA MRELKXIW-4366.
o Example: Promotion Start date = 1st July 2022 , Promotion End Date = 31st July 2022. Batch executes on 3rd July 2022,
On Account , Ad-Break Day = Wednesday.Then following will be populated by Batch on Promotion Store record,
Week Start = 3rd July , Week End = 9th July , Ad- break day = 6th July.
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE                DETAIL              Description
1.0      Jinal Desai                    07/01/2022     Initial Development    

***************************************************************/

public class MDLZ_PromotionExportHandler {
    
    public static Map<Id,Date> promoIdToWeekStartDate = new Map<Id,Date>();
    public static Map<Id,Date> promoIdToWeekEndDate = new Map<Id,Date>();
    public static String FandD  = MDLZ_ConstantHelper.Template_FandD;
    public static String SCRIPTED = MDLZ_ConstantHelper.Template_Scripted;
    public static String NON = MDLZ_ConstantHelper.Template_Non;
    
    public static void createPromoExportRecord(List<MDLZ_Promotion_Store__c> promotionStoreList,MDLZ_Promotion_Export_AdBreak__mdt adbreakMetadata){
        
        Set<Id> promotionIdSet = new Set<Id>();
        Date weekStartDate,weekEndDate;
        Map<Id,Set<String>> promotionToTacticProductMap = new Map<Id,Set<String>>();
        MDLZ_ErrorExceptionHandler exc = new MDLZ_ErrorExceptionHandler();
        List<Database.SaveResult> srList = new List<Database.SaveResult>();
        
        List<MDLZ_Promotion_Store__c> validPromoStoreList = new List<MDLZ_Promotion_Store__c>();
        Map<Id,Date> accIdToAdBreakDateMap = new Map<Id,Date>();
        List<MDLZ_Promotion_Export__c> createPromoExportList = new List<MDLZ_Promotion_Export__c>();
        Map<Id,String> accIdToL4AccountName = new Map<Id,String>();
        Set<Id> accIdSet = new Set<Id>();
        
        try{
            
            for(MDLZ_Promotion_Store__c promoStore : promotionStoreList){
                promotionIdSet.add(promoStore.Promotion__c);
            
                // calculates Week start date for Promotion Store record by adding no of days to batch execution day.
                weekStartDate = Date.today().addDays(Integer.valueOf(adbreakMetadata.Week_Start_Sun__c));
                promoIdToWeekStartDate.put(promoStore.Promotion__c,weekStartDate); 
                     
                // calculates Week End date for Promotion Store record by adding no of days to batch execution day.
                weekEndDate = Date.today().addDays(Integer.valueOf(adbreakMetadata.Week_End_Sat__c)); 
                promoIdToWeekEndDate.put(promoStore.Promotion__c,weekEndDate);
            
                Integer weekNum;
                Boolean isvalidAdBreakDate = false;
                Date adbreakDate;
            
                //Calculate Ad-break date for each Account        
                if(String.valueOf(promoStore.Store__r.MDLZ_Ad_Break_Day__c) != null){
                    weekNum = getWeekday(String.valueOf(promoStore.Store__r.MDLZ_Ad_Break_Day__c),adbreakMetadata);
                    adbreakDate = weekStartDate.addDays(weekNum);
                
                    // check if Ad break Date is within Week Start Date, Week End Date and Promotion End Date.
                    isvalidAdBreakDate = checkValidAdbreakDate(promoStore.Promotion__r.ACCL__Date_From__c,promoStore.Promotion__r.ACCL__Date_Thru__c,
                                                       weekStartDate,weekEndDate,adbreakDate);
                                                       
                }
            
                //Consider only those Promotion Store records whose Ad break date falls within our criteria 
                if(isvalidAdBreakDate){
                    validPromoStoreList.add(promoStore);
                    accIdToAdBreakDateMap.put(promoStore.Store__c,adbreakDate);
                    accIdSet.add(promoStore.Store__c);
                }
            }// end-of for
        
            // Get all Tactic Products with PPG , Sub ppg combinations related to Promotions.
            if(promotionIdSet.size() > 0){
                promotionToTacticProductMap = getTacticProductMap(promotionIdSet);
            }
            
			// Fetch Account Hierarchy records to get Level 4 Account. Account Level 4 is required to populate Activity Description field
			// on Promotion Export Record.
            if(accIdSet.size() > 0){
                for(ACCL__Flatten_Account_Hierarchy__c rec : [Select Id , ACCL__Account__c ,
                                                             ACCL__Account_Level_04__c , ACCL__Account_Level_04__r.Name
                                                             from ACCL__Flatten_Account_Hierarchy__c
                                                             where ACCL__Account__c IN :accIdSet]){
                                                                
                       accIdToL4AccountName.put(rec.ACCL__Account__c, String.valueof(rec.ACCL__Account_Level_04__r.Name));                  
                    
                }
            }
        
            // Creation of Promotion Export records.
            if(validPromoStoreList.size() > 0){
            for(MDLZ_Promotion_Store__c promoStore : validPromoStoreList){
                
                String storeEccNum;
                
                String activityDescription;
                
                if(!accIdToAdBreakDateMap.containsKey(promoStore.Store__c)){
                    continue;
                }
                
                if(String.valueOf(promoStore.Store__r.ACCL__Account_Number__c) != null){
                    storeEccNum = String.ValueOf(promoStore.Store__r.ACCL__Account_Number__c);
                    storeEccNum = storeEccNum.replaceFirst('^0+', '');
                }
                
                if(accIdToL4AccountName != null && accIdToL4AccountName.size()>0
                  && accIdToL4AccountName.containsKey(promoStore.Store__c)){
                    activityDescription = accIdToL4AccountName.get(promoStore.Store__c);
                }
                
                if(promotionToTacticProductMap.containsKey(promoStore.Promotion__c) && accIdToAdBreakDateMap.containsKey(promoStore.Store__c)){
                    for(String tacticProduct : promotionToTacticProductMap.get(promoStore.Promotion__c)){
                        List<String> tacticProductString = tacticProduct.split('\\+');
                        //Create Promotion Export record if Promotion Template contains F&D
                        if(String.ValueOf(promoStore.Promotion__r.ACCL__Promotion_Template_Description__c).contains(FandD)){
                            MDLZ_Promotion_Export__c newPromoExport = new MDLZ_Promotion_Export__c();
                            newPromoExport.MDLZ_Activity_Type__c = FandD;
                            newPromoExport.MDLZ_Store__c = promoStore.Store__c;
                            newPromoExport.MDLZ_Activity_ID__c = promoStore.Promotion__c;
                            newPromoExport.MDLZ_Activity_Task_Description__c = tacticProductString[0];
                            newPromoExport.MDLZ_Activity_Task_ID__c = tacticProductString[1];
							newPromoExport.MDLZ_Activity_Description__c = activityDescription;
                            /*if(promoStore.Promotion__r.ACCL__Anchor_Account__r.Name != null){
                                newPromoExport.MDLZ_Activity_Description__c = activityDescription + ' ' +promoStore.Promotion__r.ACCL__Anchor_Account__r.Name;
                            }else{
                                newPromoExport.MDLZ_Activity_Description__c = activityDescription + ' ' +promoStore.Promotion__r.ACCL__Anchor_Account_Set__r.ACCL__Description__c;
                            }*/
                            newPromoExport.MDLZ_Activity_Start_Date__c = promoStore.Promotion__r.ACCL__Date_From__c;
                            newPromoExport.MDLZ_Activity_End_Date__c = promoStore.Promotion__r.ACCL__Date_Thru__c;
                            newPromoExport.MDLZ_Activity_Ad_Break_Date__c = accIdToAdBreakDateMap.get(promoStore.Store__c);
                            newPromoExport.MDLZ_StoreECC__c = storeEccNum;
                            createPromoExportList.add(newPromoExport);
                        } // end of F&D 
                        
                        //Create Promotion Export record if Promotion Template contains only 'Scripted'
                        if(String.ValueOf(promoStore.Promotion__r.ACCL__Promotion_Template_Description__c).contains(SCRIPTED)
                        && !String.ValueOf(promoStore.Promotion__r.ACCL__Promotion_Template_Description__c).contains(NON)){

                            MDLZ_Promotion_Export__c newPromoExport = new MDLZ_Promotion_Export__c();
                            newPromoExport.MDLZ_Activity_Type__c = SCRIPTED;
                            newPromoExport.MDLZ_Store__c = promoStore.Store__c;
                            newPromoExport.MDLZ_Activity_ID__c = promoStore.Promotion__c;
                            newPromoExport.MDLZ_Activity_Task_Description__c = tacticProductString[0];
                            newPromoExport.MDLZ_Activity_Task_ID__c = tacticProductString[1];
							newPromoExport.MDLZ_Activity_Description__c = activityDescription;
                            /*if(promoStore.Promotion__r.ACCL__Anchor_Account__r.Name != null){
                                newPromoExport.MDLZ_Activity_Description__c = activityDescription + ' ' +promoStore.Promotion__r.ACCL__Anchor_Account__r.Name;
                            }else{
                                newPromoExport.MDLZ_Activity_Description__c = activityDescription + ' ' +promoStore.Promotion__r.ACCL__Anchor_Account_Set__r.ACCL__Description__c;
                            }*/
                            newPromoExport.MDLZ_Activity_Start_Date__c = promoStore.Promotion__r.ACCL__Date_From__c;
                            newPromoExport.MDLZ_Activity_End_Date__c = promoStore.Promotion__r.ACCL__Date_Thru__c;
                            newPromoExport.MDLZ_Activity_Ad_Break_Date__c = accIdToAdBreakDateMap.get(promoStore.Store__c);
                            newPromoExport.MDLZ_StoreECC__c = storeEccNum;
                            createPromoExportList.add(newPromoExport);      
                                
                        }// end of scripted
                        
                        //Create Promotion Export record when Promotion Template other than 'F&D' , 'Scripted'
                        if(!String.ValueOf(promoStore.Promotion__r.ACCL__Promotion_Template_Description__c).contains(SCRIPTED)
                            && !String.ValueOf(promoStore.Promotion__r.ACCL__Promotion_Template_Description__c).contains(NON)
                            && !String.ValueOf(promoStore.Promotion__r.ACCL__Promotion_Template_Description__c).contains(FandD)){

                            MDLZ_Promotion_Export__c newPromoExport = new MDLZ_Promotion_Export__c();
                            newPromoExport.MDLZ_Activity_Type__c = String.Valueof(promoStore.Promotion__r.ACCL__Promotion_Template_Description__c);
                            newPromoExport.MDLZ_Store__c = promoStore.Store__c;
                            newPromoExport.MDLZ_Activity_ID__c = promoStore.Promotion__c;
                            newPromoExport.MDLZ_Activity_Task_Description__c = tacticProductString[0];
                            newPromoExport.MDLZ_Activity_Task_ID__c = tacticProductString[1];
							newPromoExport.MDLZ_Activity_Description__c = activityDescription;
                            /*if(promoStore.Promotion__r.ACCL__Anchor_Account__r.Name != null){
                                newPromoExport.MDLZ_Activity_Description__c = activityDescription + ' ' +promoStore.Promotion__r.ACCL__Anchor_Account__r.Name;
                            }else{
                                newPromoExport.MDLZ_Activity_Description__c = activityDescription + ' ' +promoStore.Promotion__r.ACCL__Anchor_Account_Set__r.ACCL__Description__c;
                            }*/
                            newPromoExport.MDLZ_Activity_Start_Date__c = promoStore.Promotion__r.ACCL__Date_From__c;
                            newPromoExport.MDLZ_Activity_End_Date__c = promoStore.Promotion__r.ACCL__Date_Thru__c;
                            newPromoExport.MDLZ_Activity_Ad_Break_Date__c = accIdToAdBreakDateMap.get(promoStore.Store__c);
                            newPromoExport.MDLZ_StoreECC__c = storeEccNum;
                            createPromoExportList.add(newPromoExport);
                                
                        }

                    }
                    
                }   
                
            }// end-of for
            
        } //end-of if
        
        if(createPromoExportList.size() > 0){
            srList = Database.Insert(createPromoExportList,false);
            exc.saveResultErrors(srList,createPromoExportList,'MDLZ_PromotionExportHandler().createPromoExportRecord','MDLZ_Promotion_Export__c','MDLZ_Store__c');
        }
            
        }catch(Exception E){
            exc.insertExceptions('MDLZ_PromotionExportHandler()',e.getMessage(),e.getLineNumber(),e.getTypeName());
        }
        
        
        
    }
    
    /* Metadata record and Ad-Break day week from Account passed as parameters
     * Based on Weekday , no of days from metadata will be fetched to calculate final ad-break date
     * Example , Ad break day on Account = Thursday , then '4' will be fetched from custom metadata
     * and logic will add 4 days to Week Start Date.
    */
    
    public static Integer getWeekday(String weekday,MDLZ_Promotion_Export_AdBreak__mdt selectedBatchMetadata){
       Integer weekNum = 0;
        switch on weekday{
            when 'Monday' {
                weekNum = Integer.valueof(selectedBatchMetadata.Monday__c);
            }
            when 'Tuesday' {
                weekNum = Integer.valueof(selectedBatchMetadata.Tuesday__c);
            }
            when 'Wednesday' {
                weekNum = Integer.valueof(selectedBatchMetadata.Wednesday__c);
            }
            when 'Thursday' {
                weekNum = Integer.valueof(selectedBatchMetadata.Thursday__c);
            }
            when 'Friday' {
                weekNum = Integer.valueof(selectedBatchMetadata.Friday__c);
            }
            when 'Saturday' {
                weekNum = Integer.valueof(selectedBatchMetadata.Saturday__c);
            }
            when 'Sunday' {
                weekNum = Integer.valueOf(selectedBatchMetadata.Sunday__c);
            }
            
        }
        
        return weekNum;
        
    }
    
    public static Boolean checkValidAdbreakDate(Date promotionStartDate,Date promotionEndDate,
                                               Date weekStartDate , Date weekEndDate , Date adbreakDate){
                                                   
        Boolean isValidAdBreakDate = false;
                                                  
        if(adbreakDate >= weekStartDate && adbreakDate <= weekEndDate
           && adbreakDate <= promotionEndDate){
              isValidAdBreakDate = true;                                         
        }
        
        return isValidAdBreakDate;
    }

    //Method to get all the ppg and subppg combinations from tactic products related to Promtions
    public static Map<Id,Set<String>> getTacticProductMap(Set<Id> promoIdSet){
        Map<Id,Set<String>> promotionToTacticProductMap = new Map<Id,Set<String>>();
        for(ACCL__Tactic_Product__c tactic : [SELECT Id,  MDLZ_Location__c, MDLZ_SubPPG__c, MDLZ_PPG__c, Name, ACCL__Tactic__c, ACCL__Tactic__r.ACCL__Promotion__c  FROM ACCL__Tactic_Product__c WHERE ACCL__Tactic__r.ACCL__Promotion__c IN :promoIdSet]){
            if(promotionToTacticProductMap.containsKey(tactic.ACCL__Tactic__r.ACCL__Promotion__c)){
                String tacticProductString;
                if(tactic.MDLZ_SubPPG__c != null && tactic.MDLZ_SubPPG__c != ''){
                    tacticProductString = tactic.MDLZ_SubPPG__c + '+' + tactic.ACCL__Tactic__c;
                } else {
                    tacticProductString = tactic.MDLZ_PPG__c + '+' + tactic.ACCL__Tactic__c;
                }
                promotionToTacticProductMap.get(tactic.ACCL__Tactic__r.ACCL__Promotion__c).add(tacticProductString);
            } else {
                String tacticProductString;
                if(tactic.MDLZ_SubPPG__c != null && tactic.MDLZ_SubPPG__c != ''){
                    tacticProductString = tactic.MDLZ_SubPPG__c + '+' + tactic.ACCL__Tactic__c;
                } else {
                    tacticProductString = tactic.MDLZ_PPG__c + '+' + tactic.ACCL__Tactic__c;
                }
                promotionToTacticProductMap.put(tactic.ACCL__Tactic__r.ACCL__Promotion__c, new Set<String>{tacticProductString});
            }
        }
        return promotionToTacticProductMap;
    }

    public class tacticProductWrapper{
        public string ppgSubppg;
        public string tacticId;
    }

}