src/objects/ACCL__Account_Set__c.object
<CustomObject>
    <description>Object for the creation of Customer Sets.</description>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds Description in Language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Description__c</fullName>
        <description>Description based on the user specific language.</description>
        <formula>CASE($User.ACCL__Language_Postfix__c,
&quot;Language1&quot;, ACCL__Description_Language_1__c,
&quot;Language2&quot;, BLANKVALUE(ACCL__Description_Language_2__c,ACCL__Description_Language_1__c),
&quot;Language3&quot;, BLANKVALUE(ACCL__Description_Language_3__c,ACCL__Description_Language_1__c),
&quot;Language4&quot;, BLANKVALUE(ACCL__Description_Language_4__c,ACCL__Description_Language_1__c),
ACCL__Description_Language_1__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer set belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Customer Set</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Call__c.object
<CustomObject>
    <description>Contains data of customer related calls.</description>
    <fields>
        <fullName>ACCL__Account__c</fullName>
        <description>Customer associated to Call created</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Calls</relationshipLabel>
        <relationshipName>Calls</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Call_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Call Template associated to the Call</description>
        <label>Call Template</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>No matches found or call Template is not active.</errorMessage>
            <filterItems>
                <field>ACCL__Call_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Call_Template__c</referenceTo>
        <relationshipLabel>Calls</relationshipLabel>
        <relationshipName>Calls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <label>Call</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Call_Template__c.object
<CustomObject>
    <description>Template describing basic call behaviour.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Company_Required__c</fullName>
        <description>Company Required</description>
        <label>Company Required</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not required</fullName>
                    <default>true</default>
                    <label>Not required</label>
                </value>
                <value>
                    <fullName>Mandatory</fullName>
                </value>
                <value>
                    <fullName>Optional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Creation_Platform__c</fullName>
        <description>Creation Platform</description>
        <label>Creation Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Both</fullName>
                    <default>true</default>
                    <label>Both</label>
                </value>
                <value>
                    <fullName>Mobility</fullName>
                </value>
                <value>
                    <fullName>Laptop</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Default_Duration__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Default Duration</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RE_CallTemplate_ExternalID__c</fullName>
        <description>It maintain Unique value for external ID</description>
        <externalId>true</externalId>
        <label>RE_Call Template_ExternalID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Call Template</label>
    <nameField>
        <label>Call Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Job_Definition_List__c.object
<CustomObject>
    <description>Holds the set of questions/surveys that are to be carried out in the respective call and contains further relevant configurations.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Call_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Call Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Call_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>ACCL__Call_Template__c.ACCL__Sales_Org__c</field>
                <operation>equals</operation>
                <valueField>$Source.ACCL__Sales_Org__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Call_Template__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Job_Definition_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Consider_Account__c</fullName>
        <formula>ACCL__Job_Definition_List_Template__r.ACCL__Consider_Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Consider Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Job_Definition_List_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Activity Template</label>
        <referenceTo>ACCL__Job_Definition_List_Template__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Job_Definition_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes sales organization which the activity belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Standard_Jobs__c</fullName>
        <formula>ACCL__Job_Definition_List_Template__r.ACCL__Standard_Jobs__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Standard Jobs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <inlineHelpText>Updated based on activity template and valid from value.</inlineHelpText>
        <label>Valid Thru</label>
        <type>Date</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Job_Definition_List_Account_Set__c.object
<CustomObject>
    <description>Junction object between Job Definition List and Customer Set.</description>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes sales organization which the account set assignment of the activity (and the activity itself) belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Activity Customer Set</label>
    <nameField>
        <displayFormat>JDLCS-{0000}</displayFormat>
        <label>Activity Customer Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Customer Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Job_List__c.object
<CustomObject>
    <description>Holds the job lists generated out of non-standard job definition lists.</description>
    <fields>
        <fullName>ACCL__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Job Lists</relationshipLabel>
        <relationshipName>Job_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Call_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Call Template</label>
        <referenceTo>ACCL__Call_Template__c</referenceTo>
        <relationshipLabel>Job Lists</relationshipLabel>
        <relationshipName>Job_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Call__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Call</label>
        <referenceTo>ACCL__Call__c</referenceTo>
        <relationshipLabel>Job Lists</relationshipLabel>
        <relationshipName>Job_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <label>Valid Thru</label>
        <type>Date</type>
    </fields>
    <label>Job List</label>
    <nameField>
        <displayFormat>JL-{0000}</displayFormat>
        <label>Job List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Account_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to customer template.</description>
        <label>Customer Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Account_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Account_Template__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__City__c</fullName>
        <description>Name of a city.</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Name_2__c</fullName>
        <description>Alternate name for the customer.</description>
        <label>Name 2</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer belongs to.</description>
        <formula>Text(ACCL__Account_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Street__c</fullName>
        <description>Name of a street.</description>
        <label>Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/GenerateJobListTestFactory.cls
@isTest
/**  PROGRAM NAME : GenerateJobListTestFactory 
     * This class is a test factory class to provide data setup to be refered in GenerateJobListBatchTest class.
     * @see    GenerateJobListBatchTest
     * @version  1.0
     * @Created Date 2018-10-18
*/
public class GenerateJobListTestFactory {
	/** Private Variables */
    private static Map<String,Schema.SObjectType> allObjMetaType = AddOnConstants.allObjectMetadataTypes;
    private static final string PROCESS_NAME = 'JobListGeneration';
    private final Static String CUSTOMER_RECORD_TYPE = 'Customer';
    private final Static String CUSTOMER_TEMPLATE_OBJECT = 'ACCL__Account_Template__c';
    private final Static String CALL_CREATION_MODE_MANUALLY = 'Manually';
    private final Static String CALL_STATUS_PLANNED = 'Plan';
    
    /**
     *  @description This method creates a record in the Batch_Process_Configuration__c custom setting to determine default batch size.
     *  @param None
     *  @return None
     *  @throws None
     */
    public static void createCustomSettingData() {
        sObject sObj = allObjMetaType.get('ACCL__Batch_Process_Configuration__c').newSObject();
        sObj.put('Name', PROCESS_NAME);
        sObj.put('ACCL__Batch_Size__c', 1);
        insert sObj;
    }  
    
    /**
     *  @description This method inserts Account Template record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sobject getDefaultAccountTemplateWithSalesOrg() {
        RecordType rt = [SELECT Id FROM RecordType WHERE sObjectType=:CUSTOMER_TEMPLATE_OBJECT AND DeveloperName=:CUSTOMER_RECORD_TYPE];
        sObject accTemp = allObjMetaType.get('ACCL__Account_Template__c').newSObject();
        accTemp.put('Name', 'TestName');
        accTemp.put('ACCL__Initial_Roles__c', 'customer');
        accTemp.put('ACCL__Active__c', true);
        accTemp.put('RecordTypeId', rt.Id);
        accTemp.put('ACCL__Description_Language_1__c', 'TestName');
        // accTemp.put('ACCL__Sales_Org__c', 'US01');
        insert accTemp;
        return accTemp;
    }
    
    /**
     *  @description This method insert Account record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sobject getDefaultAccountWithSalesOrg() {
        sObject acc = allObjMetaType.get('Account').newSObject();
        acc.put('Name', 'testName');
        acc.put('ACCL__City__c', 'testCity');
        acc.put('ACCL__Street__c', 'testStreet');
        acc.put('ACCL__Name_2__c', 'testName2');
        acc.put('ACCL__Account_Template__c', getDefaultAccountTemplateWithSalesOrg().Id);
        insert acc;
        return acc;
    }

    /**
     *  @description This method insert Account record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sobject getDefaultAccount() {
        sObject acc = allObjMetaType.get('Account').newSObject();
        acc.put('Name', 'testName');
        acc.put('ACCL__City__c', 'testCity');
        acc.put('ACCL__Street__c', 'testStreet');
        acc.put('ACCL__Name_2__c', 'testName2');
        acc.put('ACCL__Name_2__c', 'testName2');
        // acc.put('ACCL__Account_Template__c', 'a0Y4C00000AUyCCUA1'); //Test Fix - Pooja - 10 Sep
        insert acc;
        return acc;
    }
    
    /**
     *  @description This method insert Account record in Bulk.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static List<sobject> insertBulkAccounts(Integer noOfAcc) {
        List<sObject> accList = new List<sObject>();
        for(Integer i=0; i<noOfAcc; i++) {
            sObject acc = allObjMetaType.get('Account').newSObject();
            acc.put('Name', 'testName'+i);
            acc.put('ACCL__City__c', 'testCity');
            acc.put('ACCL__Street__c', 'testStreet');
            acc.put('ACCL__Name_2__c', 'testName2'+i);
            // acc.put('ACCL__Account_Template__c', 'a0Y4C00000AUyCCUA1'); //Test Fix - Pooja - 10 Sep
            accList.add(acc);
        }
        insert accList;
        return accList;
    }

    /**
     *  @description This method insert Account Manager record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultAccountManager() {
        sObject accMan = allObjMetaType.get('ACCL__Account_Manager__c').newSObject();
        accMan.put('ACCL__Account__c', getDefaultAccount().Id);
        accMan.put('ACCL__User__c', UserInfo.getUserId());
        accMan.put('ACCL__Management_Type__c', 'Sales');
        accMan.put('ACCL__Active__c', true);
        accMan.put('ACCL__Valid_From__c', System.today());
        accMan.put('ACCL__Valid_Thru__c', System.today().addDays(50));
        insert accMan;
        return accMan;
    }
    
    /**
     *  @description This method insert Account Manager record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultAccountManager(sObject acc) {
        sObject accMan = allObjMetaType.get('ACCL__Account_Manager__c').newSObject();
        accMan.put('ACCL__Account__c', acc.Id);
        accMan.put('ACCL__User__c', UserInfo.getUserId());
        accMan.put('ACCL__Management_Type__c', 'Sales');
        accMan.put('ACCL__Active__c', true);
        accMan.put('ACCL__Valid_From__c', System.today());
        accMan.put('ACCL__Valid_Thru__c', System.today().addDays(50));
        insert accMan;
        return accMan;
    }
    
    /**
     *  @description This method insert Account Manager record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultAccountManagerWithSalesOrg() {
        sObject accMan = allObjMetaType.get('ACCL__Account_Manager__c').newSObject();
        accMan.put('ACCL__Account__c', getDefaultAccountWithSalesOrg().Id);
        accMan.put('ACCL__User__c', UserInfo.getUserId());
        accMan.put('ACCL__Management_Type__c', 'Sales');
        accMan.put('ACCL__Active__c', true);
        accMan.put('ACCL__Valid_From__c', System.today());
        accMan.put('ACCL__Valid_Thru__c', System.today().addDays(50));
        insert accMan;
        return accMan;
    }
    
    /**
     *  @description This method insert Account Manager record in Bulk.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static List<sObject> insertAccountManagersWithDifferentDates(List<sObject> acc, Date Frm, Date Thru, String managementType, Boolean isMain) {
        List<sObject> accManList = new List<sObject>();
        for(sObject a : acc) {
            sObject accMan = allObjMetaType.get('ACCL__Account_Manager__c').newSObject();
            accMan.put('ACCL__Account__c', a.Id);
            accMan.put('ACCL__User__c', UserInfo.getUserId());
            accMan.put('ACCL__Management_Type__c', managementType);
            accMan.put('ACCL__Active__c', true);
            accMan.put('ACCL__Valid_From__c', Frm);
            accMan.put('ACCL__Valid_Thru__c', Thru);
            accMan.put('ACCL__Main__c', isMain);
            accManList.add(accMan);
        }
        insert accManList;
        return accManList;
    }
    
    /**
     *  @description This method insert Account Manager record in Bulk.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static List<sObject> insertAccountManagersWithDifferentDates(List<sObject> acc, sObject Usr, Date Frm, Date Thru, String managementType, Boolean isMain) {
        List<sObject> accManList = new List<sObject>();
        for(sObject a : acc) {
            sObject accMan = allObjMetaType.get('ACCL__Account_Manager__c').newSObject();
            accMan.put('ACCL__Account__c', a.Id);
            accMan.put('ACCL__User__c', Usr.Id);
            accMan.put('ACCL__Management_Type__c', managementType);
            accMan.put('ACCL__Active__c', true);
            accMan.put('ACCL__Valid_From__c', Frm);
            accMan.put('ACCL__Valid_Thru__c', Thru);
            accMan.put('ACCL__Main__c', isMain);
            accManList.add(accMan);
        }
        insert accManList;
        return accManList;
    }
    
    /**
     *  @description This method insert a non standard Job_Definition_List_Template record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultJobDefinitionListTemplate_NonStandard() {
        sObject jdlt = allObjMetaType.get('ACCL__Job_Definition_List_Template__c').newSObject();
        jdlt.put('ACCL__Description_Language_1__c', 'NonStandard');
        jdlt.put('ACCL__Consider_Account__c', true);
        jdlt.put('ACCL__Standard_Jobs__c', false);
        // jdlt.put('ACCL__Sales_Org__c', 'US01');
        jdlt.put('ACCL__Active__c', true);
        insert jdlt;
        return jdlt;
    }
    
    /**
     *  @description This method insert a Call_Template record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultCallTemplate() {
        sObject ct = allObjMetaType.get('ACCL__Call_Template__c').newSObject();
        ct.put('Name', 'test Call Temp');
        ct.put('ACCL__Description_Language_1__c', 'test desc');
        ct.put('ACCL__Active__c', true);
        ct.put('ACCL__Default_Duration__c', 15);
        ct.put('ACCL__Company_Required__c', 'Mandatory');
        ct.put('ACCL__Creation_Platform__c', 'Both');
        // ct.put('RE_CallTemplate_ExternalID__c', 'TestTemplate_US01');
        // ct.put('ACCL__Sales_Org__c', 'US01');
        insert ct;
        return ct;
    }
        
    /**
     *  @description This method insert a Call record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultCall(sObject ct, sObject acc) {
        sObject c = allObjMetaType.get('ACCL__Call__c').newSObject();
        c.put('ACCL__Subject__c', acc.get('Name')+'-'+ct.get('ACCL__Description__c'));
        c.put('ACCL__Creation_Mode__c', CALL_CREATION_MODE_MANUALLY);
        //c.put('ACCL__Call_Template__c', ct.Id);
        c.put('ACCL__Account__c', acc.Id);
        c.put('ACCL__Start_Date_Time__c', System.now());
        if(ct != null ){
            c.put('ACCL__Call_Template__c', ct.Id);
            c.put('ACCL__End_Date_Time__c', System.now().addMinutes(Integer.valueOf(ct.get('ACCL__Default_Duration__c'))));
        }
        c.put('ACCL__Responsible__c', UserInfo.getUserId());
        c.put('ACCL__Status__c', CALL_STATUS_PLANNED);
        insert c;
        return c;
    }
    
    /**
     *  @description This method insert a Call record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultCall() {
        sObject c = allObjMetaType.get('ACCL__Call__c').newSObject();
        c.put('ACCL__Subject__c', 'test Subject');
        c.put('ACCL__Creation_Mode__c', CALL_CREATION_MODE_MANUALLY);
        c.put('ACCL__Call_Template__c', getDefaultCallTemplate().Id);
        c.put('ACCL__Account__c', getDefaultAccount().Id);
        c.put('ACCL__Start_Date_Time__c', System.now());
        c.put('ACCL__End_Date_Time__c', System.now().addMinutes(Integer.valueOf(getDefaultCallTemplate().get('ACCL__Default_Duration__c'))));
        c.put('ACCL__Responsible__c', UserInfo.getUserId());
        c.put('ACCL__Status__c', CALL_STATUS_PLANNED);
        insert c;
        return c;
    }
    
    /**
     *  @description This method insert a non standard Job_Definition_List record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultJobDefinitionList_NonStandard() {
        sObject jdl = allObjMetaType.get('ACCL__Job_Definition_List__c').newSObject();
        jdl.put('Name', 'test jdl');
        jdl.put('ACCL__Description_Language_1__c', 'test desc');
        jdl.put('ACCL__Active__c', true);
        jdl.put('ACCL__Valid_From__c', Date.today());
        jdl.put('ACCL__Valid_Thru__c', Date.today().addDays(3));
        jdl.put('ACCL__Job_Definition_List_Template__c', getDefaultJobDefinitionListTemplate_NonStandard().Id);
        jdl.put('ACCL__Call_Template__c', getDefaultCallTemplate().Id);
        jdl.put('ACCL__Default_Management_Type__c', 'Sales');
        jdl.put('ACCL__User_Policy__c', 'All');
        insert jdl;
        return jdl;
    }
    
    /**
     *  @description This method insert a non standard Job_Definition_List record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultJobDefinitionList_NonStandard(sObject jdlt, sObject ct) {
        sObject jdl = allObjMetaType.get('ACCL__Job_Definition_List__c').newSObject();
        jdl.put('Name', 'test jdl');
        jdl.put('ACCL__Description_Language_1__c', 'test desc');
        jdl.put('ACCL__Active__c', true);
        jdl.put('ACCL__Valid_From__c', Date.today());
        jdl.put('ACCL__Valid_Thru__c', Date.today().addDays(3));
        jdl.put('ACCL__Job_Definition_List_Template__c', jdlt.Id);
        jdl.put('ACCL__Call_Template__c', ct.Id);
        jdl.put('ACCL__Default_Management_Type__c', 'Sales');
        jdl.put('ACCL__User_Policy__c', 'All');
        insert jdl;
        return jdl;
    }
    
    /**
     *  @description This method insert a non standard Job_Definition_List record in Bulk.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static List<sObject> insertJobDefinitionLists(Integer noOfObj, sObject ct, sObject jdlt, String defManagmentType, String defUserPolicy, Date dateFrom, Date dateTo) {
        List<sObject> jdlList = new List<sObject>();
        for(Integer i=0; i<noOfObj; i++) {
            sObject jdl = allObjMetaType.get('ACCL__Job_Definition_List__c').newSObject();
            jdl.put('Name', 'test jdl'+i);
            jdl.put('ACCL__Description_Language_1__c', 'test desc'+i);
            jdl.put('ACCL__Active__c', true);
            jdl.put('ACCL__Valid_From__c', dateFrom);
            jdl.put('ACCL__Valid_Thru__c', dateTo);
            jdl.put('ACCL__Job_Definition_List_Template__c', jdlt.Id);
            jdl.put('ACCL__Call_Template__c', ct.Id);
            jdl.put('ACCL__Default_Management_Type__c', defManagmentType);
            jdl.put('ACCL__User_Policy__c', defUserPolicy);
            // jdl.put('ACCL__Sales_Org__c', 'US01'); //test fix
            jdlList.add(jdl);
        }
        insert jdlList;
        return jdlList;
    }
    
    /**
     *  @description This method insert a non standard Job_Definition_List_Account record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultJobDefinitionListAccount_NonStandard() {
        sObject jdla = allObjMetaType.get('ACCL__Job_Definition_List_Account__c').newSObject();
        jdla.put('ACCL__Account__c', getDefaultAccount().Id);
        jdla.put('ACCL__Job_Definition_List__c', getDefaultJobDefinitionList_NonStandard().Id);
        // jdla.put('ACCL__Sales_Org__c', 'US01');
        insert jdla;
        return jdla;
    }
    
    /**
     *  @description This method insert a non standard Job_Definition_List_Account record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultJobDefinitionListAccount_NonStandard(sObject acc, sObject jdl) {
        sObject jdla = allObjMetaType.get('ACCL__Job_Definition_List_Account__c').newSObject();
        jdla.put('ACCL__Account__c', acc.Id);
        jdla.put('ACCL__Job_Definition_List__c', jdl.Id);
        insert jdla;
        return jdla;
    }
    
    /**
     *  @description This method insert a non standard Job_List record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultJobList(sObject acc, sObject ct, sObject jdl) {
        sObject jl = allObjMetaType.get('ACCL__Job_List__c').newSObject();
        jl.put('ACCL__Manager__c', UserInfo.getUserId());
        jl.put('ACCL__Account__c', acc.Id);
        jl.put('ACCL__Call_Template__c', ct.Id);
        jl.put('ACCL__Job_Definition_List__c', jdl.Id);
        jl.put('ACCL__Valid_From__c', System.today());
        jl.put('ACCL__Valid_Thru__c', System.today());
        jl.put('ACCL__Done__c', '0');
        insert jl;
        return jl;
    }
    
    /**
     *  @description This method insert a Job_List record in Bulk.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static List<sObject> insertJobLists(List<sObject> managers, sObject ct, List<sObject> jdls, Date dateFrom, Date dateTo) {
        List<sObject> listOfJobList = new List<sObject>();
        for(sObject jdl : jdls ) {
            for(sObject manager : managers) {
                sObject jl = allObjMetaType.get('ACCL__Job_List__c').newSObject();
                jl.put('ACCL__Account__c', manager.get('ACCL__Account__c'));
                jl.put('ACCL__Call_Template__c', ct.Id);
                jl.put('ACCL__Job_Definition_List__c', jdl.Id);
                jl.put('ACCL__Done__c', '0');
                jl.put('ACCL__Valid_From__c', dateFrom);
                jl.put('ACCL__Valid_Thru__c', dateTo);
                jl.put('ACCL__Manager__c', manager.get('ACCL__User__c'));
                listOfJobList.add(jl);
            }
        }
        insert listOfJobList;
        return listOfJobList;
    }
    
    /**
     *  @description This method inserts a User record in Bulk.
     *  @param None
     *  @return User record
     *  @throws None
     */
    public static List<sObject> insertUsers(Integer noOfUser) {
        Profile pro = [SELECT Id FROM Profile WHERE Name='System Administrator' LIMIT 1];
        User loggedInUser = [SELECT TimeZoneSidKey FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
        List<sObject> userList = new List<sObject>();
        for(Integer i=0; i<noOfUser; i++) {
            sObject u = allObjMetaType.get('User').newSObject();
            u.put('FirstName', 'Joan'+i);
            u.put('LastName', 'Of Arc'+i);
            u.put('Email', 'joan'+i+'@arc.com');
            u.put('Alias', 'arcjoan'+i);
            u.put('Username', 'joanarc'+i+'@france.com');
            u.put('LocaleSidKey', 'en_US');
            u.put('TimeZoneSidKey', loggedInUser.TimeZoneSidKey);
            u.put('ProfileID', pro.Id);
            u.put('LanguageLocaleKey', 'en_US');
            u.put('EmailEncodingKey', 'UTF-8');
            // u.put('ACCL__Sales_Org__c','US01'); //Test fix - Pooja - 10 Sep
            userList.add(u);
        }
        insert userList;
        return userList;
    }
    
    /**
     *  @description This method insert a Account_Set record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultAccountSet() {
        sObject accset = allObjMetaType.get('ACCL__Account_Set__c').newSObject();
        accset.put('ACCL__Description_Language_1__c', 'test Desc');
        insert accset;
        return accset;
    }
    
    /**
     *  @description This method insert a Account_Set_Account record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultAccountSetAccount(sObject accSet, sObject acc) {
        sObject accsetacc = allObjMetaType.get('ACCL__Account_Set_Account__c').newSObject();
        accsetacc.put('ACCL__Account_Set__c', accSet.Id);
        accsetacc.put('ACCL__Account_Set_Account__c', acc.Id);
        insert accsetacc;
        return accsetacc;
    }
    
    /**
     *  @description This method insert a Job_Definition_List_Account_Set record.
     *  @param None
     *  @return sObject
     *  @throws None
     */
    public static sObject getDefaultJobDefinitionListAccountSet(sObject jdl, sObject accSet) {
        sObject jdlas = allObjMetaType.get('ACCL__Job_Definition_List_Account_Set__c').newSObject();
        jdlas.put('ACCL__Account_Set__c', accSet.Id);
        jdlas.put('ACCL__Job_Definition_List__c', jdl.Id);
        insert jdlas;
        return jdlas;
    }
}