src/objects/ACCL__Org_Unit__c.object
<CustomObject>
    <description>Holds the details of the organization unit object, defining a manufacturer´s organizational structure.</description>
    <label>Org Unit</label>
    <nameField>
        <label>Org Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Org_Unit_User__c.object
<CustomObject>
    <description>Holds the details of the relationship between organization unit and user.</description>
    <fields>
        <fullName>ACCL__Org_Unit__c</fullName>
        <description>Reference to an org unit assigned to a user.</description>
        <label>Org Unit</label>
        <lookupFilter>
            <active>false</active>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Org_Unit__c</referenceTo>
        <relationshipLabel>Org Unit Users</relationshipLabel>
        <relationshipName>Org_Unit_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Org Unit User</label>
    <nameField>
        <displayFormat>OUU-{0000}</displayFormat>
        <label>Org Unit User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Unit Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MDLZ_UpdateOrgUnitUserValidityTest.cls
/***************************************************************
Name: MDLZ_UpdateOrgUnitUserValidityTest
======================================================
Purpose:
Test Factory for MDLZ_ProdAssortment_ByCustBranchBatch
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0      Priya Tubachi                03/30/2022     Initial Development    

***************************************************************/

@isTest
private class MDLZ_UpdateOrgUnitUserValidityTest {
    
    private MDLZ_UpdateOrgUnitUserValidityTest(){
        
    }
    static testMethod void updateOrgUnitUserValidity(){
        
        
        User u = MDLZ_UpdateOrgUnitUserValidityTestFctry.createUser();
        ACCL__Org_Unit__c orgun1 = MDLZ_UpdateOrgUnitUserValidityTestFctry.insertOrgUnit();
        ACCL__Org_Unit_User__c orgusr = MDLZ_UpdateOrgUnitUserValidityTestFctry.insertOrgUnitUser(orgun1,u);
        
        Test.startTest();
        Database.BatchableContext BC = null;
        SchedulableContext sc2 = null;
        //MDLZ_UpdateOrgUnitUserValidity pr = new MDLZ_UpdateOrgUnitUserValidity();
        //pr.updateUserValidity(new List<User> {u});
        
        MDLZ_UpdateOrgUnitUserValidityBatch bt = new MDLZ_UpdateOrgUnitUserValidityBatch(10);
        bt.execute(sc2);
        bt.execute(BC,new List<User> {u});
       
        Test.stopTest();
        
        
    }
    
}