src/objects/ACCL__Order__c.object
<CustomObject>
    <description>Holds the header details of the order entry.</description>
    <fields>
        <fullName>ACCL__Delivery_Date__c</fullName>
        <description>By default next day.Delivery date calculation is
			customized very often.</description>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Document_Type__c</fullName>
        <description>Specifies the type of the order document in order to distinguish DSD and non-DSD order entries.</description>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>ProductCheckIn</fullName>
                </value>
                <value>
                    <fullName>ProductCheckOut</fullName>
                </value>
                <value>
                    <fullName>TruckAudit</fullName>
                </value>
                <value>
                    <fullName>CashCheckIn</fullName>
                </value>
                <value>
                    <fullName>CashCheckOut</fullName>
                </value>
                <value>
                    <fullName>OrderEntry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Order_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to capture customer for which Order is
			created</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Customer)</relationshipLabel>
        <relationshipName>Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Order Template for Order Entry</description>
        <label>Order Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Order_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Order_Template__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Workflow neutral description of the order Entry status.</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Send to SAP</fullName>
                    <label>Sent to SAP</label>
                </value>
                <value>
                    <fullName>Received By SAP</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Routed</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MDLZ_isChanged__c</fullName>
        <description>Functionality introduced for RDT pilot for Order Redesign to address following defects:
MRELKXIW-1925, MRELKXIW-1912, MRELKXIW-1918</description>
        <label>IsChanged</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FALSE</fullName>
                    <default>true</default>
                    <label>FALSE</label>
                </value>
                <value>
                    <fullName>TRUE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Order_Template__c.object
<CustomObject>
    <description>Template which controls the behaviour of a sales document.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>The attribute used to enable or disable the current template.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Document_Type__c</fullName>
        <description>Specifies how to handle a sales document regarding payments.</description>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CashCheckIn</fullName>
                </value>
                <value>
                    <fullName>CashCheckOut</fullName>
                </value>
                <value>
                    <fullName>OrderEntry</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>ProductCheckOut</fullName>
                </value>
                <value>
                    <fullName>ProductCheckIn</fullName>
                </value>
                <value>
                    <fullName>TruckAudit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the order template belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RE_Order_Template_ExternalID__c</fullName>
        <description>It contains unique value for external ID</description>
        <externalId>true</externalId>
        <label>RE_Order_Template_ExternalID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Order Template</label>
    <nameField>
        <label>Order Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Account_Number__c</fullName>
        <description>Customer Number.</description>
        <label>Customer Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer belongs to.</description>
        <formula>Text(ACCL__Account_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MDLZ_WOForceSAPTestClass.cls
@isTest
private class MDLZ_WOForceSAPTestClass {
    
    static testMethod void mdlzOrderReject(){
        
        System.assertEquals(MDLZ_ConstantHelper.PhaseSentToSAP,'Send to SAP');
        System.assertEquals(MDLZ_ConstantHelper.PhaseRejected,'Rejected');
        System.assertEquals(MDLZ_ConstantHelper.ReceivedBySAP,'Received By SAP');
        System.assertEquals(MDLZ_ConstantHelper.ChangeTrue,'TRUE');
        System.assertEquals(MDLZ_ConstantHelper.ChangeFalse,'FALSE');        
        Account acct = new Account();
        acct.Name ='Mondelez Test Account';
        acct.ACCL__Account_Number__c='Demo Unique123';
        acct.Description ='Test Description';
        
        insert acct;
        
        ACCL__Order_Template__c ordertempEdi = new ACCL__Order_Template__c(Name ='EDI',
                                                                           RecordTypeId =Schema.SObjectType.ACCL__Order_Template__c.getRecordTypeInfosByName().get('Order Entry').getRecordTypeId(),
                                                                           ACCL__Document_Type__c='Order Entry',ACCL__Valid_Thru__c=system.today()+365,
                                                                           ACCL__Valid_From__c=system.today(),RE_Order_Template_ExternalID__c='EDI_US01',
                                                                           ACCL__Sales_Org__c='US01',ACCL__Active__c=true);
        
        insert ordertempEdi;
        
        list<ACCL__Order__c>Ordlist=new list<ACCL__Order__c>();
        for(integer i = 0; i < 10; i++) {
            ACCL__Order__c ord = new ACCL__Order__c();
            ord.ACCL__Phase__c ='Send to SAP';
            ord.ACCL__Delivery_Date__c =System.today()+i;
            ord.ACCL__Order_Account__c =acct.Id;
            ord.MDLZ_isChanged__c =MDLZ_ConstantHelper.ChangeFalse;
            ord.ACCL__Order_Template__c =ordertempEdi.Id;
            Ordlist.add(ord);
        }
        insert Ordlist;
        Ordlist =[Select Id, name,ACCL__Phase__c from ACCL__Order__c where Id =:Ordlist[0].Id];
        Ordlist[0].ACCL__Phase__c = MDLZ_ConstantHelper.ReceivedBySAP;
        update Ordlist;
        
        Test.startTest();
        MDLZ_WOForceSAPReceivedBatch batch = new MDLZ_WOForceSAPReceivedBatch(200);
        Database.executeBatch(batch);
        Database.QueryLocator ql = batch.start(null);
        batch.execute(null,Ordlist);
        batch.Finish(null);
        
        Test.stopTest();
        
    }
}