src/objects/ACCL__Account_Set__c.object
<CustomObject>
    <description>Object for the creation of Customer Sets.</description>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds Description in Language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer set belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Customer Set</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Account_Set_Account__c.object
<CustomObject>
    <description>Junction object between Customer and Customer Set.</description>
    <fields>
        <fullName>ACCL__Account_Set_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Set Customers (Customer)</relationshipLabel>
        <relationshipName>Account_Set_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Account_Set__c</fullName>
        <description>Reference to Customer Set.</description>
        <label>Customer Set</label>
        <referenceTo>ACCL__Account_Set__c</referenceTo>
        <relationshipLabel>Customer Set Customers</relationshipLabel>
        <relationshipName>Account_Set_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Set Customer</label>
    <nameField>
        <displayFormat>ASA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Set Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Sales_Folder__c.object
<CustomObject>
    <description>This object contains the attributes associated with the Sales Folder.</description>
    <fields>
        <fullName>ACCL__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the customer.</description>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ACCL__Sales_Org__c</field>
                <operation>equals</operation>
                <valueField>Account.ACCL__Sales_Org__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Folders</relationshipLabel>
        <relationshipName>Sales_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active flag.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds the description of language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Folder_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Sales Folder Template</description>
        <label>Sales Folder Template</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>No matches found or Sales Folder Template is not active.</errorMessage>
            <filterItems>
                <field>ACCL__Sales_Folder_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Sales_Folder_Template__c</referenceTo>
        <relationshipLabel>Sales Folders</relationshipLabel>
        <relationshipName>Sales_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the sales folder belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <description>First date of validity period of the sales folder.</description>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <description>Last date of validity period of the sales folder.</description>
        <label>Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MDLZ_Customer_Sets__c</fullName>
        <label>Customer Sets</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MDLZ_Parent_RecordId__c</fullName>
        <label>Parent RecordId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Sales Folder</label>
    <nameField>
        <label>Sales Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Folders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Sales_Folder_Sell_Sheet__c.object
<CustomObject>
    <description>The object holds the details of the relationship between sales folder and sell sheet.</description>
    <fields>
        <fullName>ACCL__Sales_Folder__c</fullName>
        <description>Reference to the Sales Folder.</description>
        <label>Sales Folder</label>
        <referenceTo>ACCL__Sales_Folder__c</referenceTo>
        <relationshipLabel>Sell Sheets</relationshipLabel>
        <relationshipName>Sales_Folder_Sell_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the sales folder sell sheet belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sell_Sheet__c</fullName>
        <description>Reference to the Sell Sheet.</description>
        <label>Sell Sheet</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Sell_Sheet__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.ACCL__Sales_Org__c</field>
                <operation>equals</operation>
                <valueField>ACCL__Sell_Sheet__c.ACCL__Sales_Org__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Sell_Sheet__c</referenceTo>
        <relationshipLabel>Sales Folder Sell Sheets</relationshipLabel>
        <relationshipName>Sales_Folder_Sell_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Folder Sell Sheet</label>
    <nameField>
        <displayFormat>SFS-{00000000}</displayFormat>
        <label>Sales Folder Sell Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Folder Sell Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Sell_Sheet__c.object
<CustomObject>
    <description>This object contains the attributes associated with the sell sheet to be used on the sales folder.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Active flag.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds the description of language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the sell sheet belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Sell Sheet</label>
    <nameField>
        <label>Sell Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sell Sheets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Account_Number__c</fullName>
        <description>Customer Number.</description>
        <label>Customer Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ACCL__Account_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to customer template.</description>
        <label>Customer Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Account_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Account_Template__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer belongs to.</description>
        <formula>Text(ACCL__Account_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MDLZ_CustomersetPicklistTestclass.cls
/***************************************************************
Name: MDLZ_CustomersetPicklistTestclass
======================================================
Purpose:
a.Fetch all the customer set description and add to custom multiselect picklist datatype
b.Based On the selection of picklist value create records and shellsheets
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL                 Description
1.0         Bharath_V                    08/17/2021     Initial Development    Test Class for MDLZ_CustomersetPicklist class  

***************************************************************/
@isTest
private class MDLZ_CustomersetPicklistTestclass {
    
    static testMethod void testClass(){
        
        ACCL__Sales_Folder_Template__c salestemp = new ACCL__Sales_Folder_Template__c();
        salestemp.Name = 'Customer Salesfolder Template';
        salestemp.ACCL__Anchor_Type__c ='Customer';
        salestemp.ACCL__Description_Language_1__c ='Test data';
        salestemp.ACCL__Sales_Org__c ='US01';
        salestemp.ACCL__Active__c = true;
       Database.insert(salestemp,false);
      
        
        ACCL__Sales_Folder__c custset = new ACCL__Sales_Folder__c(Name ='Salesdemo',ACCL__Sales_Org__c ='US01',
                                                                  ACCL__Sales_Folder_Template__c=salestemp.id,ACCL__Active__c=true,MDLZ_Unique_Name__c ='ASA-00000004' );
        
       Database.insert(custset,false);
        ACCL__Account_Template__c acctemp = new ACCL__Account_Template__c();
        acctemp.Name ='Customer Template';
        acctemp.ACCL__Initial_Roles__c ='Customer';
        acctemp.ACCL__Sales_Org__c='US01';
        acctemp.ACCL__Active__c =true;
        acctemp.ACCL__Description_Language_1__c='Test Data';
        acctemp.RecordTypeId =Schema.SObjectType.ACCL__Account_Template__c.getRecordTypeInfosByName().
            get('Customer').getRecordTypeId();
         Database.insert(acctemp,false);
     System.assertEquals('US01', acctemp.ACCL__Sales_Org__c);
        Account acct = new Account();
        acct.Name ='Demo Account';
        acct.ACCL__Account_Number__c='Demo Unique123';
        acct.Description ='Test Descr';
        acct.ACCL__Account_Template__c =acctemp.id;
        Database.insert(acct,false);
        System.assertNotEquals('US01', acct.ACCL__Sales_Org__c);
     
        
        ACCL__Account_Set__c custsets = new ACCL__Account_Set__c();
        custsets.ACCL__Description_Language_1__c ='Mondelez Description';
        custsets.ACCL__Sales_Org__c ='US01';
       Database.insert(custsets,false);
        System.assertEquals('US01', custsets.ACCL__Sales_Org__c);
       
        ACCL__Account_Set_Account__c custsetaccount = new ACCL__Account_Set_Account__c();
        custsetaccount.ACCL__Account_Set_Account__c = acct.Id;
        custsetaccount.ACCL__Account_Set__c =custsets.Id;
       Database.insert(custsetaccount,false);
       
        ACCL__Sales_Folder__c salesfold = new ACCL__Sales_Folder__c(); 
        salesfold.Name='Salesfolder Name';
        salesfold.ACCL__Active__c =true;
        salesfold.ACCL__Sales_Folder_Template__c=salestemp.Id;
        salesfold.ACCL__Description_Language_1__c ='Test Demo';
        salesfold.ACCL__Sales_Org__c=salestemp.ACCL__Sales_Org__c;
        salesfold.ACCL__Valid_From__c=system.today();
        salesfold.ACCL__Valid_Thru__c=system.today()+5;
        salesfold.ACCL__Account__c =acct.id;
        salesfold.MDLZ_Customer_Sets__c='Test Customer';
        salesfold.MDLZ_Parent_RecordId__c=custset.Id;
        salesfold.MDLZ_Unique_Name__c =custset.MDLZ_Unique_Name__c; 
        Database.insert(salesfold,false);
        
        
        ACCL__Sell_Sheet__c sellsheet = new ACCL__Sell_Sheet__c();
        sellsheet.Name = 'Sell Sheet Demo';
        sellsheet.ACCL__Active__c =true;
        sellsheet.ACCL__Description_Language_1__c ='SellSheet Test';
        sellsheet.ACCL__Sales_Org__c = custset.ACCL__Sales_Org__c;
        Database.insert(sellsheet,false);
        
        ACCL__Sales_Folder_Sell_Sheet__c salesfoldsell = new ACCL__Sales_Folder_Sell_Sheet__c();
        salesfoldsell.ACCL__Sales_Folder__c =custset.Id;
        salesfoldsell.ACCL__Sales_Org__c = custset.ACCL__Sales_Org__c;
        salesfoldsell.ACCL__Sell_Sheet__c =sellsheet.id;
        Database.insert(salesfoldsell,false);
       
        PageReference pageRef = Page.MDLZ_CustomersetPicklist;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(custset.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(custset);
        MDLZ_CustomersetPicklist controller = new MDLZ_CustomersetPicklist(sc);
        controller.selectedPicklistValues = new List<String>{'Mondelez Description','Mondelez Description-2'};
            
            Test.startTest(); 
        List<SelectOption> options = controller.getCustomerSets();
        System.debug('options' + options);
        controller.save();
        controller.getmyID();
        controller.doFinish(); 
        controller.reset();
        Test.stopTest();
        
    }
}