src/objects/ACCL__Order__c.object
<CustomObject>
    <description>Holds the header details of the order entry.</description>
    <fields>
        <fullName>ACCL__Delivery_Date__c</fullName>
        <description>By default next day.Delivery date calculation is
			customized very often.</description>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to capture customer for which Order is
			created</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Customer)</relationshipLabel>
        <relationshipName>Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Order Template for Order Entry</description>
        <label>Order Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Order_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Order_Template__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Workflow neutral description of the order Entry status.</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Send to SAP</fullName>
                    <label>Sent to SAP</label>
                </value>
                <value>
                    <fullName>Received By SAP</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Routed</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MDLZ_Total_Case_Quantity__c</fullName>
        <description>Sum of case quantity of all products in the order item</description>
        <label>Total Case Quantity</label>
        <summarizedField>ACCL__Order_Item__c.ACCL__Quantity__c</summarizedField>
        <summaryForeignKey>ACCL__Order_Item__c.ACCL__Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Order_Template__c.object
<CustomObject>
    <description>Template which controls the behaviour of a sales document.</description>
    <label>Order Template</label>
    <nameField>
        <label>Order Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_UpdateNOSEDIOrdersBatch.cls
/***************************************************************
Name: MDLZ_UpdateNOSEDIOrdersBatch
======================================================
Purpose:
a. batch1 to update NOS and EDI orders to Routed or cancelled 
	refer conditions in confluence matrix.
======================================================
History
-------
VERSION     AUTHOR         REVIWER      DATE             DETAIL              Description
1.0      Bharath Vikkurthi            18/09/2021     Initial Development    

***************************************************************/

global with sharing class MDLZ_UpdateNOSEDIOrdersBatch implements Database.Batchable< sObject >,Schedulable {
    global   Database.QueryLocator start(Database.BatchableContext BC)    
    {
        
        //Date  systemYesterday =System.Today();
        
        //Retrieve list of orders with order template as EDI and NOS for the current day
            String query = 'SELECT Id, ACCL__Delivery_Date__c,ACCL__Order_Account__c, ACCL__Order_Template__r.Name,ACCL__Phase__C, '+
            'MDLZ_Total_Case_Quantity__c FROM ACCL__Order__c WHERE ACCL__Delivery_Date__c >= today and ACCL__Delivery_Date__c <= tomorrow '+
            'and ACCL__Order_Template__r.Name in (\'NOS\',\'EDI\') and ACCL__Phase__c in (\'Received By SAP\',\'Send to SAP\',\'Locked\')';
        //String query = 'SELECT Id from Account';
        system.debug('query '+query);
        return Database.getQueryLocator(query);
        
    }
    
    global void execute(Database.BatchableContext BC, List<sobject> orderList)
    {
       // new MDLZ_OrderConsolidation().updateNOSEDIOrders(orderList); 
    }
   
    global void execute(SchedulableContext ctx) {
        Database.executeBatch(new MDLZ_UpdateNOSEDIOrdersBatch(), 500);   
    }
    
    global void finish(Database.BatchableContext BC)
    {
      // Query the AsyncApexJob object to retrieve the current job's information.
AsyncApexJob details = [SELECT Id, Status,ExtendedStatus, NumberOfErrors, JobItemsProcessed,TotalJobItems, 
                        CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        System.debug('Batch Process Details' +details);   
    }
}