src/objects/ACCL__Account_Extension__c.object
<CustomObject>
    <description>Object to record account roles and further product related attributes.</description>
    <fields>
        <fullName>ACCL__Account__c</fullName>
        <description>Reference to the customer to which the extension record is assigned.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Extensions</relationshipLabel>
        <relationshipName>Account_Extensions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Bill_To_Role_Valid_From__c</fullName>
        <description>From this date on the Bill To Role is valid.</description>
        <label>Bill To Role Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Bill_To_Role_Valid_Thru__c</fullName>
        <description>Until this date the Bill To Role is valid.</description>
        <label>Bill To Role Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Broker_Role_Valid_From__c</fullName>
        <description>From this date on the Broker Role is valid.</description>
        <label>Broker Role Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Broker_Role_Valid_Thru__c</fullName>
        <description>Until this date the Broker Role is valid.</description>
        <label>Broker Role Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Customer_Role_Valid_From__c</fullName>
        <description>From this date on the Customer Role is valid.</description>
        <label>Customer Role Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Customer_Role_Valid_Thru__c</fullName>
        <description>Until this date the Customer Role is valid.</description>
        <label>Customer Role Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Delivery_Role_Valid_From__c</fullName>
        <description>From this date on the Delivery Role is valid.</description>
        <label>Delivery Role Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Delivery_Role_Valid_Thru__c</fullName>
        <description>Until this date the Delivery Role is valid.</description>
        <label>Delivery Role Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Fund_Role_Valid_From__c</fullName>
        <description>From this date on the Fund Role is valid.</description>
        <label>Fund Role Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Fund_Role_Valid_Thru__c</fullName>
        <description>Until this date the Fund Role is valid.</description>
        <label>Fund Role Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Role_Valid_From__c</fullName>
        <description>From this date on the Order Role is valid.</description>
        <label>Order Role Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Role_Valid_Thru__c</fullName>
        <description>Until this date the Order Role is valid.</description>
        <label>Order Role Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Payer_Role_Valid_From__c</fullName>
        <description>From this date on the Payer Role is valid.</description>
        <label>Payer Role Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Payer_Role_Valid_Thru__c</fullName>
        <description>Until this date the Payer Role is valid.</description>
        <label>Payer Role Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Promotion_Valid_From__c</fullName>
        <description>From this date on the Promotion Role is valid.</description>
        <label>Promotion Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Promotion_Valid_Thru__c</fullName>
        <description>Until this date the Promotion Role is valid.</description>
        <label>Promotion Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Store_Role_Valid_From__c</fullName>
        <description>From this date on the Store Role is valid.</description>
        <label>Store Role Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Store_Role_Valid_Thru__c</fullName>
        <description>Until this date the Store Role is valid.</description>
        <label>Store Role Valid Thru</label>
        <type>Date</type>
    </fields>
    <label>Customer Extension</label>
    <nameField>
        <displayFormat>AEX-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AddOnAccountExtensionTestFactory.cls
@isTest
public class AddOnAccountExtensionTestFactory {
      public static ACCL__Account_Extension__c buildAccountExtension(
    Account account,
    Date fundValidFrom,
    Date fundValidThru,
    Date billToValidFrom,
    Date billToValidThru,
    Date brokerRoleValidFrom,
    Date brokerRoleValidThru,
    Date customerValidFrom,
    Date customerValidThru,
    Date deliveryRoleValidFrom,
    Date deliveryRoleValidThru,
    Date orderRoleValidFrom,
    Date orderRoleValidThru,
    Date payerRoleValidFrom,
    Date payerRoleValidThru,
    Date storeRoleValidFrom,
    Date storeRoleValidThru,
    Date promotionValidFrom,
    Date promotionValidThru
  ) {
    ACCL__Account_Extension__c accountExtensionRecord = new ACCL__Account_Extension__c();
    accountExtensionRecord.ACCL__Account__c = account.id;
    accountExtensionRecord.ACCL__Fund_Role_Valid_From__c = fundValidFrom;
    accountExtensionRecord.ACCL__Fund_Role_Valid_Thru__c = fundValidThru;
    accountExtensionRecord.ACCL__Bill_To_Role_Valid_From__c = billToValidFrom;
    accountExtensionRecord.ACCL__Bill_To_Role_Valid_Thru__c = billToValidThru;
    accountExtensionRecord.ACCL__Broker_Role_Valid_From__c = brokerRoleValidFrom;
    accountExtensionRecord.ACCL__Broker_Role_Valid_Thru__c = brokerRoleValidThru;
    accountExtensionRecord.ACCL__Customer_Role_Valid_From__c = customerValidFrom;
    accountExtensionRecord.ACCL__Customer_Role_Valid_Thru__c = customerValidThru;
    accountExtensionRecord.ACCL__Delivery_Role_Valid_From__c = deliveryRoleValidFrom;
    accountExtensionRecord.ACCL__Delivery_Role_Valid_Thru__c = deliveryRoleValidThru;
    accountExtensionRecord.ACCL__Order_Role_Valid_From__c = orderRoleValidFrom;
    accountExtensionRecord.ACCL__Order_Role_Valid_Thru__c = orderRoleValidThru;
    accountExtensionRecord.ACCL__Payer_Role_Valid_From__c = payerRoleValidFrom;
    accountExtensionRecord.ACCL__Payer_Role_Valid_Thru__c = payerRoleValidThru;
    accountExtensionRecord.ACCL__Promotion_Valid_From__c = promotionValidFrom;
    accountExtensionRecord.ACCL__Promotion_Valid_Thru__c = promotionValidThru;
    accountExtensionRecord.ACCL__Store_Role_Valid_From__c = storeRoleValidFrom;
    accountExtensionRecord.ACCL__Store_Role_Valid_Thru__c = storeRoleValidThru;

    return accountExtensionRecord;
  }

}