src/objects/ACCL__Account_Set__c.object
<CustomObject>
    <description>Object for the creation of Customer Sets.</description>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds Description in Language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer set belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Customer Set</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Account_Set_Account__c.object
<CustomObject>
    <description>Junction object between Customer and Customer Set.</description>
    <fields>
        <fullName>ACCL__Account_Set_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Set Customers (Customer)</relationshipLabel>
        <relationshipName>Account_Set_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Account_Set__c</fullName>
        <description>Reference to Customer Set.</description>
        <label>Customer Set</label>
        <referenceTo>ACCL__Account_Set__c</referenceTo>
        <relationshipLabel>Customer Set Customers</relationshipLabel>
        <relationshipName>Account_Set_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Set Customer</label>
    <nameField>
        <displayFormat>ASA-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Set Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Product__c.object
<CustomObject>
    <description>This object records the attributes of a product.</description>
	<fields>
        <fullName>MDLZ_PPG__c</fullName>
        <description>Stores the planning PPG for product</description>
        <label>PPG</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_SubPPG__c</fullName>
        <description>Stores the sub PPG for product</description>
        <label>Sub PPG</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the product belongs to.</description>
        <formula>TEXT(ACCL__Product_Template__r.ACCL__Sales_Org__c)</formula>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <label>Product</label>
	 <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Promotion__c.object
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Decides whether a promotion is available.</description>
        <inlineHelpText>Defines if the promotion is considered in the Trade Calendar and the Account Plan.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Anchor_Account_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer Set</description>
        <label>Anchor Customer Set</label>
        <referenceTo>ACCL__Account_Set__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_From__c</fullName>
        <description>Promotion date from</description>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_Thru__c</fullName>
        <description>Promotion date thru</description>
        <label>Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Phase of the promotion</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Preparation</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Modeling</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                    <default>true</default>
                    <label>Committed</label>
                </value>
                <value>
                    <fullName>ForApproval</fullName>
                    <label>For Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Promotion_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to promotion template.</description>
        <label>Promotion Template</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>ACCL__Promotion_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Promotion_Template__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <formula>TEXT (ACCL__Promotion_Template__r.ACCL__Sales_Org__c)</formula>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Slogan_Language_1__c</fullName>
        <description>Holds the slogan in language 1.</description>
        <label>Slogan Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Tactic__c.object
<CustomObject>
    <description>Relation from a Promotion and Tactic.</description>
    <fields>
        <fullName>ACCL__Date_From__c</fullName>
        <description>Start date of a tactic</description>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_Thru__c</fullName>
        <description>End date of a tactic</description>
        <label>Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Included__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Defines if a tactic is included in a promotion</description>
        <label>Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Promotion__c</fullName>
        <description>Reference to the promotion</description>
        <label>Promotion</label>
        <referenceTo>ACCL__Promotion__c</referenceTo>
        <relationshipLabel>Tactics</relationshipLabel>
        <relationshipName>Tactics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <formula>TEXT(ACCL__Tactic_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <label>Tactic</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tactic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tactics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Tactic_Product__c.object
<CustomObject>
    <description>Junction Object between Tactic and Product</description>
    <fields>
        <fullName>ACCL__Included__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Product__c</fullName>
        <label>Product</label>
        <referenceTo>ACCL__Product__c</referenceTo>
        <relationshipLabel>Tactic Products</relationshipLabel>
        <relationshipName>Tactic_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <formula>ACCL__Product__r.ACCL__Sales_Org__c</formula>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Tactic__c</fullName>
        <label>Tactic</label>
        <referenceTo>ACCL__Tactic__c</referenceTo>
        <relationshipLabel>Tactic Products</relationshipLabel>
        <relationshipName>Tactic_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>MDLZ_Location__c</fullName>
        <description>Stores the location for Tactic product</description>
        <label>Location</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_PPG__c</fullName>
        <description>Stores the PPG for Tactic product</description>
        <label>PPG</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_Price__c</fullName>
        <description>Stores the price for Tactic product</description>
        <label>SRP</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MDLZ_SubPPG__c</fullName>
        <description>Stores the Sub PPG for Tactic product</description>
        <label>Sub PPG</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Tactic Product</label>
    <nameField>
        <displayFormat>TP-{00000000}</displayFormat>
        <label>Tactic Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tactic Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MDLZ_Ad_Break_Day__c</fullName>
        <defaultValue>&quot;Sunday&quot;</defaultValue>
        <label>Ad-Break Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer belongs to.</description>
        <formula>Text(ACCL__Account_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MDLZ_Promotion_Store__c.object
<CustomObject>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>ACCL__Promotion__c</referenceTo>
        <relationshipLabel>Promotion Stores</relationshipLabel>
        <relationshipName>MDLZ_Promotion_Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotion Stores</relationshipLabel>
        <relationshipName>MDLZ_Promotion_Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion Store</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>MDLZ_Promotion_Store Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_PromotionExportBatchTest.cls
/***************************************************************
Name: MDLZ_PromotionExportBatchTest
======================================================
Purpose:
Test class for MDLZ_PromotionExportBatch class
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0      Jinal Desai                  09/22/2022     Initial Development

***************************************************************/
@isTest
private class MDLZ_PromotionExportBatchTest {
    
     @testSetup static void dataCreation(){
                
       List<ACCL__Promotion_Template__c> newPromotionTemplateList = new List<ACCL__Promotion_Template__c>(); 
        
       ACCL__Promotion_Template__c promoFandDScriptedTemplate= new ACCL__Promotion_Template__c(Name='F&D Scripted', ACCL__Promotion_Type__c='SellablePromotion',
                                                                                   ACCL__Sales_Org__c='US01',ACCL__Description_Language_1__c='F&D Scripted',
                                                                                   ACCL__Product_Definition_Level__c='Tactic' ,ACCL__UI_Type__c='StandardUI');
        newPromotionTemplateList.add(promoFandDScriptedTemplate);
        
        ACCL__Promotion_Template__c promoFandDNonScriptedTemplate= new ACCL__Promotion_Template__c(Name='F&D Non Scripted', ACCL__Promotion_Type__c='SellablePromotion',
                                                                                   ACCL__Sales_Org__c='US01',ACCL__Description_Language_1__c='F&D Non Scripted',
                                                                                   ACCL__Product_Definition_Level__c='Tactic' ,ACCL__UI_Type__c='StandardUI');
        newPromotionTemplateList.add(promoFandDNonScriptedTemplate);
        
        ACCL__Promotion_Template__c promoTemplate= new ACCL__Promotion_Template__c(Name='Sellable Promotion Test', ACCL__Promotion_Type__c='SellablePromotion',
                                                                                   ACCL__Sales_Org__c='US01',ACCL__Description_Language_1__c='Sellable Promotion Test',
                                                                                   ACCL__Product_Definition_Level__c='Tactic' ,ACCL__UI_Type__c='StandardUI');
        
        newPromotionTemplateList.add(promoTemplate);
        
        if(newPromotionTemplateList.size() > 0){
            Database.Insert(newPromotionTemplateList,false);
        }
        
        system.assertEquals(3,newPromotionTemplateList.size());
        
         List<ACCL__Promotion_Template__c> promotionTemplateList = [Select Id from ACCL__Promotion_Template__c];
      
         // accountList for Customer Set Customer
        List<Account> accountList = MDLZ_TestDataFactory.insertAccount(6,true);
        
        accountList[0].MDLZ_Ad_Break_Day__c = 'Monday';
        accountList[1].MDLZ_Ad_Break_Day__c = 'Tuesday';
        accountList[2].MDLZ_Ad_Break_Day__c = 'Wednesday';
        accountList[3].MDLZ_Ad_Break_Day__c = 'Thursday';
        accountList[4].MDLZ_Ad_Break_Day__c = 'Friday';
        accountList[5].MDLZ_Ad_Break_Day__c = 'Saturday';
        
        Database.Update(accountList,false);
                
        // Customer Set 
        List<ACCL__Account_Set__c> customerSetList = MDLZ_TestDataFactory.insertCustomerSetList(1,true);
        
        // Customer Set Customers
        List<ACCL__Account_Set_Account__c> customerSetCustomerList = new List<ACCL__Account_Set_Account__c>();
        
        for(Integer i=0 ; i<accountList.size();i++){
            ACCL__Account_Set_Account__c customerSetCust = new ACCL__Account_Set_Account__c();
            customerSetCust.ACCL__Account_Set_Account__c = accountList[i].id;
            customerSetCust.ACCL__Account_Set__c = customerSetList[0].Id;
            customerSetCustomerList.add(customerSetCust);
        }
        
        if(customerSetCustomerList.size() > 0){
            Insert customerSetCustomerList;
        }
                
        List<ACCL__Promotion__c> promotionWithTacticList = new List<ACCL__Promotion__c>();
        
        ACCL__Promotion__c promotion1 = new ACCL__Promotion__c();
        promotion1.ACCL__Promotion_Template__c = promotionTemplateList[0].Id;
        promotion1.ACCL__Date_From__c= Date.Today();
        promotion1.ACCL__Date_Thru__c= Date.Today().addDays(60);
        promotion1.ACCL__Anchor_Account_Set__c = customerSetList[0].Id;
        promotion1.ACCL__Slogan_Language_1__c='Test Promotion 1';
        promotion1.ACCL__Active__c=True;
        promotion1.ACCL__Phase__c='Committed';
        promotionWithTacticList.add(promotion1);    
        
        ACCL__Promotion__c promotion2 = new ACCL__Promotion__c();
        promotion2.ACCL__Promotion_Template__c = promotionTemplateList[1].Id;
        promotion2.ACCL__Date_From__c= Date.Today();
        promotion2.ACCL__Date_Thru__c= Date.Today().addDays(60);
        promotion2.ACCL__Anchor_Account_Set__c = customerSetList[0].Id;
        promotion2.ACCL__Slogan_Language_1__c='Test Promotion 2';
        promotion2.ACCL__Active__c=True;
        promotion2.ACCL__Phase__c='Committed';
        promotionWithTacticList.add(promotion2); 
        
        ACCL__Promotion__c promotion3 = new ACCL__Promotion__c();
        promotion3.ACCL__Promotion_Template__c = promotionTemplateList[2].Id;
        promotion3.ACCL__Date_From__c= Date.Today();
        promotion3.ACCL__Date_Thru__c= Date.Today().addDays(60);
        promotion3.ACCL__Anchor_Account_Set__c = customerSetList[0].Id;
        promotion3.ACCL__Slogan_Language_1__c='Test Promotion 3';
        promotion3.ACCL__Active__c=True;
        promotion3.ACCL__Phase__c='Committed';
        promotionWithTacticList.add(promotion3);
        
        if(promotionWithTacticList.size() > 0){
            Database.Insert(promotionWithTacticList,false);
        }
        
        List<ACCL__Tactic__c> tacticList = new List<ACCL__Tactic__c>();
        
        List<ACCL__Promotion__c> insertedPromotionList = [Select Id from ACCL__Promotion__c];
        
        for(Integer i=0 ; i< insertedPromotionList.size() ; i++){
            ACCL__Tactic__c tactic = new ACCL__Tactic__c();
            tactic.ACCL__Promotion__c=insertedPromotionList[i].id;
            tactic.ACCL__Date_From__c= Date.today(); 
            tactic.ACCL__Date_Thru__c= Date.today().addDays(60);
            tacticList.add(tactic);
        }
        
        if(tacticList.size() > 0){
            Database.Insert(tacticList,false);
        }
        
        ACCL__Product__c product = new ACCL__Product__c(Name='Test Mondelez');
        insert product;
        
        List<ACCL__Tactic_Product__c> tacticProductList = new List<ACCL__Tactic_Product__c>();
        
        list<ACCL__Tactic__c> insertedTacticList = [Select Id from ACCL__Tactic__c];
        for(Integer i=0 ;i<insertedTacticList.size() ; i++){
           ACCL__Tactic_Product__c tacticProd = new ACCL__Tactic_Product__c();
           tacticProd.MDLZ_Price__c = 5;
           tacticProd.MDLZ_Location__c='xff'; 
           tacticProd.MDLZ_SubPPG__c='1Big Bags';
           tacticProd.MDLZ_PPG__c ='1Big Bags'; 
           tacticProd.ACCL__Tactic__c=insertedTacticList[i].id; 
           tacticProd.ACCL__Included__c=true;
           tacticProd.ACCL__Product__c =product.id;
           tacticProductList.add(tacticProd);
            
        }
        
        if(tacticProductList.size() > 0){
            Database.Insert(tacticProductList,false);
        }
        
        List<MDLZ_Promotion_Store__c> newPromoStoreList = new List<MDLZ_Promotion_Store__c>();
        
        for(Integer i=0 ; i<accountList.size() ; i++ ){
            for(Integer j=0 ; j<promotionWithTacticList.size() ;j++){
                MDLZ_Promotion_Store__c promoStore = new MDLZ_Promotion_Store__c();
                promoStore.Promotion__c = promotionWithTacticList[j].Id;
                promoStore.Store__c = accountList[i].Id;
                newPromoStoreList.add(promoStore);
            }
            
        }
        
        if(newPromoStoreList.size() > 0){
            Database.Insert(newPromoStoreList,false);
        }
        
    }
    
    @isTest static void testPromotionWithCustomerSet(){
        
        Test.startTest();
        MDLZ_PromotionExportBatch obj = new MDLZ_PromotionExportBatch();
        Database.executeBatch(obj);
        Test.stopTest();
             
    }

}