src/objects/ACCL__Promotion__c.object
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Decides whether a promotion is available.</description>
        <inlineHelpText>Defines if the promotion is considered in the Trade Calendar and the Account Plan.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Anchor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Customer</description>
        <label>Anchor Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_From__c</fullName>
        <description>Promotion date from</description>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_Thru__c</fullName>
        <description>Promotion date thru</description>
        <label>Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Phase of the promotion</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Preparation</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Modeling</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                    <default>true</default>
                    <label>Committed</label>
                </value>
                <value>
                    <fullName>ForApproval</fullName>
                    <label>For Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AggregatePromotionInputView.cls
/**
* This class is used for determining the promotion record set as a QueryLocator object that will be batched for execution
* @see    PromotionAggregationBatch
*/
global class AggregatePromotionInputView implements ACCL.ACSFBatchInputView {
    private static final Type classType = AggregatePromotionInputView.class;
    private static final string ns = AddOnConstants.NAMESPACEPREFIX; 
    private static final String PROMOTION_PHASE_COMMITTED = 'Committed';
    //private static String txId = TransactionHandler.generateGUID();
   
    /**
    * Description Method for determining the promotion record set as a QueryLocator object that will be batched for execution
    * @param None
    * @return QueryLocator object that will be batched for execution
    */
    global Database.QueryLocator getObjectDataReader() {
        //LogTrace logTraceHandle = LoggerUtility.enterMethod(txId, classType, 'getObjectDataReader', LogTrace.SOURCETYPE.Batch, new String[] {});   
			
		Date fromDate;
        if(Test.isRunningTest()){
            fromDate = Date.Today().addDays(7);
        }else{
            fromDate = Date.Today().addDays(Integer.valueOf(System.label.MDLZ_DateCriteria));
        }
		
        String query ='SELECT Id,ACCL__Anchor_Account__c FROM ACCL__Promotion__c WHERE ACCL__Date_From__c <= :fromDate AND ACCL__Date_Thru__c >=today AND ACCL__Active__c=true AND ACCL__Phase__c=: PROMOTION_PHASE_COMMITTED AND ACCL__Anchor_Account__c != NULL';
        Database.QueryLocator ql = Database.getQueryLocator(query);
        System.debug('ql'+ql);
        return ql;
    }
}