src/objects/ACCL__Org_Unit__c.object
<CustomObject>
    <description>Holds the details of the organization unit object, defining a manufacturer´s organizational structure.</description>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds Description for language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Main__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Main Org Unit.</description>
        <label>Main</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Org_Level__c</fullName>
        <description>Level of an organization unit regarding a organization type.</description>
        <label>Org Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>SalesOrganization</fullName>
                </value>
                <value>
                    <fullName>SalesOffice</fullName>
                </value>
                <value>
                    <fullName>SalesRep</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Org_Type__c</fullName>
        <description>Type of a organization unit.</description>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the org unit belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Org Unit</label>
    <nameField>
        <label>Org Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Org_Unit_Hierarchy__c.object
<CustomObject>
    <description>Holds the detail of the relationship between two org units. Usually used for the sales org unit hierarchy.</description>
    <fields>
        <fullName>ACCL__Child_Org_Unit__c</fullName>
        <description>Reference to a child org unit in an org unit hierarchy.</description>
        <label>Child Org Unit</label>
        <referenceTo>ACCL__Org_Unit__c</referenceTo>
        <relationshipLabel>Parent Org Unit Hierarchies</relationshipLabel>
        <relationshipName>Org_Unit_Hierarchies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Parent_Org_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the parent org unit in an org unit hierachy.</description>
        <label>Parent Org Unit</label>
        <referenceTo>ACCL__Org_Unit__c</referenceTo>
        <relationshipLabel>Child Org Unit Hierarchies</relationshipLabel>
        <relationshipName>Org_Unit_Hierarchies1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Org Unit Hierarchy</label>
    <nameField>
        <displayFormat>OUH-{0000}</displayFormat>
        <label>Org Unit Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Unit Hierarchies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Org_Unit_User__c.object
<CustomObject>
    <description>Holds the details of the relationship between organization unit and user.</description>
    <fields>
        <fullName>ACCL__Main__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines the main user.</description>
        <label>Main</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Management_Type__c</fullName>
        <description>Management Type.</description>
        <label>Management Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>CallCenter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Org_Unit__c</fullName>
        <description>Reference to an org unit assigned to a user.</description>
        <label>Org Unit</label>
        <lookupFilter>
            <active>false</active>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Org_Unit__c</referenceTo>
        <relationshipLabel>Org Unit Users</relationshipLabel>
        <relationshipName>Org_Unit_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ACCL__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a user assigned to an org unit.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Org_Unit_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Org Unit User</label>
    <nameField>
        <displayFormat>OUU-{0000}</displayFormat>
        <label>Org Unit User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Unit Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MDLZ_OrgUnitUserAssignementTestClass.cls
@isTest
public class MDLZ_OrgUnitUserAssignementTestClass {
    
    static testMethod void mainClass(){
        List<ACCL__Org_Unit__c>orgUnitList = new List<ACCL__Org_Unit__c>();
        List<ACCL__Org_Unit_User__c>orgUnitUserList = new List<ACCL__Org_Unit_User__c>();
        
        Test.startTest();
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          LastName='Testing', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com',ACCL__Sales_Org__c='US01');
        
        //insert org unit 
        ACCL__Org_Unit__c orgun = new ACCL__Org_Unit__c();
        orgun.Name ='G500001';
        orgun.ACCL__Sales_Org__c ='US01';
        orgun.ACCL__Org_Type__c ='Sales';
        orgun.ACCL__Org_Level__c ='Team';
        orgun.ACCL__Description_Language_1__c ='MDLZ TerritoryTest Class';
        orgun.ACCL__Main__c =true;
        orgUnitList.add(orgun);
        
        ACCL__Org_Unit__c orgun2 = new ACCL__Org_Unit__c();
        orgun2.Name ='G500002';
        orgun2.ACCL__Sales_Org__c ='US01';
        orgun2.ACCL__Org_Type__c ='Sales';
        orgun2.ACCL__Org_Level__c ='Territory';
        orgun2.ACCL__Description_Language_1__c ='MDLZ TerritoryTest Class-Org2';
        orgUnitList.add(orgun2);     
        
        ACCL__Org_Unit__c orgunterr = new ACCL__Org_Unit__c();
        orgunterr.Name ='G500003';
        orgunterr.ACCL__Sales_Org__c ='US01';
        orgunterr.ACCL__Org_Type__c ='Sales';
        orgunterr.ACCL__Org_Level__c ='Territory';
        orgunterr.ACCL__Description_Language_1__c ='MDLZ TerritoryTest Class result';
        orgunterr.ACCL__Main__c =true; 
        orgUnitList.add(orgunterr);
        
        insert orgUnitList;
        
        //insert org unit hierarchy
        ACCL__Org_Unit_Hierarchy__c orghier = new ACCL__Org_Unit_Hierarchy__c();
        orghier.ACCL__Parent_Org_Unit__c = orgUnitList[0].Id;
        orghier.ACCL__Child_Org_Unit__c = orgUnitList[1].Id;
        
        insert orghier;
        
        //Insert Org unit user                 
        ACCL__Org_Unit_User__c orguser = new ACCL__Org_Unit_User__c();
        orguser.ACCL__Org_Unit__c =orgUnitList[0].Id;
        orguser.ACCL__User__c =u.Id;
        orguser.ACCL__Management_Type__c ='Sales';
        orguser.ACCL__Valid_From__c = System.today();
        orguser.ACCL__Valid_Thru__c = System.today()+10;
        orgUnitUserList.add(orguser);
        
        ACCL__Org_Unit_User__c orguser3 = new ACCL__Org_Unit_User__c();
        orguser3.ACCL__Org_Unit__c =orgUnitList[2].Id;
        orguser3.ACCL__User__c =u.id;
        orguser3.ACCL__Management_Type__c ='Manager';
        orguser3.ACCL__Valid_From__c = System.today();
        orguser3.ACCL__Valid_Thru__c = System.today()+365;
        orgUnitUserList.add(orguser3);
        
        insert orgUnitUserList;
        
        ACCL__Org_Unit__c tes = new ACCL__Org_Unit__c();
        tes.Id = orgun.Id;
        
        list<ACCL__Org_Unit__c>Emplist=new list<ACCL__Org_Unit__c>();
        update Emplist;
        
        MDLZ_TeamTerritoryUserAssignBatch batch= new MDLZ_TeamTerritoryUserAssignBatch(10);
        
        ID batchprocessid2 = Database.executeBatch(batch,10);  
        SchedulableContext sc = null;        
        
        MDLZ_TeamTerritoryUserAssignBatch bdsec2=new MDLZ_TeamTerritoryUserAssignBatch(10);
        bdsec2.execute(sc);
        
        Test.stopTest();
    }
    
}