src/objects/ACCL__Account_Extension__c.object
<CustomObject>
    <description>Object to record account roles and further product related attributes.</description>
    <fields>
        <fullName>ACCL__Account__c</fullName>
        <description>Reference to the customer to which the extension record is assigned.</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Extensions</relationshipLabel>
        <relationshipName>Account_Extensions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Extension</label>
    <nameField>
        <displayFormat>AEX-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Account_Trade_Org_Hierarchy__c.object
<CustomObject>
    <description>Holds the details of the account hierarchy. From points to the higher trade org, to points to the lower trade org or store, The relation is time dependent.</description>
    <fields>
        <fullName>ACCL__Child_Account__c</fullName>
        <description>Reference to the business partner the relation is going to.</description>
        <label>Child Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Trade Org Hierarchies</relationshipLabel>
        <relationshipName>Account_Trade_Org_Child</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference from the business partner from which the relation is out going.</description>
        <label>Parent Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Trade Org Hierarchies (Parent Account)</relationshipLabel>
        <relationshipName>Account_Trade_Org_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Customer Trade Org Hierarchy</label>
    <nameField>
        <displayFormat>TOH-{0000}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Trade Org Hierarchies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__City__c</fullName>
        <description>Name of a city.</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Name_2__c</fullName>
        <description>Alternate name for the customer.</description>
        <label>Name 2</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Street__c</fullName>
        <description>Name of a street.</description>
        <label>Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AccountClearEffectiveParentBatchTest.cls
@isTest

private class AccountClearEffectiveParentBatchTest {

    @testsetup
    static void createAccountData(){
        Map<String, Schema.SObjectType> AllObjects = Schema.getGlobalDescribe();
        List<sObject> accList = new List<sObject>();
        List<sObject> accParentList = new List<sObject>();
        List<sObject> accExtList = new List<sObject>();
        List<sObject> accNewList = new List<sObject>();
        List<sObject> accTradeOrgList = new List<sObject>();
        for(Integer i=0; i<200; i++) {
            sObject accObj = AllObjects.get('Account').newSObject();
            accObj.put('ACCL__City__c','Test City');
            accObj.put('ACCL__Street__c','Test Street');
            accObj.put('Name','Test Account'+i);
            accObj.put('ACCL__Name_2__c','testX'+i);
            accList.add(accObj);
        }
        insert accList;
        for(sObject acc : accList) {
            sObject accObjParent = AllObjects.get('Account').newSObject();
            accObjParent.put('Name','Test Account Child');
            accObjParent.put('ParentId', acc.Id);
            accParentList.add(accObjParent);
            // Account Extension
            sObject accExtObj = AllObjects.get('ACCL__Account_Extension__c').newSObject();
            accExtObj.put('ACCL__Account__c', acc.Id);
            accExtList.add(accExtObj);
        }
        insert accParentList;
        insert accExtList;
    }

    /** Positive scenario test */
    private static testMethod void insertAccountEffectiveParentClearData() {
        AccountClearEffectiveParentBatch sh1 = new AccountClearEffectiveParentBatch();
        Test.startTest();
        ID batchprocessid = Database.executeBatch(sh1,200);
        Test.stopTest();
        List<sObject> listAccParentIdCheck = [SELECT Id FROM Account WHERE ParentId=null LIMIT 1000];
        System.assert(listAccParentIdCheck.size() > 199, true);
    }

    /** Negative scenario test */
    private static testMethod void insertAccountEffectiveParentClearNegativeBulkData() {

        Map<String, Schema.SObjectType> AllObjectMeta = Schema.getGlobalDescribe();
        List<sObject> accTradeOrgList = new List<sObject>();
        List<sObject> accListnew = [SELECT Id, Name FROM Account WHERE ParentId != null];
        // Add Account Trade Org Hierarchy
        for(Integer i=0; i<accListnew.size()-1; i++) {
            sObject accTradeOrgObj = AllObjectMeta.get('ACCL__Account_Trade_Org_Hierarchy__c').newSObject();
            accTradeOrgObj.put('ACCL__Child_Account__c', accListnew[i].Id);
            accTradeOrgObj.put('ACCL__Valid_From__c',System.today().addMonths(-1));
            accTradeOrgObj.put('ACCL__Valid_Thru__c',System.today().addMonths(1));
            accTradeOrgObj.put('ACCL__Parent_Account__c',accListnew[i+1].Id);
            accTradeOrgList.add(accTradeOrgObj);
        }
		insert accTradeOrgList;
        AccountClearEffectiveParentBatch sh1 = new AccountClearEffectiveParentBatch();
        Test.startTest();
        ID batchprocessid = Database.executeBatch(sh1,200);
        Test.stopTest();
		List<Account> accList = [SELECT Id FROM Account WHERE ParentId!=null LIMIT 1000];
        System.assert(accList.size() > 0,True);        
    }  
}