src/objects/ACCL__Org_Unit__c.object
<CustomObject>
    <description>Holds the details of the organization unit object, defining a manufacturer´s organizational structure.</description>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds Description for language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Main__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Main Org Unit.</description>
        <label>Main</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Org_Level__c</fullName>
        <description>Level of an organization unit regarding a organization type.</description>
        <label>Org Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>SalesOrganization</fullName>
                </value>
                <value>
                    <fullName>SalesOffice</fullName>
                </value>
                <value>
                    <fullName>SalesRep</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Org_Type__c</fullName>
        <description>Type of a organization unit.</description>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the org unit belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Org Unit</label>
    <nameField>
        <label>Org Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Org_Unit_User__c.object
<CustomObject>
    <description>Holds the details of the relationship between organization unit and user.</description>
    <fields>
        <fullName>ACCL__Main__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines the main user.</description>
        <label>Main</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MDLZ_isOrgUnitChanged__c</fullName>
        <description>This field is updated by Integration to &quot;Int Updated&quot; when there is a org unit change for the user.</description>
        <label>isOrgUnitChanged</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Int Updated</fullName>
                </value>
                <value>
                    <fullName>Batch Processed</fullName>
                </value>
                <value>
                    <fullName>TT Processed</fullName>
                </value>
                <value>
                    <fullName>RDR Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Org_Unit__c</fullName>
        <description>Reference to an org unit assigned to a user.</description>
        <label>Org Unit</label>
        <lookupFilter>
            <active>false</active>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Org_Unit__c</referenceTo>
        <relationshipLabel>Org Unit Users</relationshipLabel>
        <relationshipName>Org_Unit_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ACCL__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a user assigned to an org unit.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Org_Unit_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Org Unit User</label>
    <nameField>
        <displayFormat>OUU-{0000}</displayFormat>
        <label>Org Unit User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Unit Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MDLZ_isChanged__c</fullName>
        <description>Field to be updated by integration as Int Updated when there is a change on the user record. To be updated by Batch as Batch Processed post processing of the record</description>
        <label>isChanged</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Int Updated</fullName>
                </value>
                <value>
                    <fullName>Batch Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MDLZ_UpdateOrgUnitUserValidityTestFctry.cls
/***************************************************************
Name: MDLZ_UpdateOrgUnitUserValidityTestFctry
======================================================
Purpose:
Test Factory for MDLZ_ProdAssortment_ByCustBranchBatch
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0      Priya Tubachi                03/30/2022     Initial Development    

***************************************************************/
public class MDLZ_UpdateOrgUnitUserValidityTestFctry {

    public static user createUser(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator' Limit 1];
        User u = new User(Alias = 'standt', Email='orgUnituser@testorg.com', 
                          LastName='Testing', isActive =true,
                          ProfileId = p.Id,
                          MDLZ_isChanged__c = 'Int Updated', 
                          UserName='orgUnituser123456@testorg.com',ACCL__Sales_Org__c='US01');
        return u;
    }
    
    public static ACCL__Org_Unit__c insertOrgUnit(){
        ACCL__Org_Unit__c orgun1 = new ACCL__Org_Unit__c();
        orgun1.Name ='G500002';
        orgun1.ACCL__Sales_Org__c ='US01';
        orgun1.ACCL__Org_Type__c ='Sales';
        orgun1.ACCL__Org_Level__c ='Team';
        orgun1.ACCL__Description_Language_1__c ='MDLZ updateOrg user-Team Org2';
        orgun1.ACCL__Main__c =true;
        insert orgun1;
        System.assertEquals(orgun1.ACCL__Sales_Org__c,'US01');
        return orgun1;
        
    }
    
    public static ACCL__Org_Unit_User__c insertOrgUnitUser(ACCL__Org_Unit__c orgun1,user u){
        ACCL__Org_Unit_User__c orgusr = new ACCL__Org_Unit_User__c();
        orgusr.ACCL__User__c =u.Id;
        orgusr.ACCL__Org_Unit__c = orgun1.id;
        orgusr.MDLZ_isOrgUnitChanged__c ='Batch Processed';
        orgusr.ACCL__Valid_From__c =System.today()-100;
        orgusr.ACCL__Valid_Thru__c =System.today()+1;
        insert orgusr;
        System.assertEquals(orgusr.MDLZ_isOrgUnitChanged__c,'Batch Processed');
        return orgusr;
        
    }
}