src/objects/ACCL__Promotion__c.object
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <fields>
        <fullName>ACCL__Date_From__c</fullName>
        <description>Promotion date from</description>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_Thru__c</fullName>
        <description>Promotion date thru</description>
        <label>Date Thru</label>
        <type>Date</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Tactic__c.object
<CustomObject>
    <description>Relation from a Promotion and Tactic.</description>
    <fields>
        <fullName>ACCL__Amount__c</fullName>
        <description>Tactic Cost Amount</description>
        <label>Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_From__c</fullName>
        <description>Start date of a tactic</description>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_Thru__c</fullName>
        <description>End date of a tactic</description>
        <label>Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Lift_Type__c</fullName>
        <label>Lift Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Abs</fullName>
                </value>
                <value>
                    <fullName>%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Promotion__c</fullName>
        <description>Reference to the promotion</description>
        <label>Promotion</label>
        <referenceTo>ACCL__Promotion__c</referenceTo>
        <relationshipLabel>Tactics</relationshipLabel>
        <relationshipName>Tactics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Scenario_Participation__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Bitlist defining the scenario participation (only the first 5 bits are used).</description>
        <label>Scenario Participation</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACCL__Tactic_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the tactic template</description>
        <label>Tactic Template</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Tactic template does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>ACCL__Tactic_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Tactic_Template__c</referenceTo>
        <relationshipLabel>Tactics</relationshipLabel>
        <relationshipName>Tactics</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tactic</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tactic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tactics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Tactic_Template__c.object
<CustomObject>
    <description>Template which controls the behaviour of a tactic</description>
    <label>Tactic Template</label>
    <nameField>
        <label>Tactic Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tactic Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddOnTacticTestFactory.cls
@isTest
public class AddOnTacticTestFactory {
    public AddOnTacticTestFactory() {
    }

    public static ACCL__Tactic__c defaultTactic;
    public static ACCL__Tactic__c defaultTacticWithSalesOrg;

    public static ACCL__Tactic__c getDefaultTactic() {
        if( defaultTactic == null ){
            defaultTactic = insertDefaultTactic();
        }
        return defaultTactic;
    }

    public static ACCL__Tactic__c insertDefaultTactic() {
        ACCL__Tactic__c tactic = buildDefaultTactic();
        return (ACCL__Tactic__c) AddOnTestFactoryUtility.insertSObject(tactic);
    }

    public static ACCL__Tactic__c buildDefaultTactic() {
        return buildTactic(AddOnPromotionTestFactory.getDefaultPromotion(), AddOnTacticTemplateTestFactory.getDefaultTacticTemplate());
    }
 
    public static ACCL__Tactic__c buildTactic(ACCL__Promotion__c promotion, ACCL__Tactic_Template__c tacticTemplate) {

        ACCL__Tactic__c tactic = new ACCL__Tactic__c();
        tactic.ACCL__Tactic_Template__c = tacticTemplate.id;
        tactic.ACCL__Promotion__c=promotion.id;
        tactic.ACCL__Date_From__c=System.today();
        tactic.ACCL__Date_Thru__c=System.today().addMonths(1);
        tactic.ACCL__Scenario_Participation__c = 1;
        tactic.ACCL__Lift_Type__c = '%';
        tactic.ACCL__Amount__c = 10;

        return tactic;

    }

    //method for inserting Tactic for PromotionFindingTest class
    public static ACCL__Tactic__c insertTactic(ACCL__Promotion__c promotion,ACCL__Tactic_Template__c tacticTemplate) {

        ACCL__Tactic__c tactic = buildTactic(promotion, tacticTemplate);
        return (ACCL__Tactic__c) AddOnTestFactoryUtility.insertSObject(tactic);

    }

    public static List<ACCL__Tactic__c> insertTactics(Integer numTactics, ACCL__Tactic_Template__c tacticTemplate, ACCL__Promotion__c promo){
        List<ACCL__Tactic__c> tacticList = buildTactics(numTactics, tacticTemplate, promo);
        return (List<ACCL__Tactic__c>) AddOnTestFactoryUtility.insertBulkSObject(tacticList);
    }

    public static List<ACCL__Tactic__c> buildTactics(Integer numTactics, ACCL__Tactic_Template__c tacticTemplate, ACCL__Promotion__c promo){
        List<ACCL__Tactic__c> tacticList = new List<ACCL__Tactic__c>();
        for(Integer i = 0; i<numTactics;i++){
            tacticList.add(buildTactic(promo, tacticTemplate));
        }
        return tacticList;
    }

    public static List<ACCL__Tactic__c> buildInsertTactics(Integer numTactics, ACCL__Tactic_Template__c tacticTemplate, List<ACCL__Promotion__c> promos){
        List<ACCL__Tactic__c> tacticList = new List<ACCL__Tactic__c>();
        for(Integer i = 0; i<numTactics;i++){
            tacticList.add(buildTactic(promos[i], tacticTemplate));
        }
        return (List<ACCL__Tactic__c>) AddOnTestFactoryUtility.insertBulkSObject(tacticList);
    }

    public static List<ACCL__Tactic__c> buildInsertTactics(Integer numTactics, ACCL__Tactic_Template__c tacticTemplate, ACCL__Promotion__c promo){
        List<ACCL__Tactic__c> tacticList = new List<ACCL__Tactic__c>();
        for(Integer i = 0; i<numTactics;i++){
            tacticList.add(buildTactic(promo, tacticTemplate));
        }
        return (List<ACCL__Tactic__c>) AddOnTestFactoryUtility.insertBulkSObject(tacticList);
    }

}