src/objects/ACCL__Account_Set__c.object
<CustomObject>
    <description>Object for the creation of Customer Sets.</description>
    <label>Customer Set</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Promotion__c.object
<CustomObject>
    <description>Promotion is an activity of a user which includes the definition of prices for a time segment.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Decides whether a promotion is available.</description>
        <inlineHelpText>Defines if the promotion is considered in the Trade Calendar and the Account Plan.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Anchor_Account_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to Customer Set</description>
        <label>Anchor Customer Set</label>
        <referenceTo>ACCL__Account_Set__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Anchor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Customer</description>
        <label>Anchor Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Commit_Date__c</fullName>
        <description>The date the promotion was commited. This field is taken for getting the prices and discounts of a promotion.</description>
        <label>Commit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_From__c</fullName>
        <description>Promotion date from</description>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Date_Thru__c</fullName>
        <description>Promotion date thru</description>
        <label>Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Delivery_Date_From__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Delivery Date From</description>
        <label>Shipment Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Delivery_Date_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Delivery Date Thru</description>
        <label>Shipment Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Group_Text_Language_1__c</fullName>
        <description>Holds the Group Text in language 1</description>
        <label>Group Text Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Date_From__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Order Date From.</description>
        <label>Order Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Date_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Order Date Thru.</description>
        <label>Order Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Phase of the promotion</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Preparation</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Modeling</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                    <default>true</default>
                    <label>Committed</label>
                </value>
                <value>
                    <fullName>ForApproval</fullName>
                    <label>For Approval</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Placement_Date_From__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Placement Date From</description>
        <label>In-Store Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Placement_Date_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Placement Date Thru</description>
        <label>In-Store Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Promotion_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to promotion template.</description>
        <label>Promotion Template</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>ACCL__Promotion_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Promotion_Template__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Relevant_For_Account_Plan__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field is for project customization. Through this field one can set if the Promotion is specific for the Account Plan.</description>
        <inlineHelpText>Through this field one can set if the Promotion is specific for the Account Plan.</inlineHelpText>
        <label>Relevant For Account Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Slogan_Language_1__c</fullName>
        <description>Holds the slogan in language 1.</description>
        <label>Slogan Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AddOnPromotionTestFactory.cls
@isTest
public class AddOnPromotionTestFactory {
    //FLS_Create, FLS_Create_Partial
    //This class is used for unit test data creation and is used in other test classes. It will be executed in System context, hence no FLS/CRUD check is required.
    public static ACCL__Promotion__c defaultPromotion;
    public static ACCL__Promotion__c defaultPromotionWithSalesOrg;

    public static ACCL__Promotion__c insertPromotion(Integer i, ACCL__Promotion_Template__c template, Account account, String phase){
        return (ACCL__Promotion__c)AddOnTestFactoryUtility.insertSObject(buildPromotion(i, template,  account, Phase));
    }

    public static ACCL__Promotion__c insertPromotion(Integer i, ACCL__Promotion_Template__c template, ACCL__Account_Set__c accountset, String phase){
        return (ACCL__Promotion__c)AddOnTestFactoryUtility.insertSObject(buildPromotion(i, template,  accountset, phase));
    }

        public static ACCL__Promotion__c buildPromotion(Integer nameSuffix, ACCL__Promotion_Template__c template, Account account, String phase) {
        return buildPromotion(nameSuffix, template, account, null, phase, true, System.today(), System.today().addYears(1));
    }

    public static ACCL__Promotion__c buildPromotion(Integer nameSuffix, ACCL__Promotion_Template__c template, ACCL__Account_Set__c accountset, String phase) {
        return buildPromotion(nameSuffix, template, null, accountset, phase, true, System.today(), System.today().addYears(1));
    }
        public static ACCL__Promotion__c buildPromotion(Integer nameSuffix, ACCL__Promotion_Template__c template,
                                              Account account, ACCL__Account_Set__c accountSet, String phase,
                                              Boolean active, Date dateFrom, Date dateThru) {
        return buildPromotion(nameSuffix, template, account, accountSet, phase, active, dateFrom, dateThru, null, null);
    }

    public static ACCL__Promotion__c buildPromotion(Integer nameSuffix, ACCL__Promotion_Template__c template, Account account, ACCL__Account_Set__c accountSet, String phase,
                                              Boolean active, Date dateFrom, Date dateThru, String slogan, String groupText) {
        ACCL__Promotion__c promotion = new ACCL__Promotion__c();
        promotion.ACCL__Active__c = active;
        promotion.ACCL__Anchor_Account__c = account != null ? account.Id : null;
        promotion.ACCL__Anchor_Account_Set__c = accountSet != null ? accountSet.Id : null;
        promotion.ACCL__Commit_Date__c = dateFrom;
        promotion.ACCL__Promotion_Template__c = template != null ? template.Id : AddOnPromotionTemplateTestFactory.getDefaultAccountSetPromotionTemplate().Id;
        promotion.ACCL__Date_From__c = dateFrom;
        promotion.ACCL__Date_Thru__c = dateThru;
        promotion.ACCL__Delivery_Date_From__c = promotion.ACCL__Date_From__c;
        promotion.ACCL__Delivery_Date_Thru__c = promotion.ACCL__Date_From__c.addDays(30);
        promotion.ACCL__Order_Date_From__c = promotion.ACCL__Date_From__c;
        promotion.ACCL__Order_Date_Thru__c = promotion.ACCL__Date_Thru__c;
        promotion.ACCL__Placement_Date_From__c = promotion.ACCL__Date_From__c;
        promotion.ACCL__Placement_Date_Thru__c = promotion.ACCL__Date_Thru__c;
        promotion.ACCL__Slogan_Language_1__c = (slogan != null) ? slogan : ('slogan '+nameSuffix);
        promotion.ACCL__Group_Text_Language_1__c = groupText;
        promotion.ACCL__Phase__c=phase;
        promotion.ACCL__Relevant_For_Account_Plan__c = true;
        return promotion;
    }

    public static List<ACCL__Promotion__c> buildPromotions( Integer numberOfPromotions ) {
        List<ACCL__Promotion__c> promotions = new List<ACCL__Promotion__c>();
        for(Integer i=0 ; i < numberOfPromotions ; i++){
            promotions.add(buildPromotion(i,AddOnPromotionTemplateTestFactory.getDefaultPromotionTemplate(),AddOnAccountTestFactory.getDefaultAccount(),AddOnConstants.PROMOTION_PHASE_PLANNING));
        }
        return promotions;
    }    

    public static ACCL__Promotion__c buildDefaultPromotion() {
        return buildPromotion(-1,AddOnPromotionTemplateTestFactory.getDefaultPromotionTemplate(),AddOnAccountTestFactory.getDefaultAccount(),AddOnConstants.PROMOTION_PHASE_PLANNING);
    }

    public static ACCL__Promotion__c getDefaultPromotion() {
        if( defaultPromotion == null ){
            defaultPromotion = insertPromotion(-1, AddOnPromotionTemplateTestFactory.getDefaultPromotionTemplate(),AddOnAccountTestFactory.getDefaultAccount(),AddOnConstants.PROMOTION_PHASE_PLANNING);
        }
        return defaultPromotion;
    }
}