src/objects/ACCL__Product_Assortment_Product__c.object
<CustomObject>
    <description>Holds the relationship between a product assortment and a product.A product-assortment-relation is time-dependent. Assortments can be used as set of products which are restricted to an industry or a sales channel.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active flag.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MDLZ_ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Assortment Product</label>
    <nameField>
        <displayFormat>PAP-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Assortment Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MDLZ_ProdAssortProd_Batch.cls
/***************************************************************
Name: MDLZ_ProdAssortProd_Batch
======================================================
Purpose:
Batch process  runs every day that identifies 
Product Assortment Products that have not been updated in the past X-weeks 
(X should be a configurable variable that can be changed but will have a default value of 2)
and deactivates these records. Deactivation sohuld include setting the Valid Thru date to the current date and setting the active flag to false.

======================================================
History
-------
VERSION     AUTHOR          REVIEWER      DATE             DETAIL              Description
1.0       Bharath_Vikkurthi            07/02/2022    Initial Development 
2.0       Bharath_Vikkurthi            12/05/2022    changed the query locator to consider only Branch 

***************************************************************/
global class MDLZ_ProdAssortProd_Batch implements Database.Batchable<sObject>,Schedulable, Database.Stateful {
    //Custom label for last-n-days
   Integer  dt = Integer.valueOf(System.Label.MDLZ_Prod_Cleanup_Days); 
    
    //Defining the Scheduled Batch Size thru constructor
    public integer defaultChildBatchSize;
    public MDLZ_ProdAssortProd_Batch(integer childBatchSize){
        defaultChildBatchSize = childBatchSize;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC)    
    {
        
        // Query the records lastmodified date eq to 14 days default 
        String query = 'Select Id, Name, ACCL__Active__c, ACCL__Valid_Thru__c,ACCL__Valid_From__c,LastModifiedDate' 
            +' from  ACCL__Product_Assortment_Product__c where MDLZ_ExternalID__c like \'%Branch%\' and  ACCL__Active__c = true and LastModifiedDate < LAST_N_DAYS:'+dt;
        return Database.getQueryLocator(query);
    }
 
    global void execute(Database.BatchableContext BC, List<ACCL__Product_Assortment_Product__c> scope)
    {
         new MDLZ_ProdAssortProd_Cleanup().getLastModrec(scope); 
    
    }
    
    global void execute(SchedulableContext ctx) {
        Database.executeBatch(new MDLZ_ProdAssortProd_Batch(200), defaultChildBatchSize);    
    } 
    
    global void finish(Database.BatchableContext BC)
    {
          
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob details = [SELECT Id, Status,ExtendedStatus, NumberOfErrors, JobItemsProcessed,TotalJobItems, 
                                CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        System.debug('Batch Process Details' +details);
    }
    
}