src/objects/ACCL__Order__c.object
<CustomObject>
    <description>Holds the header details of the order entry.</description>
    <fields>
        <fullName>ACCL__Customer_Order_Id__c</fullName>
        <label>Customer Order Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Delivery_Date__c</fullName>
        <description>By default next day.Delivery date calculation is
			customized very often.</description>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to capture customer for which Order is
			created</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Customer)</relationshipLabel>
        <relationshipName>Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Order Template for Order Entry</description>
        <label>Order Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Order_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Order_Template__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Workflow neutral description of the order Entry status.</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Send to SAP</fullName>
                    <label>Sent to SAP</label>
                </value>
                <value>
                    <fullName>Received By SAP</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Routed</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MDLZ_Total_Case_Quantity__c</fullName>
        <description>Sum of case quantity of all products in the order item</description>
        <label>Total Case Quantity</label>
        <summarizedField>ACCL__Order_Item__c.ACCL__Quantity__c</summarizedField>
        <summaryForeignKey>ACCL__Order_Item__c.ACCL__Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Order_Template__c.object
<CustomObject>
    <description>Template which controls the behaviour of a sales document.</description>
    <label>Order Template</label>
    <nameField>
        <label>Order Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_UpdateCAOOrdersBatch.cls
/***************************************************************
Name: MDLZ_UpdateCAOOrdersBatch
======================================================
Purpose:
a. batch2 to update CAO orders to Routed or cancelled 
refer conditions in confluence matrix.
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              
1.0      Priya Tubachi            	 25/09/2021     Initial Development 
1.1      Priya Tubachi               10/05/2022     Optimizing class for AMS issues
***************************************************************/
global with sharing class MDLZ_UpdateCAOOrdersBatch implements Database.Batchable< sObject >, Schedulable {
    
    /***** Private variables ********/
    private static Integer DEFAULTBATCHSIZE = 200;
    private Integer batchSize;
    private static final string PROCESS_NAME = MDLZ_ConstantHelper.UPDATE_CAO_ORDERS;
    
    /** Initializing the constructor for the batch class **/
     
    global MDLZ_UpdateCAOOrdersBatch() {
        String squery ='SELECT ACCL__Batch_Size__c FROM ACCL__Batch_Process_Configuration__c WHERE Name=:PROCESS_NAME';
        List<sObject> sobjList = Database.query(sQuery);
       
        if(!sobjList.isEmpty()) {
            batchSize = ((Decimal)sobjList[0].get('ACCL__Batch_Size__c')).intValue();  
        }
        else
        {
           batchSize = DEFAULTBATCHSIZE;
        } 
    }
    
    /** start method of Batch class for input query**/
    
    global Database.QueryLocator start(Database.BatchableContext BC)    
    {
        
        //Retrieve list of orders with order template as EDI and NOS for the current day
        String query = 'SELECT ACCL__Delivery_Date__c,ACCL__Order_Account__c, ACCL__Order_Template__r.Name,ACCL__Phase__C,MDLZ_Total_Case_Quantity__c'
            +' FROM ACCL__Order__c WHERE ACCL__Customer_Order_Id__c = \'\' and ACCL__Delivery_Date__c >=today and ACCL__Delivery_Date__c <= tomorrow and'+
            ' ACCL__Order_Template__r.Name in (\'Order Wrapper\') and ACCL__Phase__c in (\'Received By SAP\')';
        
        return Database.getQueryLocator(query);
        
    }
    
    global void execute(Database.BatchableContext BC, List<sobject> orderList)
    {
        new MDLZ_OrderConsolidation().updateCAOOrdersNew(orderList);
    }
    
    //schedulable method of the batch class
    global void execute(SchedulableContext ctx) {
        Database.executeBatch(this, batchSize);
    } 
    
    global void finish(Database.BatchableContext BC)
    {
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob details = [SELECT Id, Status,ExtendedStatus, NumberOfErrors, JobItemsProcessed,TotalJobItems, 
                                CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        System.debug('Batch Process Details' +details);    
    }
}