src/objects/ACCL__Product__c.object
<CustomObject>
    <description>This object records the attributes of a product.</description>
    <fields>
        <fullName>ACCL__Product_Code__c</fullName>
        <description>Unique identification of a product.</description>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ACCL__Product_Level__c</fullName>
        <description>Describes the Product Level.</description>
        <label>Product Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Category</fullName>
                </value>
                <value>
                    <fullName>SubCategory</fullName>
                    <label>Sub Category</label>
                </value>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Flavor</fullName>
                </value>
                <value>
                    <fullName>Package</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                    <default>true</default>
                    <label>Product</label>
                </value>
                <value>
                    <fullName>PPG</fullName>
                </value>
                <value>
                    <fullName>Case Config</fullName>
                </value>
                <value>
                    <fullName>Main Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Product_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to product template.</description>
        <label>Product Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Product_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Product_Template__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the product belongs to.</description>
        <formula>TEXT(ACCL__Product_Template__r.ACCL__Sales_Org__c)</formula>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <label>Product</label>
	 <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Product_Assortment__c.object
<CustomObject>
    <description>Holds the details of a set of products which are often used together.</description>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds the description of language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Product_Assortment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to product assortment template.</description>
        <label>Product Assortment Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Product_Assortment_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Product_Assortment_Template__c</referenceTo>
        <relationshipLabel>Product Assortments</relationshipLabel>
        <relationshipName>Product_Assortments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the product assortment belongs to.</description>
        <formula>TEXT(ACCL__Product_Assortment_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Product Assortment</label>
    <nameField>
        <label>Product Assortment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Assortments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Product_Assortment_Product__c.object
<CustomObject>
    <description>Holds the relationship between a product assortment and a product.A product-assortment-relation is time-dependent. Assortments can be used as set of products which are restricted to an industry or a sales channel.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Active flag.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Product_Assortment__c</fullName>
        <description>Reference to the assortment the product relation belongs to.</description>
        <label>Product Assortment</label>
        <referenceTo>ACCL__Product_Assortment__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Product_Assortment_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Product__c</fullName>
        <description>Reference to a product assigned to the assortment.</description>
        <label>Product</label>
        <referenceTo>ACCL__Product__c</referenceTo>
        <relationshipLabel>Product Assortment Products</relationshipLabel>
        <relationshipName>Product_Assortment_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Product Assortment Product</label>
    <nameField>
        <displayFormat>PAP-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Assortment Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Product_Assortment_Template__c.object
<CustomObject>
    <description>Template for product assortments. Controls the behaviour of the instances of this template, for example if a business partner must be specified (AccountMultiplicity). This table is sales organization dependent.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Boolean to identify if the Product Assortment template is active.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <description>Holds the description of language 1.</description>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Product_Level__c</fullName>
        <description>Describes the product level.</description>
        <label>Product Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Category</fullName>
                </value>
                <value>
                    <fullName>SubCategory</fullName>
                </value>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Flavor</fullName>
                </value>
                <value>
                    <fullName>Package</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the product assortment template belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <label>Product Assortment Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Assortment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_ProdAssortProd_TestClass.cls
/***************************************************************
Name: MDLZ_ProdAssortProd_TestClass
======================================================
Purpose:

======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0     Bharath Vikkurthi       		                       15/02/2022     Initial Development    

***************************************************************/

@isTest
public class MDLZ_ProdAssortProd_TestClass {
    
    static testMethod void cleanProdAssrt(){
        
        List<ACCL__Product_Template__c> prList = new List<ACCL__Product_Template__c>();
        List<ACCL__Product__c> prodList  = new List<ACCL__Product__c>();
        
        ACCL__Product_Template__c prtemp = new ACCL__Product_Template__c();
        prtemp.Name ='Product US01 Test';
        prtemp.ACCL__Active__c =true;
        prtemp.ACCL__Sales_Org__c ='US01';
        prtemp.RecordTypeId =Schema.SObjectType.ACCL__Product_Template__c.getRecordTypeInfosByName().
            get('Product').getRecordTypeId();
        prList.add(prtemp);
        System.assertEquals(prtemp.ACCL__Sales_Org__c, 'US01');
        ACCL__Product_Template__c prtemp1 = new ACCL__Product_Template__c();
        prtemp1.Name ='Product US02 Test';
        prtemp1.ACCL__Active__c =true;
        prtemp1.ACCL__Sales_Org__c ='0001';
        prtemp1.RecordTypeId =Schema.SObjectType.ACCL__Product_Template__c.getRecordTypeInfosByName().
            get('Product').getRecordTypeId();
        prList.add(prtemp1);
        insert prList;
        System.assertEquals(prList[0].ACCL__Active__c , true);
        ACCL__Product_Assortment_Template__c prasstemp = new ACCL__Product_Assortment_Template__c();
        prasstemp.Name ='Listing';
        prasstemp.ACCL__Description_Language_1__c ='Authorization List';
        prasstemp.ACCL__Sales_Org__c ='US01';
        prasstemp.RecordTypeId =Schema.SObjectType.ACCL__Product_Assortment_Template__c.getRecordTypeInfosByName().
            get('Assortment List').getRecordTypeId();
        insert prasstemp;
        
        ACCL__Product__c prd = new ACCL__Product__c();
        prd.Name ='Cookie Product 01';
        prd.ACCL__Product_Template__c =prList[0].Id;
        prd.ACCL__Product_Code__c ='1234556';
        prd.ACCL__Product_Level__c ='Product';
        prodList.add(prd);
        ACCL__Product__c prd1 = new ACCL__Product__c();
        prd1.Name ='Cookie Product 02';
        prd1.ACCL__Product_Template__c =prList[1].Id;
        prd1.ACCL__Product_Code__c ='1234552';
        prd1.ACCL__Product_Level__c ='Product1';
        prodList.add(prd1);
        insert prodList;
        
        ACCL__Product_Assortment__c prs = new ACCL__Product_Assortment__c();
        prs.Name ='US01_1017_Branch';
        prs.ACCL__Product_Assortment_Template__c =prasstemp.Id;
        prs.ACCL__Valid_From__c =System.today();
        prs.ACCL__Valid_Thru__c =System.today()+2;  
        insert prs;
        
        
        List<ACCL__Product_Assortment_Product__c> prdList = new  List<ACCL__Product_Assortment_Product__c>();
        ACCL__Product_Assortment_Product__c prdsst = new ACCL__Product_Assortment_Product__c();
        prdsst.ACCL__Product__c =prodList[0].Id;
        prdsst.ACCL__Product_Assortment__c =prs.Id;
        prdsst.ACCL__Valid_From__c =System.today();
        prdsst.ACCL__Valid_Thru__c = System.today()+2;  
        prdsst.ACCL__Active__c = true;
        prdList.add(prdsst);
        
        ACCL__Product_Assortment_Product__c prdsst2 = new ACCL__Product_Assortment_Product__c();
        prdsst2.ACCL__Product__c =prodList[0].Id;
        prdsst2.ACCL__Product_Assortment__c =prs.Id;
        prdsst2.ACCL__Active__c = true;
        prdList.add(prdsst2);
        insert prdList;
        
        ACCL__Product_Assortment_Product__c pp =[Select Id from ACCL__Product_Assortment_Product__c where id =:prdsst2.Id];
        
        Test.startTest();
        prdList[1].ACCL__Product__c =prodList[1].Id;
        
        MDLZ_ProdAssortProd_Cleanup pr = new MDLZ_ProdAssortProd_Cleanup();
        pr.getLastModrec(prdList);
        pr.getLastModrec(new List<ACCL__Product_Assortment_Product__c> {pp});
        
        MDLZ_ProdAssortProd_Batch b = new MDLZ_ProdAssortProd_Batch(1);
        Database.executeBatch(b, 1);
        SchedulableContext sc = null;
        
        MDLZ_ProdAssortProd_Batch bdsec=new MDLZ_ProdAssortProd_Batch(1);
        bdsec.execute(sc);
        Test.stopTest();
    }
}