src/objects/ACCL__Order__c.object
<CustomObject>
    <description>Holds the header details of the order entry.</description>
    <fields>
        <fullName>ACCL__Customer_Order_Id__c</fullName>
        <label>Customer Order Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>MDLZ_LastSavedByUser__c</fullName>
        <label>Last Saved By User</label>
        <type>DateTime</type>
    </fields>
	<fields>
        <fullName>MDLZ_isOrderAccepted__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Showing if an order was accepted (true) or rejected by SAP (false).</description>
        <label>Is Order Accepted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Delivery_Date__c</fullName>
        <description>By default next day.Delivery date calculation is
			customized very often.</description>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Document_Type__c</fullName>
        <description>Specifies the type of the order document in order to distinguish DSD and non-DSD order entries.</description>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>ProductCheckIn</fullName>
                </value>
                <value>
                    <fullName>ProductCheckOut</fullName>
                </value>
                <value>
                    <fullName>TruckAudit</fullName>
                </value>
                <value>
                    <fullName>CashCheckIn</fullName>
                </value>
                <value>
                    <fullName>CashCheckOut</fullName>
                </value>
                <value>
                    <fullName>OrderEntry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Order_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to capture customer for which Order is
			created</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Customer)</relationshipLabel>
        <relationshipName>Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Order Template for Order Entry</description>
        <label>Order Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Order_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Order_Template__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Phase__c</fullName>
        <description>Workflow neutral description of the order Entry status.</description>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Send to SAP</fullName>
                    <label>Sent to SAP</label>
                </value>
                <value>
                    <fullName>Received By SAP</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Routed</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MDLZ_isChanged__c</fullName>
        <description>Functionality introduced for RDT pilot for Order Redesign to address following defects:
MRELKXIW-1925, MRELKXIW-1912, MRELKXIW-1918</description>
        <label>IsChanged</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FALSE</fullName>
                    <default>true</default>
                    <label>FALSE</label>
                </value>
                <value>
                    <fullName>TRUE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Order_Item__c.object
<CustomObject>
    <description>Holds the details of the order item object.</description>
    <fields>
        <fullName>ACCL__Order__c</fullName>
        <description>ID of the order where Order Item is associated with</description>
        <label>Order</label>
        <referenceTo>ACCL__Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
	<fields>
        <fullName>MDLZ_BkpSuggestedQty__c</fullName>
        <label>Bkp Suggested Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACCL__Suggested_Quantity__c</fullName>
        <description>The value contains the suggested order quantity that has been calculated via algorithm or that is given by a relevant promotion.</description>
        <label>Suggested Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
	<fields>
        <fullName>MDLZ_LastSavedByUser__c</fullName>
        <description>Indicates whether item was added or updated by user on device</description>
        <label>Last Saved By User</label>
        <type>DateTime</type>
    </fields>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{0000}</displayFormat>
        <label>Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACCL__Order_Template__c.object
<CustomObject>
    <description>Template which controls the behaviour of a sales document.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>The attribute used to enable or disable the current template.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Document_Type__c</fullName>
        <description>Specifies how to handle a sales document regarding payments.</description>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CashCheckIn</fullName>
                </value>
                <value>
                    <fullName>CashCheckOut</fullName>
                </value>
                <value>
                    <fullName>OrderEntry</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>ProductCheckOut</fullName>
                </value>
                <value>
                    <fullName>ProductCheckIn</fullName>
                </value>
                <value>
                    <fullName>TruckAudit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the order template belongs to.</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>From this date on the entry is valid.</description>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <defaultValue>DATE(2099,12,31)</defaultValue>
        <description>Until this date the entry is valid.</description>
        <label>Valid Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RE_Order_Template_ExternalID__c</fullName>
        <description>It contains unique value for external ID</description>
        <externalId>true</externalId>
        <label>RE_Order_Template_ExternalID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Order Template</label>
    <nameField>
        <label>Order Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Account_Number__c</fullName>
        <description>Customer Number.</description>
        <label>Customer Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales organization which the customer belongs to.</description>
        <formula>Text(ACCL__Account_Template__r.ACCL__Sales_Org__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MDLZ_Object_Logging__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to turn ON or OFF the logging enabled on an object</description>
    <fields>
        <fullName>MDLZ_LoggingObjectName__c</fullName>
        <label>MDLZ_LoggingObjectName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDLZ_isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MDLZ_isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>MDLZ_Object_Logging</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MDLZ_isChanged__c</fullName>
        <description>Field to be updated by integration as Int Updated when there is a change on the user record. To be updated by Batch as Batch Processed post processing of the record</description>
        <label>isChanged</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Int Updated</fullName>
                </value>
                <value>
                    <fullName>Batch Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MDLZ_OrderTriggerTestClass.cls
/***************************************************************
Name: MDLZ_OrderTriggerTestClass
======================================================
Purpose:

======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0      Priya Tubachi                11/02/2022     Initial Development    

***************************************************************/
@isTest
private class MDLZ_OrderTriggerTestClass {
    
    
    static testMethod void mdlzOrderReject(){
        List<ACCL__Order__c> ordList = new List<ACCL__Order__c>();
        Profile p1 = [select Id from Profile  where Name ='System Administrator']; 
        
        Profile p2 = [select Id from Profile  where Name ='MDLZ_Integration_User']; 
        User opUser = new User(alias = 'mdlz', email='test123@noemail.com',
                               emailencodingkey='UTF-8', lastname='01 Inbound AltREXwedcxss', languagelocalekey='en_US',IsActive=true,
                               localesidkey='en_US', profileid = p2.Id, country='United States',
                               timezonesidkey='America/Los_Angeles', username='test022al1@noemail.com', ACCL__Sales_Org__c='US01'); 
        
        
        User opUser2 = new User(alias = 'mdlz', email='test1234@noemail.com',
                                emailencodingkey='UTF-8', lastname='01 Inbound AltREXs', languagelocalekey='en_US',IsActive=true,
                                localesidkey='en_US', profileid = p1.Id, country='United States',
                                timezonesidkey='America/Los_Angeles', username='test001@noemail.com', ACCL__Sales_Org__c='US01'); 
        
        
        Account acct = new Account();
        acct.Name ='Mondelez Test Account';
        acct.ACCL__Account_Number__c='Demo Unique123';
        acct.Description ='Test Description';
        
        insert acct;
        
        ACCL__Order_Template__c ordertempEdi = new ACCL__Order_Template__c(Name ='EDI',
                                                                           RecordTypeId =Schema.SObjectType.ACCL__Order_Template__c.getRecordTypeInfosByName().get('Order Entry').getRecordTypeId(),
                                                                           ACCL__Document_Type__c='Order Entry',ACCL__Valid_Thru__c=system.today()+365,
                                                                           ACCL__Valid_From__c=system.today(),RE_Order_Template_ExternalID__c='EDI_US01',
                                                                           ACCL__Sales_Org__c='US01',ACCL__Active__c=true);
        
        insert ordertempEdi;
        System.assertEquals(ordertempEdi.ACCL__Sales_Org__c , 'US01');
        MDLZ_Object_Logging__c trgs = new MDLZ_Object_Logging__c();
        trgs.MDLZ_isActive__c = true;
        trgs.MDLZ_LoggingObjectName__c ='Order';
        trgs.Name ='Order';
        insert trgs;
        
        ACCL__Order__c ord = new ACCL__Order__c();
        ord.MDLZ_LastSavedByUser__c = system.today() - 10;
        ord.ACCL__Phase__c ='Cancelled';
        ord.ACCL__Delivery_Date__c =System.today()+363;
        ord.ACCL__Order_Account__c =acct.Id;
        ord.ACCL__Order_Template__c =ordertempEdi.Id;
        ord.MDLZ_isChanged__c='True';
        ord.MDLZ_isOrderAccepted__c =true;
        ord.ACCL__Customer_Order_Id__c ='1234567899 ';
        ordList.add(ord);
        
        ACCL__Order__c ords = new ACCL__Order__c();
        ords.MDLZ_LastSavedByUser__c = system.today() - 10;
        ords.ACCL__Phase__c ='Routed';
        ords.ACCL__Delivery_Date__c =System.today()+363;
        ords.ACCL__Order_Account__c =acct.Id;
        ords.ACCL__Order_Template__c =ordertempEdi.Id;
        ords.MDLZ_isChanged__c='FALSE';
        ords.ACCL__Customer_Order_Id__c ='t6eteyue';
        ordList.add(ords);
        Database.insert(ordList) ;
        System.assertEquals(ordList[1].ACCL__Phase__c,'Routed');
      
        ACCL__Order_Item__c oItem = new ACCL__Order_Item__c(ACCL__Suggested_Quantity__c =2, MDLZ_BkpSuggestedQty__c =2 ,
                                                            ACCL__Order__c =ordList[0].id);
        insert oItem;
        
        if(ordList[0].ACCL__Phase__c != MDLZ_ConstantHelper.open){
            ordList[0].MDLZ_isChanged__c = MDLZ_ConstantHelper.ChangeFalse;
        }
        update ordList;
        
        
        
        ordList[0].ACCL__Phase__c ='Received By SAP';
        update ordList;
        ordList[0].ACCL__Phase__c='Routed';
        update ordList;
        System.assertEquals(ordList[0].ACCL__Phase__c,'Routed');
        
        
      
        
        ordList[1].ACCL__Phase__c ='Received By SAP';
        update ordList;
        ordList[1].ACCL__Phase__c='Routed';
      
        update ordList;
          
        MDLZ_OrderTriggerHandler pr3 = new MDLZ_OrderTriggerHandler();
        pr3.ResetIsChanged(new List<ACCL__Order__c> {ordList[0]});
        
        System.runAs(opUser){
            Test.startTest();
            ords.ACCL__Customer_Order_Id__c =null ;
            ords.ACCL__Phase__c =null;           
            update ordList[1];            
            Test.stopTest();             
        }
        
       
        System.runAs(opUser){
            ord.MDLZ_isOrderAccepted__c = false;
            update ord;
            MDLZ_OrderTriggerHandler pr = new MDLZ_OrderTriggerHandler();
            pr.ResetIsChanged(new List<ACCL__Order__c> {ordList[0]});
             
        }        
        
        
    }
    
    
}