src/objects/ACCL__Product__c.object
<CustomObject>
    <description>This object records the attributes of a product.</description>
    <fields>
        <fullName>ACCL__Criterion_1_Product_Code__c</fullName>
        <description>Product Code belonging to Criterion_1_Product.</description>
        <formula>ACCL__Criterion_1_Product__r.ACCL__Product_Code__c</formula>
        <label>Criterion 1 Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Criterion_1_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product hierarchy related: Reference to product on Product_Level &apos;Category&apos;.</description>
        <inlineHelpText>Only product with &apos;Category&apos; product level can be selected</inlineHelpText>
        <label>Criterion 1 Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Product__c.ACCL__Product_Level__c</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Product__c</referenceTo>
        <relationshipLabel>Products (Criterion 1 Product)</relationshipLabel>
        <relationshipName>Products01</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Holds the unique external id.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ACCL__Order_Ability__c</fullName>
        <description>This is a roll up summary field to identify the Order able products only. Order Able products are identified by the units of measure which have Order Ability set to true.</description>
        <label>Order Ability</label>
        <summaryFilterItems>
            <field>ACCL__Unit_of_Measure__c.ACCL__Order_Ability__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>ACCL__Unit_of_Measure__c.ACCL__Product__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ACCL__Product_Code__c</fullName>
        <description>Unique identification of a product.</description>
        <externalId>true</externalId>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ACCL__Product_Level__c</fullName>
        <description>Describes the Product Level.</description>
        <label>Product Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Category</fullName>
                </value>
                <value>
                    <fullName>SubCategory</fullName>
                    <label>Sub Category</label>
                </value>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Flavor</fullName>
                </value>
                <value>
                    <fullName>Package</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                    <default>true</default>
                    <label>Product</label>
                </value>
                <value>
                    <fullName>PPG</fullName>
                </value>
                <value>
                    <fullName>Case Config</fullName>
                </value>
                <value>
                    <fullName>Main Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Product_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to product template.</description>
        <label>Product Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Product_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Product_Template__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <description>Describes the sales org which the product belongs to.</description>
        <formula>TEXT(ACCL__Product_Template__r.ACCL__Sales_Org__c)</formula>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <label>Product</label>
	 <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Unit_of_Measure__c.object
<CustomObject>
    <description>Holds the details od the units of measure (logistic unit) of a product.</description>
    <fields>
        <fullName>ACCL__Is_Consumer_Unit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Consumer unit.</description>
        <label>Is Consumer Unit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Is_Order_Unit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default order unit.</description>
        <inlineHelpText>Unit of Measure is default order unit.</inlineHelpText>
        <label>Is Order Unit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Is_Price_Unit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Price unit.</description>
        <inlineHelpText>Unit of Measure is default price unit.</inlineHelpText>
        <label>Is Price Unit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Order_Ability__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Unit of Measure can be ordered.</description>
        <inlineHelpText>Unit of Measue is allowed for ordering.</inlineHelpText>
        <label>Order Ability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Product__c</fullName>
        <description>Reference to product.</description>
        <label>Product</label>
        <referenceTo>ACCL__Product__c</referenceTo>
        <relationshipLabel>Units of Measure</relationshipLabel>
        <relationshipName>Units_of_Measure</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Sort__c</fullName>
        <description>Sequence of unit of measures of a product (from smallest unit to largest unit).</description>
        <label>Sort</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACCL__Unit_Type__c</fullName>
        <description>Type of the unit of measure.</description>
        <label>Unit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SalesUnit</fullName>
                    <default>true</default>
                    <label>SalesUnit</label>
                </value>
                <value>
                    <fullName>Layer</fullName>
                </value>
                <value>
                    <fullName>Pallet</fullName>
                </value>
                <value>
                    <fullName>ConsumerUnit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Unit of Measure</label>
    <nameField>
        <displayFormat>UoM-{00000}</displayFormat>
        <label>Unit of Measure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units of Measure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MDLZ_ProductUnitFlagTestClass.cls
/***************************************************************
Name: MDLZ_ProductUnitFlagTestClass
======================================================
Purpose:
a.Update the UOM for each product as an interim fix for SAP issue
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0     Bharath V       		 27/09/2021     Initial Development 
1.1     Vaidehi Heda              25/03/2022    MAde changes as per Nova Report

***************************************************************/

@isTest
Private class MDLZ_ProductUnitFlagTestClass {
    
    static testMethod void unitMeasure(){
        List<ACCL__Product__c>prodList = new List<ACCL__Product__c>();
        List<ACCL__Unit_of_Measure__c>uomList = new List<ACCL__Unit_of_Measure__c>();
        Test.startTest();
        
        //insert PRoduct Template
        ACCL__Product_Template__c ptemp = new ACCL__Product_Template__c();
        ptemp.Name ='Product Group US01';
        ptemp.ACCL__Description_Language_1__c='Product Group US01';
        ptemp.ACCL__Sales_Org__c ='US01';
        ptemp.RecordTypeId =Schema.SObjectType.ACCL__Product_Template__c.getRecordTypeInfosByName().get('Product').getRecordTypeId();
        ptemp.ACCL__Active__c =true;    
        insert ptemp;
        
        
        ACCL__Product__c prod = new ACCL__Product__c(Name ='Mondelez Product',ACCL__Product_Level__c ='Product',
                                                     ACCL__ExternalId__c='US01POSM0001', ACCL__Product_Template__c=ptemp.id,ACCL__Product_Code__c='US01POSM0001',
                                                     RecordTypeId =Schema.SObjectType.ACCL__Product__c.getRecordTypeInfosByName().get('Product Group').getRecordTypeId());
        
        insert prod;
        ACCL__Product__c prod2 = new ACCL__Product__c(Name ='Mondelez Product2',ACCL__Product_Level__c ='Product',
                                                      ACCL__Criterion_1_Product__c=prod.id,ACCL__Product_Template__c=ptemp.id);
        
        prodList.add(prod2);
        
        ACCL__Product__c prod3 = new ACCL__Product__c(Name ='Mondelez Product3',ACCL__Product_Level__c ='Product',
                                                      ACCL__Criterion_1_Product__c=prod.id,ACCL__Product_Template__c=ptemp.id);
        
        prodList.add(prod3);        
        insert prodList;        
        
        //Insert UOM
        ACCL__Unit_of_Measure__c unitmeasure = new ACCL__Unit_of_Measure__c();        
        unitmeasure.ACCL__Product__c = prodList[1].Id;
        unitmeasure.ACCL__Unit_Type__c ='ConsumerUnit';
        unitmeasure.ACCL__Sort__c =1;
        unitmeasure.ACCL__Is_Price_Unit__c = false;
        unitmeasure.ACCL__Is_Consumer_Unit__c = false;
        unitmeasure.ACCL__Is_Order_Unit__c = true;
        unitmeasure.ACCL__Order_Ability__c = true;
        uomList.add(unitmeasure);
        
        prod2 = [select id , name , ACCL__Criterion_1_Product_Code__c from ACCL__Product__c where id =: prodList[0].id];
        system.assertEquals('US01POSM0001',prod2.ACCL__Criterion_1_Product_Code__c);
        
        ACCL__Unit_of_Measure__c unitmeasure1 = new ACCL__Unit_of_Measure__c(); 
        unitmeasure1.ACCL__Product__c = prodList[1].Id;
        unitmeasure1.ACCL__Unit_Type__c ='Sales Unit';
        unitmeasure1.ACCL__Sort__c =2;
        unitmeasure1.ACCL__Is_Price_Unit__c = true;
        unitmeasure1.ACCL__Is_Consumer_Unit__c = false;
        unitmeasure1.ACCL__Is_Order_Unit__c = true;
        unitmeasure1.ACCL__Order_Ability__c = true;        
        uomList.add(unitmeasure1);
        
        ACCL__Unit_of_Measure__c unitmeasure2 = new ACCL__Unit_of_Measure__c();        
        unitmeasure2.ACCL__Product__c = prodList[0].id;
        unitmeasure2.ACCL__Unit_Type__c ='SalesUnit';
        unitmeasure2.ACCL__Sort__c =3;
        unitmeasure2.ACCL__Is_Price_Unit__c = true;
        unitmeasure2.ACCL__Is_Consumer_Unit__c = false;
        unitmeasure2.ACCL__Is_Order_Unit__c = true;
        unitmeasure2.ACCL__Order_Ability__c = true;
        uomList.add(unitmeasure2);
        
        database.insert(uomList);
        
        MDLZ_ProductUnitFlagChange pr = new MDLZ_ProductUnitFlagChange();
        pr.ConsumerSalesUnitChange(new List<ACCL__Unit_of_Measure__c> {uomList[0]});
        pr.ConsumerSalesUnitChange(new List<ACCL__Unit_of_Measure__c> {uomList[1]});
        
        Test.stopTest();  
    }
    
    
}