src/objects/ACCL__Org_Unit__c.object
<CustomObject>
    <description>Holds the details of the organization unit object, defining a manufacturer´s organizational structure.</description>
    <fields>
        <fullName>ACCL__Org_Level__c</fullName>
        <description>Level of an organization unit regarding a organization type.</description>
        <label>Org Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>SalesOrganization</fullName>
                </value>
                <value>
                    <fullName>SalesOffice</fullName>
                </value>
                <value>
                    <fullName>SalesRep</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Org Unit</label>
    <nameField>
        <label>Org Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Org_Unit_User__c.object
<CustomObject>
    <description>Holds the details of the relationship between organization unit and user.</description>
    <fields>
        <fullName>MDLZ_isOrgUnitChanged__c</fullName>
        <description>This field is updated by Integration to &quot;Int Updated&quot; when there is a org unit change for the user.</description>
        <label>isOrgUnitChanged</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Int Updated</fullName>
                </value>
                <value>
                    <fullName>Batch Processed</fullName>
                </value>
                <value>
                    <fullName>TT Processed</fullName>
                </value>
                <value>
                    <fullName>RDR Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Org_Unit__c</fullName>
        <description>Reference to an org unit assigned to a user.</description>
        <label>Org Unit</label>
        <lookupFilter>
            <active>false</active>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Org_Unit__c</referenceTo>
        <relationshipLabel>Org Unit Users</relationshipLabel>
        <relationshipName>Org_Unit_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Org Unit User</label>
    <nameField>
        <displayFormat>OUU-{0000}</displayFormat>
        <label>Org Unit User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Unit Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ExceptionLog__c.object
<CustomObject>
    <description>To track all exceptions occuring</description>
    <fields>
        <fullName>Error_Line_Number__c</fullName>
        <label>Error Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExceptionCode__c</fullName>
        <label>Exception Code</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionDetails__c</fullName>
        <label>Exception Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MethodName__c</fullName>
        <label>Method Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EXCP - {00000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MDLZ_UpdateTerritoryFlagBatch.cls
/***************************************************************
Name: MDLZ_UpdateTerritoryFlagBatch
======================================================
Purpose:
Updates the org unit changed Flag for orphaned territories from Int Updated to Batch Processed
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0      Priya Tubachi                05/04/2021     Initial Development    

***************************************************************/
global class MDLZ_UpdateTerritoryFlagBatch implements Database.Batchable<sObject>,Schedulable{  
    
    //Defining the Scheduled Batch Size thru custom label
    public integer defaultChildBatchSize;
      
    
    global MDLZ_UpdateTerritoryFlagBatch(integer childBatchSize){
        defaultChildBatchSize = childBatchSize;
    }
    
    //query locator for the batch to retrieve records
    global Database.QueryLocator start(Database.BatchableContext BC)    
    {
        String intUpdated = MDLZ_ConstantHelper.IntUpdated;
        String territory = MDLZ_ConstantHelper.Territory;
        String query ;
        query = 'select id from ACCL__Org_Unit_User__c where MDLZ_isOrgUnitChanged__c =: intUpdated and ACCL__Org_Unit__r.ACCL__Org_Level__c =: territory ';
        if(test.isRunningTest()){
            query = 'select id from ACCL__Org_Unit_User__c where MDLZ_isOrgUnitChanged__c =: intUpdated and ACCL__Org_Unit__r.ACCL__Org_Level__c =: territory Limit 1';
        }
        return Database.getQueryLocator(query);
        
    }
    
    //execute method of the batch class
    global void execute(Database.BatchableContext BC, List<sobject> scope)
    {
        
        system.debug('Size of records to be cleaned up '+scope.size());
        List<sObject> orgUnitUserDbList = new List<sObject>();
        List<ExceptionLog__c> errorList = new List<ExceptionLog__c>();
        MDLZ_ErrorExceptionHandler exc = new MDLZ_ErrorExceptionHandler();
        
        try{
            for(sObject orgUnit: scope){
                
                orgUnit.put('MDLZ_isOrgUnitChanged__c',MDLZ_ConstantHelper.BatchProcessed);
                orgUnitUserDbList.add(orgUnit);
            }
            
            if(orgUnitUserDbList.size()> 0){
                List<Database.SaveResult>  srList =  database.update(orgUnitUserDbList,false); 
                exc.saveResultErrors(srList,orgUnitUserDbList,'MDLZ_UpdateTerritoryFlagBatch()','ACCL__Org_Unit_User__c', 'Id');
                
            }
        }catch(Exception e){   
            errorList.add( new ExceptionLog__c(MethodName__c = 'MDLZ_UpdateTerritoryFlagBatch()',ExceptionDetails__c = e.getMessage(),Error_Line_Number__c = e.getLineNumber(),
                                               ExceptionCode__c = e.getTypeName()) );
           
        }
       
        if(errorList.size() > 0){
            exc.insertExceptions(errorList); 
        }
        
    }
    
    //schedulable execute method for the batch class
    global void execute(SchedulableContext ctx) {
        Database.executeBatch(this, defaultChildBatchSize); 
    } 
    
    //finish method of the batch class
    global void finish(Database.BatchableContext BC)
    {
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob details = [SELECT Id, Status,ExtendedStatus,MethodName, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email 
                                FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        System.debug('Batch Process Details' +details);        
    }
}