src/objects/ACCL__Sales_Organization__c.object
<CustomObject>
    <description>This Object holds the details of the Sales Organization.</description>
    <fields>
        <fullName>ACCL__Account_Product_List_Type__c</fullName>
        <description>Defines which Product list has to be used</description>
        <label>Account Product List Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>global</fullName>
                    <default>true</default>
                    <label>global</label>
                </value>
                <value>
                    <fullName>timedependent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Currency__c</fullName>
        <description>Currency of the sales organization</description>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>NOK</fullName>
                </value>
                <value>
                    <fullName>CHF</fullName>
                </value>
                <value>
                    <fullName>RUB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Description_Language_1__c</fullName>
        <label>Description Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Distance_Unit__c</fullName>
        <label>Distance Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>km</fullName>
                    <default>true</default>
                    <label>km</label>
                </value>
                <value>
                    <fullName>miles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__First_Day_Of_Week__c</fullName>
        <description>Describes the days of the week</description>
        <label>First Day Of Week</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__First_Week_Of_Year__c</fullName>
        <description>This field displays the week for call scheduling</description>
        <label>First Week Of Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Language_1__c</fullName>
        <description>Language for the sales organization</description>
        <label>Language 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>it</fullName>
                </value>
                <value>
                    <fullName>es</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Promotion_Access_Definition_Policy__c</fullName>
        <description>Defines whether the edit and access rights are dependent on the product categories the user has assigned or the account and product category relationship.</description>
        <label>Promotion Access Definition Policy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Independent_Anchors</fullName>
                    <default>true</default>
                    <label>Independent Anchors</label>
                </value>
                <value>
                    <fullName>Combined_Anchors</fullName>
                    <label>Combined Anchors</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Promotion_Aggregation_Level__c</fullName>
        <description>Defines at which level the product is located.</description>
        <label>Promotion Aggregation Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Category</fullName>
                </value>
                <value>
                    <fullName>SubCategory</fullName>
                </value>
                <value>
                    <fullName>Brand</fullName>
                    <default>true</default>
                    <label>Brand</label>
                </value>
                <value>
                    <fullName>Flavor</fullName>
                </value>
                <value>
                    <fullName>Package</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Sales_Org_Value__c</fullName>
        <label>Sales Org Value</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Used_Reference_Date__c</fullName>
        <description>Determines which value is set in the view for the product hierarchy resolution reference date</description>
        <label>Used Reference Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>startdate</fullName>
                    <default>true</default>
                    <label>startdate</label>
                </value>
                <value>
                    <fullName>dynamic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Volume_Unit__c</fullName>
        <label>Volume Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>l</fullName>
                    <default>true</default>
                    <label>l</label>
                </value>
                <value>
                    <fullName>gallon</fullName>
                </value>
                <value>
                    <fullName>cm3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Weight_Unit__c</fullName>
        <label>Weight Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ton</fullName>
                </value>
                <value>
                    <fullName>kg</fullName>
                    <default>true</default>
                    <label>kg</label>
                </value>
                <value>
                    <fullName>pound</fullName>
                </value>
                <value>
                    <fullName>oz</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Organization</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Organization</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ACCL__Sales_Org__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ACCL__Sales_Org</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MDLZ_NewUserSetupTestClass.cls
/***************************************************************
Name: MDLZ_NewUserSetupTestClass
======================================================
Purpose:
a.Create a batch of 100 users per batch for all users last modified today
	to assign sales org and user settings.
======================================================
History
-------
VERSION     AUTHOR         REVIEWER      DATE             DETAIL              Description
1.0      Bharath V                    Initial Development    Test class for New user setup Apex class and Batch

***************************************************************/
@isTest
public class MDLZ_NewUserSetupTestClass {   
    static testMethod void userSetup(){
       
        Profile p1 = [select Id from Profile  where Name ='System Administrator']; 
        
                          
        ACCL__Sales_Organization__c salesorg = new ACCL__Sales_Organization__c();
        salesorg.Name ='US01';
        salesorg.ACCL__Currency__c ='US Dollar';
        salesorg.ACCL__Sales_Org_Value__c ='US01';
        salesorg.ACCL__Distance_Unit__c ='Miles';
        salesorg.ACCL__Description_Language_1__c ='US01';
        salesorg.ACCL__Language_1__c ='English';
        salesorg.ACCL__First_Week_Of_Year__c ='';
        salesorg.ACCL__First_Day_Of_Week__c ='';
        salesorg.ACCL__Account_Product_List_Type__c ='Global';
        salesorg.ACCL__Used_Reference_Date__c ='Start Date';
        salesorg.ACCL__Promotion_Aggregation_Level__c ='Brand';
        salesorg.ACCL__Promotion_Access_Definition_Policy__c='Independent Anchors';
        salesorg.ACCL__Weight_Unit__c ='pound';
        salesorg.ACCL__Volume_Unit__c ='gallon';
        insert salesorg;
        
        User opUser = new user(alias = 'test123', email='test123@noemail.com',
                            emailencodingkey='UTF-8', firstName='Test', lastname='Testing', languagelocalekey='en_US',IsActive=true,
                            localesidkey='en_US', profileid = p1.Id, country='United States',
                            timezonesidkey='America/Los_Angeles', username='test04@noemail.com', ACCL__Sales_Org__c=salesorg.Name); 
        insert opUser;
        
        
        ACCL__Sales_Organization_User__c sOrgUser = new ACCL__Sales_Organization_User__c();
        sOrgUser.ACCL__Sales_Organization__c =salesorg.id;
        sOrgUser.ACCL__User__c = opUser.id;
        insert sOrgUser;
        
        ACCL__User_Setting__c us = new ACCL__User_Setting__c();
        us.ACCL__User__c=opUser.id;
        us.ACCL__Default_Management_Type__c ='Sales';
        us.ACCL__Landing_Page__c ='UserCockpit';
        us.ACCL__Display_Weekend__c =true;
        insert us;
       

        
       
        // Run your code with inserted user.
        
             
        Test.startTest();
        
        MDLZ_NewUserSetup nuserSetup=new MDLZ_NewUserSetup();
        nuserSetup.getNewUsers(new List<user> {opUser});
         
        MDLZ_NewUserSetupBatch batch1= new MDLZ_NewUserSetupBatch(20);
        DataBase.executeBatch(batch1,20);
        SchedulableContext sc = null;
        
        MDLZ_NewUserSetupBatch bdsec=new MDLZ_NewUserSetupBatch(20);
        bdsec.execute(sc);
            
         Test.stopTest();
    }
        

}