src/objects/ACCL__Account_Set__c.object
<CustomObject>
    <description>Object for the creation of Customer Sets.</description>
    <label>Customer Set</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACCL__Call_Template__c.object
<CustomObject>
    <description>Template describing basic call behaviour.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Call Template</label>
    <nameField>
        <label>Call Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Job_Definition_List__c.object
<CustomObject>
    <description>Holds the set of questions/surveys that are to be carried out in the respective call and contains further relevant configurations.</description>
    <fields>
        <fullName>ACCL__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__Approval_State__c</fullName>
        <label>Approval State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Relevant</fullName>
                    <default>true</default>
                    <label>Not Relevant</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Call_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Call Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Call_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>ACCL__Call_Template__c.ACCL__Sales_Org__c</field>
                <operation>equals</operation>
                <valueField>$Source.ACCL__Sales_Org__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Call_Template__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Job_Definition_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Default_Management_Type__c</fullName>
        <label>Default Management Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Job_Definition_List_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Activity Template</label>
        <referenceTo>ACCL__Job_Definition_List_Template__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Job_Definition_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__Standard_Jobs__c</fullName>
        <formula>ACCL__Job_Definition_List_Template__r.ACCL__Standard_Jobs__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Standard Jobs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACCL__User_Policy__c</fullName>
        <label>User Policy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                    <label>All</label>
                </value>
                <value>
                    <fullName>OnlyMain</fullName>
                </value>
                <value>
                    <fullName>First</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACCL__Valid_From__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ACCL__Valid_Thru__c</fullName>
        <inlineHelpText>Updated based on activity template and valid from value.</inlineHelpText>
        <label>Valid Thru</label>
        <type>Date</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACCL__Job_Definition_List_Account_Set__c.object
<CustomObject>
    <description>Junction object between Job Definition List and Customer Set.</description>
    <fields>
        <fullName>ACCL__Account_Set__c</fullName>
        <label>Customer Set</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ACCL__Sales_Org__c</field>
                <operation>equals</operation>
                <valueField>ACCL__Account_Set__c.ACCL__Sales_Org__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Account_Set__c</referenceTo>
        <relationshipLabel>Job Definition List Customer Sets</relationshipLabel>
        <relationshipName>Job_Definition_List_Account_Sets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACCL__Job_Definition_List__c</fullName>
        <label>Activity</label>
        <referenceTo>ACCL__Job_Definition_List__c</referenceTo>
        <relationshipLabel>Activity Customer Sets</relationshipLabel>
        <relationshipName>Job_Definition_List_Account_Sets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity Customer Set</label>
    <nameField>
        <displayFormat>JDLCS-{0000}</displayFormat>
        <label>Activity Customer Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Customer Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GenerateJobListInputView.cls
/**  PROGRAM NAME : GenerateJobListInputView 
     * This class is used for preparing the query locator that will determine the scope of the batch.
     * This class returns the Job_Definition_List records from the Org.
     * @see    GenerateJobListBatch
     * @version  1.0
     * @Created Date 2018-10-18 
*/
public class GenerateJobListInputView {
	/** Private Variable */
    private static final string CANCELED = 'Canceled';
       
    
    /**
     *  @description Returning query for database.queryLocator passing this to start method in GenerateJobListBatch
     *  @param None
     *  @return Database.QueryLocator
     *  @throws None
     */
    public Database.QueryLocator getObjectDataReader() {
        Date today = System.today();
        String query = 'SELECT  '
            +'(SELECT ACCL__Account__c FROM ACCL__Job_Definition_List_Accounts__r WHERE ACCL__Excluded__c = false ),'
            +'(SELECT ACCL__Account_Set__c FROM ACCL__Job_Definition_List_Account_Sets__r ),'
            +' ACCL__Active__c, ACCL__Call_Template__c, ACCL__Default_Management_Type__c, Id, ACCL__User_Policy__c, ACCL__Valid_From__c, ACCL__Valid_Thru__c '
            +' FROM ACCL__Job_Definition_List__c '
            +' WHERE ACCL__Active__c = true AND ACCL__Valid_Thru__c >= TODAY  AND ACCL__Job_Definition_List_Template__r.ACCL__Standard_Jobs__c = false AND ACCL__Approval_State__c != :CANCELED ';
        
        Database.QueryLocator ql = Database.getQueryLocator(query);
        return ql;
    }
}