src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACCL__Account_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to customer template.</description>
        <label>Customer Template</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ACCL__Account_Template__c.ACCL__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACCL__Account_Template__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACCL__City__c</fullName>
        <description>Name of a city.</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Holds the unique external id.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ACCL__Name_2__c</fullName>
        <description>Alternate name for the customer.</description>
        <label>Name 2</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACCL__Street__c</fullName>
        <description>Name of a street.</description>
        <label>Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AddOnAccountTestFactory.cls
//FLS_Create, FLS_Create_Partial, FLS_Update, FLS_Update_Partial - False Positive
//This is a test data generation class and must be accessed in system context. No CRUD permission check is required.
@isTest
public class AddOnAccountTestFactory {
    public static Account defaultAccount;
    public static Account defaultAccountWithSaleOrg;
    public static Account defaultAccountWithSaleOrgQueried;
    
    public static Account buildAccount(Integer nameSuffix) {
        Account account = new Account();
        account.ACCL__City__c = 'Test City';
        account.ACCL__Street__c = 'Test Street';
        account.Name = AddOnConstants.Name+nameSuffix; 
        account.ACCL__Name_2__c = 'testX'+nameSuffix;
        account.ACCL__ExternalId__c = 'ExtID_' + nameSuffix + '_' + Crypto.getRandomInteger();
        return account;
    }

    public static Account insertAccount(Integer nameSuffix){
        Account account = buildAccount(nameSuffix);
        insert account;
        return account;
    }
    
    public static Account buildAccount(Integer nameSuffix,ACCL__Account_Template__c accTemp) {
        Account account = buildAccount(nameSuffix);
        account.ACCL__Account_Template__c = accTemp.Id;
        return account;
    }

    public static Account getDefaultAccount() {
        if( defaultAccount == null ){
            defaultAccount = insertAccount( -1 );
        }
        return defaultAccount;
    }

    public static Account getAccountWithSalesOrg(
        ACCL__Account_Template__c accTemp,
        Integer nameSuffix
    ) {
        Account account = buildAccount(nameSuffix, accTemp);
        insert Account;
        return account;
    }

}